### ISSUE TITLE
Duda Entrega Proyecto

### ISSUE THREAD

**Issue by sbarriag** [IIC2413/Syllabus-2024-2#10]
Hola, quería preguntar por lo que deberia "retornar" el código que nos piden porque no me quedo muy claro leyendo el enunciado, cuando el código Bananer.php se corre en la consola, automaticamente se deben imprimir todas las matrices que nos piden en el enunciado? o se debe cumplir alguna condicion para imprimir esas matrices? (por ejemplo que el usuario que corre el código tenga que presionar un botón para pedir la matriz Persona y recien ahí se muestre) 

Muchas gracias

**Comment by Mateodlcc** [comment]
Lo ideal sería que hubiese una forma de acceder a cada una de las consultas por separado. Si te fijas, la primera consulta del enunciado aplica para un RUT en particular el cual debe ser ingresado por consola.

Por tanto, la idea sería que pudieses aplicar lo último que mencionas.

**Comment by sbarriag** [comment]
Capto, entonces si mi programa por ejemplo (todo esto obviamente lo explicaré en el informe) cuando lo corró te da la opción de ver las matrices o de hacer las consultas que se mencionan en el enunciado estaria bien?

**Comment by Mateodlcc** [comment]
Estaría perfecto!
