### ISSUE TITLE
Secciones cursos

### ISSUE THREAD

**Issue by Paulaverastegui** [IIC2413/Syllabus-2024-2#101]
Hola! En la matriz de los cursos, se pide incluir todos los cursos con el número de secciones. Sin embargo, hay datos del archivo 1 en que está el curso y el número de sección es 2 pero no esta el dato del curso con su número de sección 1. En ese caso, debo considerar que el curso solo tiene una sección (la 2) o cómo existe la sección 2 debo asumir que también existe la 1 y por ende posee dos secciones.

Muchas gracias!

**Comment by ypne** [comment]
Si, puedes asumir que si aparece sección 2 también existe la 1
