### ISSUE TITLE
Cursos con mismo nombre y diferente sigla

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2413/Syllabus-2024-2#102]
Hola!

Me di cuenta que hay cursos con mismo nombre y distinta sigla. ¿Cómo debo identificar los cursos? ¿Por su nombre o por su sigla? Ya que cambia la matriz y por ende cambia el cómo se busca la información y cómo se responde a las consultas. Muchas gracias

**Comment by ypne** [comment]
Los cursos se diferencian por sigla, es normal que haya cursos con el mismo nombre. Por ejemplo Calculo I puede ser diferente si está para matemáticas, ingeniería o economía, pero sigue siendo cálculo I
