### ISSUE TITLE
Consultas y uso de matrices

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2413/Syllabus-2024-2#104]
Hola!

Para responder a las consultas del usuario, por ejemplo la carga académica acumulada, ¿es necesario hacer uso de las matrices? ¿o se puede usar otra estructura de datos que hagamos a partir de los archivos csv?

**Comment by waldoosg** [comment]
Es a tu elección de donde obtienes los datos, mientras puedas obtener los datos pedidos por la consulta no debería haber problemas.
