### ISSUE TITLE
Flujo tarea

### ISSUE THREAD

**Issue by ignanuyens** [IIC2413/Syllabus-2024-2#105]
Hola, tengo dudas respecto al flujo de la tarea, una vez ya creadas todas las matrices.

El enunciado dice:

Realizar las siguientes consultas sobre los datos, entregando el resultado por consola o en archivo:
1. Carga acad´emica acumulada: Entregar, en una l´ınea, cada curso realizado (cualquiera sea la calificaci´on) por un estudiante identificado por su RUN ingresado por consola, indicando: periodo del curso, sigla del curso, curso, nota y calificaci´on. Al final de cada per´ıodo la nota promedio del semestre (PPS) y al final del reporte la nota promedio de todos los cursos (PPA)
2. Lista de curso: Entregar, en una l´ınea, cada estudiante perteneciente a un curso y periodo, especificado por consola, indicando: cohorte, nombre completo, RUN y n´umero de estudiante.

No entiendo si solamente me van a entregar el rut y en qué formato (con o sin guión, separado por puntos o todo seguido, ...). Una vez que me entreguen el rut, debo  entregar para cada curso realizado por él; periodo del curso, sigla del curso, curso, nota y calificación, sin embargo no entiendo a qué hacen referencia con "Al final de cada período la nota promedio del semestre (PPS) y al final del reporte la nota promedio de todos los cursos (PPA)". 
Por otro lado, no comprendo si kuego de entregarme el rut, me entregarán un curso y periodo (leyendo el punto 2.) y debo entregar; cohorte, nombre completo, RUN y n´umero de estudiante.

¿Puedo suponer que correrán el código de la forma?: php bananer.php rut curso periodo
De esta forma me entregarán toda la información necesaria para la carga académica acumulada y el listado del curso. Si no lo puedo suponer, agradecería que me explicaran con más detalle cómo nos entregarán los parámetros.

De antemano, muchas gracias :)

**Comment by waldoosg** [comment]
Sobre el formato de como se ingresará el RUT, no existe alguno predeterminado. Te recomiendo especificarlo en el informe de tu tarea como lo recibe tu código. 
Respecto a la entrega de lista de curso, se espera que se divida en semestres.
