### ISSUE TITLE
¿Nombres con guión?

### ISSUE THREAD

**Issue by maromero-21** [IIC2413/Syllabus-2024-2#106]
¿El guion se considera como carácter válido para efecto de los nombres? A continuación dejo los ejemplos:
AXELL KESSLEY CONEJEROS BUONO-CORE
MEI-LIN ESTER CONCHA CAYUQUEO
HILEN GIANITZA LOWICK-RUSSELL COÑUEN
LISSETTE MEI-LIN LEGISOS ARNES
MEI-LIN EUGENIA GOMILA MONTELLANO
JORGE NESTOR CARVACHO LOWICK-RUSSELL
NEVENKA ANISE COÑUEN BUONO-CORE
IRINA HOMERO LUPPICHINI BUONO-CORE
MILAGROS KATHERINNE BUONO-CORE URBINA

**Comment by TomasKetterer** [comment]
Es un caso que debes considerar tú si está bien o no. En tu informe debes explicitar lo que vayas a hacer, ya sea borrar el guion y juntar las dos partes, dejarlo u alguna otra opción (no debería ser necesario borrarlo). En tu código simplemente deberás hacer lo que dijiste que ibas a hacer en tu informe
