### ISSUE TITLE
Mismo alumno, distintas secciones.

### ISSUE THREAD

**Issue by antoniamarin** [IIC2413/Syllabus-2024-2#107]
Hola! Qué hago si en el archivo 1 tengo dos filas con el mismo alumno, mismo ramo, mismo periodo, etc. Pero está en dos secciones distintas? Debería invalidar uno de los dos datos? Cómo sé cuál invalidar?

**Comment by ypne** [comment]
Sigue el principio de mantener la mayor cantidad de datos, deja el de nota superior
