### ISSUE TITLE
algunas dudas respecto al proyecto

### ISSUE THREAD

**Issue by yonieeh** [IIC2413/Syllabus-2024-2#109]
hola! 
1. dentro de los archivos csv, existe la posibilidad de que hayan filas con atributos de tipos distintos al esperado? por ejemplo, un numero de estudiante que contenga caracteres, o run que contenga caracteres, cosas de ese estilo. 
2. columnas como nota en el archivo 1 dice que puede contener nulo. ese caso solo se podria dar si el estudiante se eximio del curso o lo convalido? en caso de que sea asi, entonces la nota solo podria ser nula en uno de los casos anteriores y en el caso de que tanto calificacion como nota sean nulos la tupla seria invalida? 

eso seria todo, muchas gracias!

**Comment by waldoosg** [comment]
1. Sobre los datos se espera que vengan en el formato mencionado, igualmente  es parte de la tarea poder identificar datos malos.
2. Esa nota se marca como dato faltante y no se considera para el cálculo de promedios.
