### ISSUE TITLE
Consulta sobre la evaluación de la detección de errores

### ISSUE THREAD

**Issue by joacopython** [IIC2413/Syllabus-2024-2#110]
Hola,

Tengo una duda sobre cómo se evaluará la detección de errores en nuestro proyecto. Inicialmente, entendí que era necesario desarrollar un programa que no solo reconociera los errores, sino que también los corrigiera o eliminara automáticamente. Sin embargo, en la clase de hoy, el profesor mencionó que esto no es necesario; que basta con que el programa reconozca los errores, y que luego podemos corregirlos manualmente de la manera que consideremos más adecuada.

Esto me genera varias dudas:

   1) Si mi código detecta un error, por ejemplo, un valor "diurno" en el campo de CONTRATO que debería estar en JORNADA, ¿no es necesario que mi programa lo corrija automáticamente y lo reubique en el campo correcto? ¿Es válido que yo haga esta corrección manualmente después de que el error ha sido identificado?

   2) ¿Cómo se evaluará el control de errores en este caso? ¿Se valorará más la detección automática de errores o también se considerará la corrección manual posterior?

  3) Cuando ejecuten BANANER ¿Es necesario que se haga la detecciòn de errores denuevo? ¿Se puede abrir directamente el archivo ya corregido con los errores filtrados?

Agradezco cualquier aclaración sobre estos puntos para poder ajustar mi trabajo según las expectativas del curso.

Gracias de antemano.

**Comment by ypne** [comment]
A.- Se pide que el programa DETECTE errores eso es mandatorio
B.- La corrección es manual o automática, siempre es mejor automatizarlo pero a veces no se puede para todar las restricciones
1.- Es válido corregirlo manualmente
2.- Se evalúa la detección, respecto a la calidad de la detección el único parámetro es que se trate de minimizar la pérdida de datos
3.- Se puede hacer sobre archivos de input buenos
