### ISSUE TITLE
Agregar RUN a la matriz de estudiantes

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2413/Syllabus-2024-2#111]
Hola!

Según lo hablado en la clase de hoy, sólo para confirmar ¿sí es válido agregar el atributo de RUN a la matriz de estudiantes? Para así poder relacionarla con la matriz de personas cuando se realice una consulta sobre la carga académica. Muchas gracias.

**Comment by ypne** [comment]
SI
