### ISSUE TITLE
Informe P0

### ISSUE THREAD

**Issue by vicenterodas** [IIC2413/Syllabus-2024-2#113]
Hola, no me queda claro a que se refiere el punto 3. de contenido del informe.
3. Nombre de los archivos de salida y explicacion de su contenido

Gracias

**Comment by ypne** [comment]
Si la salida la hacen por archivos y no está paramétrico deben dar el nombre y deben indicar el contenido

**Comment by Ilancf** [comment]
Puede tambien explicar a que se refiere el punto 1. de contenido del informe.
1. Análisis de los datos (tipos entregados en los archivos
Gracias

**Comment by MartyMolina** [comment]
Al realizar la tarea, hiciste un análisis visualizando los datos, identificando las distintas matrices que correspondían y los errores que contenían. Por lo tanto, debes explayarte en el análisis que realizaste para abordar la tarea con respecto a los datos.
