### ISSUE TITLE
Pregunta de criterio en la eliminaciòn de datos (en base a la issue #80)

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#114]
Le quiero hacer la pregunta porque ya esta cerrada la issue y me queda una duda con respecto a lo que mencionó en clases, yo creo que si hay un alumno con todo los datos iguales pero dio un ramo supuestamente en 2 secciones distintas de un mismo ramo y sacó 2 notas distintas, entonces uno debe dejar ambos ya que no se sabe cuál es la real ni en que sección estuvo, entonces yo al menos solo borro filas que en verdad no sirven o que son exactamente iguales, para que así pierda la menor cantidad de datos, prefiriendo hacer el cálculo de su promedio con ambos ramos y contándolo 2 veces pero sin perder ninguno.

Este criterio es válido?

**Comment by ypne** [comment]
Si es válido
