### ISSUE TITLE
Consulta Bloqueo y consola

### ISSUE THREAD

**Issue by martincortes21** [IIC2413/Syllabus-2024-2#115]
¡Hola! Tengo un par de dudas, en el archivo 1 en el bloqueo, me salen N y algunas S, ¿N sería que no tiene bloqueo?
Y la segunda, cuando pedimos argumentos por consola en la lista de curso, se pide el nombre del curso o la sigla del curso?

¡Muchas gracias!

**Comment by ypne** [comment]
1.- efectivamente N es no bloqueado y S es bloqueado
2.- respondido en discussions 57
