### ISSUE TITLE
Jornada Matriz Profesores

### ISSUE THREAD

**Issue by Gansopio** [IIC2413/Syllabus-2024-2#116]
Hola, 
para la matriz de datos de Datos de Profesor dice que hay que poner si el profesor es de jornada diurna O vespertina, que pasa si es de ambos? Pongo ambos nomas?

**Comment by ypne** [comment]
ya está respondida en otra issue

**Comment by Gansopio** [comment]
Gracias, acabo de cachar que estaba viendo las issues abiertas nomas
