### ISSUE TITLE
Prohibicion de bibliotecas o similar

### ISSUE THREAD

**Issue by CristianGarcia2310** [IIC2413/Syllabus-2024-2#117]
Me gustaria preguntar si existe alguna biblioteca prohibida para el trabajo, o si existe alguna prohibicion o similar respecto a buscar codigo en internet

**Comment by ypne** [comment]
Solo están permitidas las bibliotecas instaladas en el server.
Por lo demás puedes referirte a la "POLÍTICA DE INTEGRIDAD ACADÉMICA DEL DEPARTAMENTO DE CIENCIA DE LA COMPUTACIÓN" incluida en el programa de curso.
