### ISSUE TITLE
Matriz Estudiante 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#118]
Hola tengo una duda en cuanto la matriz estudiante. Se dice que los registros no pueden estar duplicados sin embargo la matriz no esta asociada al rut si no al número de estudiante; por lo tanto como hay alumnos que tienen más de un número de estudiante entonces si van a haber registros (en cuanto respecta a la persona en si) repetidos

**Comment by TomasKetterer** [comment]
Hola! La idea de que no hayan registros duplicados es que no hayan líneas enteras que estén exactamente iguales a otras. Te recomiendo leer otras issues al respecto, ya que se ha comentado bastante, pero cuando un estudiante tiene más de un número de estudiante, puede llegar a ocurrir que haya un registro "repetido", es decir que tenga todo o casi todo igual excepto el número de estudiante, y en esos casos se debe manejar de la forma que se estime conveniente e indicando en el informe la forma en que se manejó. A veces se dejan los registros, a veces se deben arreglar, otras veces se eliminan, etc. De nuevo, recomiendo mucho ir a revisar otras issues al respecto :)
