### ISSUE TITLE
duda con la nota del archivo

### ISSUE THREAD

**Issue by carlosmartellus** [IIC2413/Syllabus-2024-2#12]
Hola, la nota se debe representar con uno o dos decimales?

**Comment by Mateodlcc** [comment]
Queda a tu criterio, ambas son válidas.

Ahora, si es que la pregunta va para la primera parte de la tarea (migración y limpieza de datos), recuerda que los datos deberían mantenerse, por lo tanto si las notas presentaban 1 o 2 decimales, esto debe mantenerse.

Si la pregunta va orientada a la segunda parte (consultas) entonces queda a tu criterio. A modo de recomendación, pueden basarse en el modelo que implementa la UC (ver la ficha acumulada).
