### ISSUE TITLE
Pregunta de criterio en la eliminaciòn de datos (Base issue #80 y  #114)

### ISSUE THREAD

**Issue by SebastianArroyoSanchez** [IIC2413/Syllabus-2024-2#120]
Creo un nuevo Issue respecto al criterio en la eliminación de datos.

Tengo dos casos distintos: 

1) Un mismo alumno realiza un curso-periodo en dos secciones, donde (en base a lo leído) debo quedarme con uno (el con nota más alta).

2) Un mismo alumno realiza dos veces un mismo curso-periodo-sección. Para esto ¿Puedo aplicar el mismo criterio (mantener solamente el con nota más alta) o para este caso debiese dejar ambas filas? 

PD: Asumí que uno se debe descartar uno, no se si lo idóneo es seleccionar la nota más alta o debo promediar ambas y dejar solamente una. No me quedó claro con las issues.

¡Muchas gracias de antemano!

**Comment by TomasKetterer** [comment]
Hola, en tu informe puedes explicitar la decisión que tomes. Si te quedas con el alumno con nota más alta, mientras justifiques tu decisión, está bien hacer eso. En caso de ser una línea repetida, elimínala. En otro caso es necesario analizar la línea y trabajarla como tu estimes conveniente. Suelen haber varias inconsistencias en los archivos (sobre todo en la vida real) y eso es parte del trabajo que queremos que realicen
