### ISSUE TITLE
Entregable

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#121]
Hola! ¿Puedo entregar las matrices (Archivos excel) creadas y el código que justamente las crea comentado? De esta manera para que no se creen las matrices cada vez que se ejecuta el programa para hacer las consultas. Por lo que mi entregable serían las matrices y la capacidad de mi código de responder las consultas mediante la terminal, con además obviamente el informe. 

Muchas gracias.

**Comment by TomasKetterer** [comment]
Hola, debemos probar su cargador de datos, por lo que tienes que entregar el archivo php que filtra los datos. Este creará posteriormente las matrices y así podremos hacer las consultas para corregir esa parte. Por lo tanto, no, no se puede entregar solo las matrices y el código que corre las consultas. Intenta hacer que un módulo de tu código cargue las matrices una vez y que las consultas se realicen en otro/s módulo/s para que no se tenga que realizar el proceso de cargar matrices dos veces
