### ISSUE TITLE
Entrega Código

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#122]
Hola; entiendo que debo entregar mi código en la carpeta con mi nombre pero no entiendo a cual subcarpeta. Por ahora mi filezilla se ve asi 
<img width="1244" alt="filezila duda" src="https://github.com/user-attachments/assets/0904c842-d698-4d81-9b36-e320aac083d2">

**Comment by ypne** [comment]
Eso debes indicarlo tu en el informe

**Comment by josefa00** [comment]
Osea puedo subirlo a cualquier carpeta? Del mismo modo la dirección de mi carpeta es /Users/josefamontero/Library/CloudStorage/OneDrive-Personal/Ingeniería\ 2024/2-2024/Bases\ de\ Datos/P0 y me sale que no existe será un problema porque esta en OneDrive?

**Comment by vicenterodas** [comment]
También tengo una duda similar.
No entiendo que ruta al archivo colocar en el código de forma que este funcione correctamente para la corrección.

**Comment by anticarasosman** [comment]
Hola disculpa yo tambien tengo duda de como se debe entregar la tarea ¿podria pedir por una explicacion general?

**Comment by MartyMolina** [comment]
Al inicio del enunciado se menciona que el informe debe entregarse a través de Canvas, junto con el código y los datos en el servidor. Debes explicar cómo se ejecuta toda tu tarea y qué resultados se obtienen al correrla. Además, debe ser posible ver de alguna manera los resultados al ejecutar tu código, lo que debes explicar.
