### ISSUE TITLE
Duda respecto a entrega atrasada

### ISSUE THREAD

**Issue by CristianGarcia2310** [IIC2413/Syllabus-2024-2#123]
Tengo la duda de como funciona 

1) ¿El buzon de canvas quedara cerrado hoy a las 23:59, o recibira respuestas los siguientes 3 dias?

2) Si entregara un archivo hoy, pero subiera una nueva version mañana ¿cual tomarian?

**Comment by MartyMolina** [comment]
Se dejará el buzón abierto 3 días más, según lo mencionado en el programa: en caso de atraso en la entrega de las etapas, la nota disminuirá en 1 punto por cada día de retraso, hasta un máximo de 3 días. Posterior a esa fecha, se evaluará con una nota de 1.0.

Para esta tarea, podrán enviarla hoy y luego hacer una entrega atrasada si lo desean, pero se enviará un formulario que deberán llenar aquellos que entreguen con retraso

**Comment by yonieeh** [comment]
cuando dicen que se disminuira en 1 punto por cada dia de atraso, eso se aplica sobre la nota maxima obtenible o sobre la nota de la evaluacion?

**Comment by MartyMolina** [comment]
Esto se refiere a la nota de la evaluación. Por ejemplo, si se entrega con un día de atraso y la nota obtenida es un 5, esta bajará a 4.
