### ISSUE TITLE
Entidad relacionada consigo misma

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#125]
Hola, quería hacer una pregunta relacionada a la materia del modelo Entidad-Relación. ¿Puede una variable estar relacionada consigo misma? Por ejemplo, si tengo entidad Gato, y se que un gato puede jugar (relación) con un gato, puedo unir el rectángulo de gato con un rombo jugar y luego de vuelta a gato?. En este tipo de relaciones hay que poner algún cuidado especial con las llaves o la cardinalidad?

Muchas gracias

**Comment by benitopalaciosm** [comment]
Hola! Sí se puede. Acá te dejo un ejemplo de cómo se podría modelar:

<img src="https://github.com/user-attachments/assets/7a07d6fb-d414-48ca-85e8-68a0e3db8098" width=50% height=50%>

En cuanto a tu segunda pregunta, las llaves y la cardinalidad se manejan de la misma forma que en otros modelos de Entidad-Relación. Sin embargo, te sugiero que, a menos que estés seguro de que es estrictamente la misma entidad, consideres la opción de separarlas en dos entidades diferentes para mayor claridad en el modelo.

Saludos

**Comment by benitopalaciosm** [comment]
Hola! Sí se puede. Acá te dejo un ejemplo de cómo se podría modelar:

<img src="https://github.com/user-attachments/assets/12d970c8-d165-4654-900e-293c99861964" width=50% height=50%>

En cuanto a tu segunda pregunta, las llaves y la cardinalidad se manejan de la misma forma que en otros modelos de Entidad-Relación. Sin embargo, te sugiero que, a menos que estés seguro de que es estrictamente la misma entidad, consideres la opción de separarlas en dos entidades diferentes para mayor claridad en el modelo.
