### ISSUE TITLE
Notación vista en clases y notación CHEN solicitada en la tarea 2

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2413/Syllabus-2024-2#127]
Hola.

En la tarea solicitan usar la notación CHEN para hacer el diagrama E/R. De acuerdo a lo que pude investigar [acerca de esta notación](https://vertabelo.com/blog/chen-erd-notation/), esta difiere en principalmente en la forma que se indica la cardinalidad, en relación a la vista en clases.

EJEMPLO CLASES:
Relación 1 a 0.n

![imagen](https://github.com/user-attachments/assets/147bab6c-7eed-4813-9c90-1cc43f137969)

EJEMPLO CHEN:
Relación 1 a 0.n
![imagen](https://github.com/user-attachments/assets/68dac684-0c2a-4337-9f52-82713bd0dcb0)

Difiere principalmente a que en clases especificamos esta relación con flechas, pero según la guía de la página no se usan. Pregunto esto, porque no se si la notación vista en clases es una distinta o alguna equivalente a la de CHEN. También aprovecho a preguntar, que a futuro en las pruebas escritas que tengamos en este curso, deberemos usar la notación que acostumbramos a ver en clases o la de CHEN para diagramar relaciones?

Gracias =D

**Comment by noamsito** [comment]
Holaa, en efecto hay distintas notaciones para la cardinalidad entre relaciones, pero deben usar la vista en clases y ayudantía. Lo mismo aplica para el resto de evaluaciones (cardinalidad con las flechas).

**Comment by MathiasPrett** [comment]
Buenisima. Muchas gracias 😀
