### ISSUE TITLE
Nuevas posibles entidades y atributos

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#128]
Al leer el enunciado de la entrega 1 se notan entidades que antes no existian, como es el caso de cuando se nombra "carreras", y luego se menciona que estas carreras tienen nombres y cursos, pero si se compara con los archivos que se nos entregaban en la entrega pasada ("Archivo1.csv" y "Archivo2.csv") no existen nombres de carreras que estudian los estudiantes. Entonces no me queda claro si realmente debo considerar la carrera o la ignoro ya que no esta en la base de datos que de la entrega 0?

**Comment by VAMarques** [comment]
Si te acuerdas, en la entrega 0 misma se especifica que se pueden cambiar las "necesidades de la empresa". En este sentido, entiendo que no necesariamente debes considerar la entrega 1 como continuacion directa de la entrega 0, piensa tambien que en la entrega 1 no tenemos que trabajar con archivos. (No soy ayudante)

**Comment by ypne** [comment]
Cada entrega tiene un aumento de los requerimientos. El objetivo de la parte 0 era que practicaran PHP y para eso se solicitó que crearan un cargador e hicieran unas consultas simples.
Esta etapa ya entra en temas reales de Bases de datos y se solicita que modelen un problema en la forma de Entidad relación y desde ahí crear el esquema y lo demás. El problema es básicamente el mismo pero cambian las reglas de negocio y hay más atributos. Tal como dice @VAMarques en esta entrega no hay archivos de datos.
