### ISSUE TITLE
Etapa 1 Entidad personas y sub entidades

### ISSUE THREAD

**Issue by Tichi1010** [IIC2413/Syllabus-2024-2#129]
Hola buenas, en el enunciado dice que una persona puede ser concurrentemente estudiante, administrativo o académico. Mi prepunta es ¿Hay alguna foma de representar eso en el modelo E/R?¡tenemos que representar que pueden ser concurrentes esas entidades?

**Comment by ypne** [comment]
Si, fue visto en clases
