### ISSUE TITLE
Uso de Enum

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#13]
Hola, buenas tardes:
Para la tarea, ¿se pueden usar enums?
Gracias por su atención.

**Comment by TomasKetterer** [comment]
Hola! Si, se puede usar enums para los atributos que tengan una cantidad fija y conocida de valores. Algunos ejemplos serían diurno y vespertino o calificación (SO, EX, SU, I, etc).

Mientras el resultado entregado sea en el formato solicitado y lo pongas en tu informe está todo bien :)
