### ISSUE TITLE
Dudas sobre enunciado: Genero de academicos, Planes y carreras.

### ISSUE THREAD

**Issue by VAMarques** [IIC2413/Syllabus-2024-2#131]
Hola.

1. En el enunciado de la E1, sale "**_... Jerarquıa academica (ASISTENTE, ASOCIADO, INSTRUCTOR, TITULAR), ambos en su denotación masculina y femenina, combinado con..._**" Por lo cual intuyo que debemos tomar en cuenta el genero de los academicos, sin embargo, esto me llega a parecer contraintuitivo. ¿Significa esto que ademas de ASISTENTE esta ASISTENTA? mas aun ¿Deberiamos añadir TITULARA? (_esta es una pregunta retorica, solo estoy explicando el porque esto me parece raro_) considerando que TITULAR ya de por si es una palabra neutral. Debido a esto me pregunto si no tiene mas sentido que el genero sea algo especifico de la persona (O si debemos cumplir el enunciado 100% al pie de la letra)
2. En la seccion 2, estan las carreras y planes, sin embargo, veo poco exacto que es una carrera y que es un plan, Pues los planes tienen un codigo, pero parece que las carreras solo tienen un nombre, en ese caso no se puede identificar a una carrera mas que por su propio nombre ¿Es esto correcto? Supondre tambien que los planes de estudio (Segundo punto de 2.) son lo mismo que los curriculum (Tercer punto de 2.)

En general, tambien quisiera saber si, pensando en que el enunciado es poco especifico, podemos tomar ciertas consideraciones propias, claro eso si, justificadas en el mismo documento. Por ejemplo, para que las carreras tambien tengan un codigo, y no solo sus planes.

**Comment by ypne** [comment]
1.- Las palabras deben existir en el idioma castellano
2.- Un plan pertenece a una sola carrera, una carrera puede tener varios planes, el código del plan determina la carrera
En general: Ustedes deben crear el modelo con las entidades y relaciones que estimen convenientes para modelar el problema. Como vimos en clase, puede haber más de un modelo para el mismo problema (ver clase 3 pg 26). Ustedes deben tomar decisiones con base en los requerimientos y si llegan a la conclusión de que deben crear surrogate keys, lo que según lo visto en clase normalmente es una buena práctica, lo hacen.
