### ISSUE TITLE
Diagramas 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#132]
Hola; en el enunciado se pide la construcción de un modelo E/R sin embargo en el punto 7 se pide la construcción de un esquema relacional. Este también debe ir en el pdf?

**Comment by noamsito** [comment]
Hola, sí. En el enunciado en la sección de "temas administrativos" se menciona todo lo que tiene que contener el informe en PDF.

De todas formas te adjunto dicho fragmento: 
<img width="755" alt="Screenshot 2024-09-09 at 4 11 10 PM" src="https://github.com/user-attachments/assets/5f3a8017-fd8d-4cff-ab29-64c00ee41716">
