### ISSUE TITLE
administrativo

### ISSUE THREAD

**Issue by emivenezian** [IIC2413/Syllabus-2024-2#135]
hola! como estan? me queda una duda de la clasificacion de administrativo, para la entrega pasada se dijo q si tenia cargo era administrativo, pero ahora dice q administrativos y profesores tienen contrato. Entonces esta bien decir que si tiene contrato, entonces es adminsitrativo? (ambas direcciones)

**Comment by ypne** [comment]
No, tanto los profesores como administrativos
