### ISSUE TITLE
Duda sobre nulos

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#14]
Ya que algunas clasificaciones de contenidos en los archivos admiten valores nulos y otros no (En donde se rellena con algo para denotar que es inválido, 0 en mi caso)¿Puedo simplemente rellenar con 0's todas los apartados en los que no hay información?.

Muchas gracias!

**Comment by noamsito** [comment]
No puedes rellenar **todos** los datos vacíos con 0s, ya que en algunos casos se admiten valores nulos, lo cual no incumple con las restricciones planteadas. Además, los valores nulos pueden tener diferentes interpretaciones (descritas en el enunciado).

Por ejemplo, las notas pueden ir de 1.0 a 7.0, sin embargo, si dicho valor es nulo eso quiere decir que el curso aún no termina, o está convalidado o está eximido. Por lo tanto, si rellenas con 0s en dicho dato, se tendrá una interpretación diferente a la intencionada.

**Comment by jisalasc** [comment]
En ese caso se rellena con "x"? y si por ejemplo un valor no cumple un formato, por ejemplo en nota un string?

**Comment by noamsito** [comment]
Exacto, en el caso de que no se admitan nulos y venga vacío el dato, se debe rellenar con una X, como se menciona en el enunciado. 

Respondiendo a lo segundo que mencionas, eso ya es parte de su desarrollo para esta entrega. En el enunciado se menciona que deben de realizar la limpieza sobre aquellos datos que no cumplan con los formatos correctos, por lo tanto en caso de que sea posible los deben de corregir al formato correspondiente. A continuación te dejo la parte del enunciado donde se menciona esto: 

>"Realice la detección de los datos que no cumplan con los formatos correctos, indicados más adelante y si es posible los corrija, de lo contrario lo descarte."

También hay 3 ayudas para la limpieza de datos (al final de las reglas del negocio).
