### ISSUE TITLE
Contraseña servidor

### ISSUE THREAD

**Issue by waknaudt** [IIC2413/Syllabus-2024-2#140]
Hola, quiero descargar los archivos de Bananer que subi para la recorrecion, pero al parecer las contraseñas fueron cambiadas. Como puedo saber la nueva contraseña?

**Comment by kovaxis** [comment]
Hola! Las cuentas estaban desactivadas mientras se corregia, pero ahora están disponibles en modo read-only. Disculpa la demora. Saludos!
