### ISSUE TITLE
Duda entidades o atributos

### ISSUE THREAD

**Issue by AmarantaB** [IIC2413/Syllabus-2024-2#142]
Hola, tenia una duda en cuanto a creación de ciertas entidades. Si tengo una entidad hija, que aplica para dos clases padres distintas, sería correcto conectar los dos padres a la hija y poner desde cada padre un tipo de flecha distinta para clarificar que tienen cardinalidades distintas? o sería mejor derechamente crear dos clases hijas, una para cada clase padre? Me parece que esta última opción puede caer en redundancia cuando una persona puede pertenecer a las dos clases padre, no obstante no recuerdo un ejemplo similar en clase por lo que consulto a ustedes su recomendación. 

Por otro lado quisiera consultar sobre cómo se nos recomendaría tratar restricciones de tipo  "booleanas". Por ejemplo en jerarquía existen varias clasificaciones que definen la jerarquía que se entrega, el género, comisión superior o no, etcétera. En ese caso cómo nos recomendaría modelar aquello? ya que tal como decía una Issue anterior, existen restricciones que pueden aplicarse o no, como sucede con género, por lo que no me convenzo de si jerarquía ser una entidad con posibles atributos nulos o solo un atributo de academico. También caigo en la duda de que jerarquía debería entregar un valor, por ejemplo "titular docente comisión Superior", pero el modelamiento como entidad con atributos booleanos nos entregaría valores de si, no y no aplica en caso de género, mas no el nombre de la jerarquía como tal. Agradecería pudieran guiarme un poco en esta área, muchas gracias desde ya por su tiempo.

**Comment by ypne** [comment]
1.- Las entidades puedes ser puperclase o sub clase, no existe la sub clase que pertenezca a dos superclases

2.- Jerarquía no es booleana
