### ISSUE TITLE
Crear Entidad

### ISSUE THREAD

**Issue by vicenterodas** [IIC2413/Syllabus-2024-2#145]
Hola, tengo ua duda.

Existe la entidad curso la cual tiene sus atributos ( como nombre, sigla, carácter) pero esta adquiere otros atributos cuando un estudiante lo cursa (como nota, calificación). Es posible crear estos como dos entidades distintas. Quizás cursos cursados puede heredar de cursos. 

Gracias

**Comment by ypne** [comment]
si
