### ISSUE TITLE
Relaciones Binarias 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#146]
Hola, tengo una duda con respecto a las notaciones ya que la mayoría de nuestro diagrama E/R son de n a n sin embargo como tienen relaciones (frases) entre medio se lee distinto ; por ejemplo n pedidos tienen n evaluaciones y no al contrario y en caso de poner una flecha indicando la dirección la relación deja de ser de n a n

**Comment by ypne** [comment]
" n pedidos tienen n evaluaciones " pedidos??

**Comment by josefa00** [comment]
Es para ilustrar el concepto a través de la pauta del semestre pasado (subida en el sylllabus). Pero por ejemplo se podría decir que un profesores dicta n cursos pero no al revés. Por eso mi pregunta va a si es que hay que especificar el orden en el informe o a través de las direcciones de las flechas

**Comment by ypne** [comment]
del enunciado "Construya y describa un modelo E/R con notación CHEN"

con respecto a la cardinalidad depende de las relaciones que tienen:
Un curso del plan (o malla) no tiene asociado un profesor per se. Solo cuando ese curso se dicta tiene se le asocia un profesor.
Por el momento un curso puede ser dictado **en un semestre** por un solo profesor (esto va a cambiar en la próxima entrega) y un profesor puede dictar varios cursos en el mismo semestre.
