### ISSUE TITLE
Esquema relacional 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#147]
Hola entiendo que el esquema relacional es de la forma en que se explica en la ayudantía (foto 1) sin embargo como en esta entrega no se programa no se si debemos hacerlo como esta en la pauta del semestre pasado (foto 2) 
![image](https://github.com/user-attachments/assets/b7ddce11-7bb9-4b29-8ce2-8a8907fed16c)
![image](https://github.com/user-attachments/assets/b312d320-e361-41d5-bd21-fa4161af5e16)

**Comment by ypne** [comment]
Ese no es el enunciado del proyecto

**Comment by josefa00** [comment]
si se es un ejemplo del semestre pasado solo para ilustrar mi pregunta

**Comment by josefa00** [comment]
El esquema del informe debe seguir el formato de la foto 1 o foto 2?

**Comment by MartyMolina** [comment]
El esquema relacional que tiene que hacer es de la manera que se enseñó en clases, es el correspondiente a la foto 1
