### ISSUE TITLE
Duda con respecto a atributos de académicos 

### ISSUE THREAD

**Issue by Durmye** [IIC2413/Syllabus-2024-2#148]
En el enunciado de la P1, (reglas de negocio > De las personas y sus datos > sexto punto). Se detalla lo siguiente: 

- Los académicos, llamados indistintamente profesores, docentes o investigadores, son personas que dictan cursos o investigan, tienen grado académico (LICENCIATURA, MAGISTER o DOCTOR), Jerarquía académica (ASISTENTE, ASOCIADO, INSTRUCTOR, TITULAR), ambos en su denotación masculina y femenina, combinado con (DOCENTE, o REGULAR). Existen profesores SIN JERARQUIZAR y otros que están en COMISION SUPERIOR. El prefijo ”Comisión Superior” en la jerarquía significa que está siendo analizado en esa instancia institucional, mientras que el prefijo ”Profesor” es una denominación deprecada, por lo que vale la jerarquía sin el prefijo.

De acuerdo a lo anterior entiendo lo siguiente: 
1. Hay un "atributo" llamado **grado académico** el cual puede tomar los valores: 
    -  Licenciatura
    - Magister
    - Doctor 
2. Hay un "atributo" llamado **jerarquía academica** el cual puede tomar los valores: 
    - Asistente
    - Asociado
    - Instructor
    - Titular  
3. Hay un tercer "atributo" el cual no tiene nombre detallado que puede tomar los siguientes valores: 
    - Docente 
    - Regular  
4. Existe un cuarto "atributo" donde se mezcla el 2do y 3er atributo. Dando origen a las siguientes combinaciones: 
    - Docente Asistente 
    - Docente Asociado
    - Docente Instructor
    - Docente Titular
    - Regular Asistente
    - Regular Asociado
    - Regular Instructor
    - Regular Titular   

5. El 4to atributo puede tomar, además, los valores: 
    - Sin jerarquizar 
    - Comisión superior

6. Finalmente el 3er atributo puede tomar el valor:       
    -  Profesor

Mi "issue" en este caso es la aclaración de esta parte del enunciado y si es que lo detallado arriba corresponde efectivamente a lo que se busca. En especifico agradecería si pudieran explicar: 

- Cuando se habla de "prefijo", en mi interpretación, el 3er atributo vendría tomando este rol, de ahí que en el 4to punto se de lugar a esas ocho combinaciones. Sin embargo, en el punto 6 interpreto que el 3er "atributo" puede tomar, además, el valor de profesor. A partir de esto surge la duda ¿Cuál seria el valor del 4to atributo (asumiendo que efectivamente debe existir un 4to atributo)?, es decir, ¿surgen otras 4 combinaciones nuevas? o bien, ¿el cuarto atributo puede quedar simplemente como copia del 2do? esto debido a que en el enunciado se menciona que: "vale la jerarquía sin prefijo". 

Perdón por el mucho texto y ¡gracias!

**Comment by ypne** [comment]
1.- Existen 2 atributos
- Grado académico
- Jerarquía
2.- Grado académico puede tomar un valor entre (LICENCIATURA, MAGISTER o DOCTOR)
3.- Jerarquía es una de las siguientes 3 opciones
     3.1.- La combinación de (un valor entre (ASISTENTE, ASOCIADO, INSTRUCTOR, TITULAR) y un valor entre (DOCENTE, REGULAR) ) XOR (SIN JERARQUIZAR)
     3.2.- COMISION SUPERIOR + <cualquier jerarquía de 3.1>
     3.3.- PROFESOR + <cualquier jerarquía de 3.1> que es equivalente a <jerarquía de 3.1>
