### ISSUE TITLE
Duda de llaves para entidades débiles

### ISSUE THREAD

**Issue by jisalasc** [IIC2413/Syllabus-2024-2#149]
Si poseo una entidad C débil la cual depende de una subentidad B que hereda de A, como esta no puede tener llave que no sea parcial, puede la llave de la entidad C ser la parcial de la subclase B? o debo heredar la llave completa (parcial + llave clase madre)

**Comment by IgnaciaDeGoyeneche** [comment]
Hola! Debe heredar la llave completa, ya que B sería la llave foránea y A la llave primaria en su relación de dependencia. En el caso de C, esta depende de B, por lo cual por transitividad dependerá de A.
