### ISSUE TITLE
Duda en definición de claves primarias

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2413/Syllabus-2024-2#150]
Hola, tengo una duda respecto del uso de llaves primarias ¿Es posible definir claves primarias en una entidad hija que hereda de otra entidad? 

Por ejemplo, considerando el caso de una entidad Persona con las claves primarias RUT y DV, y una entidad Alumno que hereda de Persona, ¿se podría definir una clave primaria adicional en Alumno, subrayando un atributo propio de esta entidad, como el Número de Alumno?

**Comment by VicenteSanMartin** [comment]
Hola! Te recomiendo revisar la issue #126
