### ISSUE TITLE
Restricciones de integridad y formato de atributos

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2413/Syllabus-2024-2#151]
Hola, ¿Es necesario añadir restricciones de integridad y/o formatos de los atributos que agregamos a nuestro diagrama? Por ejemplo, en el caso de la cohorte, periodo de la asignatura, último logro y última carga tienen que tener el formato <año>-<semestre>, donde año debe ser un numero natural y semestre un numero del 1 al 3.

**Comment by ypne** [comment]
Eso es el Dominio del atributo
