### ISSUE TITLE
Prerequisito y curso

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#152]
En el enunciado sale: Los cursos tienen prerequisitos los que pueden ser uno o m´as cursos previos o un ciclo. 
Lo cual no me hace sentido que todos los cursos deban tener al menos un prerequisito. En el enunciado querrá decir puede tener uno o más prerequisitos ?

**Comment by ypne** [comment]
Dice los cursos, no todos los cursos. En todo caso, si quieres modelar que todos tengan, agrega el requisito INGRESO
