### ISSUE TITLE
Herencia y llaves

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#155]
Hola no me quedaron claras unas cosas en la issue 126:
1. Una entidad hija puede tener su propia llave primaria o secundaria ?
2. También no me queda claro si estudiante debe heredar de personas o ser una entidad aparte?

Muchas gracias de antemano

**Comment by ypne** [comment]
1.- Si puede tener una PK, que es una llave secundaria?
2.- Cpomo tu lo modeles,m ambos son válidos
