### ISSUE TITLE
Duda de entidades debiles, luego de leer el issue #154

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#158]
Por lo visto en ayudant{ias y clases si una entidad herda las llaves de su entidad padre (están conectadas por un isA) entonces no sería una entidad debil, al menos en la ayudantía 3 Estudiante, Profesor y Ayudante, heredan todo de la entidad Persona y de todas formas no se crean como entidades debiles en el modelo E/r ni en el esquema, lo mismo pasa en el ejemplo de clases de bebidas. Entonces quisiera saber que no entiedo, porque según como entiendo la respuesta del issue #154 si deberían ser debiles.

**Comment by ypne** [comment]
No se mareen con eso. Si la única forma de llegar a una entidad es a través de otra, ergo es débil.
