### ISSUE TITLE
Matrices a implementar

### ISSUE THREAD

**Issue by javirossi** [IIC2413/Syllabus-2024-2#16]
Hola, me queda una duda con la matriz Persona: ¿Debo incluir datos de ambos archivos? Si es así, ¿El atributo Teléfono lo debo dejar vacío para las personas del archivo 1? Considerando que no se encuentra en la instancia.

**Comment by Mateodlcc** [comment]
Si, debes incluír los datos de las personas. Es un supuesto válido no incluir el teléfono para las personas del archivo 1 dado la falta del dato para el primer archivo.
