### ISSUE TITLE
Solicitud de pauta de Guía recopilatoria y Controles 2023-2 y 2023-1

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#165]
Hola!
 Espero se encuentren bien. Quería preguntar si pueden subir la pauta de la guía recopilatoria que esta subida y de los controles de los años 2023-2 y 2023-1 para poder complementar el estudio.
 Revisé los repositorios de ambos semestres, pero no encontré pautas que pudiese consultar 😔.

Gracias de antemano!

**Comment by ypne** [comment]
Hola
2023-2 está publicado en canvas
2023-1 el link estaba malo (decía 22023-1) corregido
Guía recopilatoria no tiene pauta de corrección.
