### ISSUE TITLE
Dudas enunciado E2

### ISSUE THREAD

**Issue by AmarantaB** [IIC2413/Syllabus-2024-2#168]
Hola, con mi grupo nos surgieron varias dudas al leer el enunciado 2 y tratar de modelar el modelo E/R, las dejo a continuación por si pudieran aclarárnoslas. Desde ya muchas gracias

En la sección 2 sale "los departamentos pertenecen a una facultad, vicerrectoría o programa, tienen código y nombre". ¿A que se refiere con programa? Me sugirieron que podía ser sinonimo de plan, pero no nos resulta lógico que un depto pertenezca a un plan, si es más al reves, un depto está a cargo de cursos que pueden ser un plan. 

En la sección 3 se habla de un atributo estamento, pero este podría tener varios valores (ej administrativo y academico a la vez). ¿Como sugeririan modelar ese atributo entonces si puede tener varios valores?¿O la idea es modelarlo por codigo de definir estamento como las entidades a las que pertenece un rut?

En la sección 6 sale que una oferta academica tiene cupo e inscritos, ¿cual es el dominio de esas caracteristicas? i.e a que se refieren cada una

Esas son todas, nuevamente muchas gracias desde ya:)

**Comment by ypne** [comment]
P:que se refiere con programa? 
R: no 
P:  atributo estamento
R: el estamento ahora se usa  para definir si es administrativo o profesor en un principio
P; cupo e inscritos:
R: cupo = vacantes inscritos: numero de estudiantes que tomaron el ramo al momento de la query
