### ISSUE TITLE
Duda Proyecto E2

### ISSUE THREAD

**Issue by anemugarza** [IIC2413/Syllabus-2024-2#170]
Buenas! Tengo la duda de si las tablas que hemos definido para la parte 2 de la tarea, es decir, siguiendo las reglas del enunciado, son las que tenemos que crear en local y en el servidor o si podemos modificarlas para que coincidan con los datos, es decir, añadir atributos, crear alguna tabla más que con el enunciado no teníamos...

Es que también hay tablas que tenemos definidas en el esquema, pero que luego mirando los datos no son necesarias crear porque no hay datos con los que rellenarlas

**Comment by Mateodlcc** [comment]
Hola! Es aceptable que realicen modificaciones a las tablas mientras se mantenga la esencia del proyecto. Lo ideal es que,  en caso de optar por esta opción, lo mencionen respectivamente en el informe.
