### ISSUE TITLE
Uso de agregación en modelo E/R

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#171]
Hola!
 Pregunta cortita. ¿Cuándo es conveniente usar agregación en un modelo E/R? 
 En clase me quedé con la idea de que es una especie de "arreglo" para poder unir 2 relaciones, pero no entiendo bien cuando sería conveniente realizarlo por sobre una relación de 3 entidades, por ejemplo.

Quedo atento!

**Comment by ypne** [comment]
En ese caso

**Comment by coniverav** [comment]
Misma pregunta

**Comment by coniverav** [comment]
sigo con la duda

**Comment by SSParzival** [comment]
Sigo con la interrogante.

**Comment by j0secr** [comment]
> En ese caso

???????????
