### ISSUE TITLE
Duda P2

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#173]
En el enunciado se dicen "La máxima entidad de la universidad es la Rectoría, de ahi se derivan las Vicerrectorias, las
Facultades y los Departamentos. Cada unidad que imparte cursos es un departamento (incluso
la Vicerrectoría Academica" 

No se explica que es una vicerrectora académica entonces asumimos que es un tipo de vicerrectora?;  y además esto quiere decir que si la Rectoria o una Facultad imparte cursos también sería un departamento

**Comment by ypne** [comment]
Los cursos impartidos por departamentos, independiente de la estructura organizacional. En particular los departamentos pueden ser: La Facultad, El instituto, la Vicerectoría académia, el Programa de idiomas, etc.

**Comment by VANCOUVERMATU11** [comment]
Si es que un departamento puede ser una facultad, entonces no me hace sentido que el enunciado diga: "(...) los departamentos pertenecen a una facultad (...)". ¿Eso quiere decir que un departamento puede estar contenido por otro departamento? (de otro tipo, no necesariamente el mismo como programa y facultad)

Saludos

**Comment by ypne** [comment]
es una estructura matricial, toda unidad que dicta cursos es un departamento. Una facultad "A" puede tener 2 departamentos C y B, pero si la facultad dicta cursos por si misma, se codifica como un departamento en la base.
