### ISSUE TITLE
Nivel de los cursos

### ISSUE THREAD

**Issue by Cdelalastra** [IIC2413/Syllabus-2024-2#175]
El enunciado dice que los cursos tienen un nivel, que corresponde al semestre que pertenecen dentro de un plan de estudio o de un ciclo. En este caso los niveles son B,L,1,2,...,10. No entiendo si con B y L se refieren a que el ramo se puede cursar en cualquier semestre entre 1 y 6 para B y de 7 a 10 para L, o si el hecho de que pertenezca a un semestre en específico lo clasifica como B o L. Esta pregunta me surge porque si B y L son consideradas como un dato que podría tomar el atributo, refiriéndose a que un ramo puede pertenecer a un rango de semestres, entonces pensando en el esquema relacional, para una misma columna tendría distintos tipos de datos (strings y int).

**Comment by ypne** [comment]
Los cursos no tienen nivel B o L

**Comment by abraxvs** [comment]
![image](https://github.com/user-attachments/assets/d7dca4f1-88b1-4553-a18f-9a4c88c4f785)

Hola, quería saber si me guio por la respuesta de esta issue, o por el enunciado, que dice que sí tienen nivel B y L
