### ISSUE TITLE
Tomar el Diagrama "Pauta" como nuestro

### ISSUE THREAD

**Issue by VANCOUVERMATU11** [IIC2413/Syllabus-2024-2#176]
Hola! A la espera de nuestra nota respecto a la E1 queremos empezar a avanzar en la E2 pero es difícil sin saber si nuestro diagrama/esquema están correcto. Por lo tanto, ¿podríamos simplemente comenzar "todo de nuevo" copiando el diagrama provisto por ustedes?

Es decir, ocupar el diagrama provisto por ustedes para saber que estamos bien y no arrastrar más errores. No está de más mencionar que no estamos tan seguro de el puntaje que obtengamos en nuestra entrega 1, por lo tanto seguir basándonos en nuestro diagrama podría ser un desperdicio. 

Saludos

**Comment by ypne** [comment]
El modelo E/R de la etapa 2 es más amplio que el de la etapa 1 por lo que para comenzar pueden usar la pauta entregada y ampliarla.

**Comment by elneitans** [comment]
Hola Profesor, una consulta respecto a esto: se puede asumir que este diagrama es correcto respecto a todas las instrucciones de la E1?

**Comment by MathiasPrett** [comment]
Aprovechando el hilo, tengo una duda del diagrama/esquema que subieron como pauta. La entidad Curso, tiene de atributo su carácter. Pero el carácter de un curso está dado por el plan que compone. Lo mismo pasa con ciclo y nivel. Eso quiere decir que existirían varios registros para un mismo curso, que puede ser de carácter mínimo y establecida para el nivel 4 de una carrera x, pero también puede ser OFG para otro plan, de otra carrera y.

Conviene que la tabla cursos esté estructurada de esa manera en la bdd?

**Comment by ypne** [comment]
La malla está en el archivo de datos, todos los cursos individualizados son mínimos
