### ISSUE TITLE
Dudas proyecto E2 acerca de las carreras y los programas

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2413/Syllabus-2024-2#177]
Hola, leyendo el enunciado de la entrega 2 me surgieron algunas dudas con respecto a las reglas de negocio.

Con respecto al inciso 1. de las carreras y planes:
En el enunciado aparece que cada plan pertenece a una facultad y que la carrera puede tener varios planes al mismo tiempo, ¿podemos asumir que cada carrera va a pertenecer necesariamente a una sola facultad?  

Con respecto al inciso 2. de la estructura organizacional:
Aparece que los departamentos pertenecen a una facultad, vicerrectoría o **"programa"**. No me queda claro a que se refiere con este último elemento ya que en las reglas de negocio no se menciona nada más de "programa".

Espero se entiendan mis dudas, gracias de antemano.

**Comment by ypne** [comment]
En el enunciado aparece que cada plan pertenece a una facultad y que la carrera puede tener varios planes al mismo tiempo, ¿podemos asumir que cada carrera va a pertenecer necesariamente a una sola facultad?
R: SI

Con respecto al inciso 2. de la estructura organizacional:
Aparece que los departamentos pertenecen a una facultad, vicerrectoría o "programa". No me queda claro a que se refiere con este último elemento ya que en las reglas de negocio no se menciona nada más de "programa".
R: en los datos entregados no existen programas, puedes obviarlo
