### ISSUE TITLE
Duda acerca Planes, Carrera, Número de alumno

### ISSUE THREAD

**Issue by Jerrazuriz** [IIC2413/Syllabus-2024-2#178]
Se menciona que la carrera puede tener varios planes en el tiempo o vigentes en paralelo. Luego se menciona que se genera un número de estudiante cada vez que una persona ingresa a estudiar un plan. Estamos confundidos debido a que al haber varios planes dentro de una carrera, una persona que está estudiando una misma carrera debe poder tener varios números de alumnos simultáneamente, lo que llevado a la realidad no tiene mucho sentido. ¿No debería ser que un número de estudiante se genere por carrera y no por planes?

**Comment by ypne** [comment]
Hola, la interpretación es diferente. La entidad principal es Plan no carrera ya que una carrera puede tener varios planes, un alumno estudia en un plan pero no puede estar estudiando dos planes de la misma carrera, lo que si puede hacer es que dentro de la misma carrera se cambie de plan, eso no genera cambio de numero de estudiante.
Lo que si genera un segundo numero de estudiante es que el estudiante esté simultáneamente haciendo 2 carreras y por lo tanto dos planes.
