### ISSUE TITLE
Duda sobre aplicación cargadora de datos

### ISSUE THREAD

**Issue by Paulaverastegui** [IIC2413/Syllabus-2024-2#179]
Hola!
No me queda claro del enunciado si para cargar los datos se debe hacer uso de PHP, o por comando de línea (dice que se debe hacer uso de PHP y luego dice que puede ser por comando de linea). Además para la limpieza de datos, esta debe ser por PHP? o se puede hacer uso de python?

**Comment by ypne** [comment]
Se debe crear una aplicación cargadora de datos en PHP+SQL. Lo que se indica es que la aplicación puede ser  solo en PHP no es necesario que sea Web, por lo tanto se ejecuta via CLI.

Para la limpieza de los datos con problemas de formato se puede usar cualquier herramienta (solo sobre esos datos) incluso manualmente. Los datos de entrada NO pueden manipularse.

**Comment by Paulaverastegui** [comment]
Y se deben trabajar como .xslx o se pueden guardar en csv y abrirlos desde ahí?

**Comment by ypne** [comment]
se puede exportar a CSV cada tab completo

**Comment by Paulaverastegui** [comment]
Perfecto, pero me sigue sin quedar claro que formato es correcto para cargar los datos a la base de datos. Puedo abrirlos con php en un archivo y separar en archivos que sean válidos y otros que no, para luego cargar la base de datos con los archivos válidos? Y los invalidos arreglarlos manualmente para luego agregarlos a la base de datos?
