### ISSUE TITLE
Duda matriz Estudiante

### ISSUE THREAD

**Issue by javirossi** [IIC2413/Syllabus-2024-2#18]
En la matriz estudiante, si un estudiante tiene más de un número de alumno ¿debo considerar ambos en la matriz?

**Comment by TomasKetterer** [comment]
Hola! Si, si un estudiante cuenta con más de un número de alumno, se debe considerar en la matriz cada número de alumno como un registro de ese estudiante. Es decir, en la matriz quedarán estudiantes con el mismo nombre pero con distintos números de alumno.

**Comment by ypne** [comment]
Por ejemplo, un estudiante que sigue dos programas en forma concurrente tiene 2 números de estudiante o, un estudiante que se retiró de un programa y después ingresa al mismo u otro también aparecerá con 2 números de estudiante diferentes.
