### ISSUE TITLE
Problema para ingresar al server

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#180]
Holaa. Tengo un problema para ingresar al server: sigo las instrucciones de la Ayundatía 6 pero me indica que la contraseña (grupo<num_grupo>) es incorrecta. Alguien sabe cómo resolverlo?

**Comment by elneitans** [comment]
También otro problema de este estilo, en este caso de enunciado. Está bien que en el punto 2 se indique que se use PLSQL para crear la base de datos? Creería que habría que usar Postgresql, pero tal vez no son excluyentes. Pido ayuda en esto también.

Muchas gracias de antemano

**Comment by tom4stapia** [comment]
Hola! Como se anunció en canvas:
- La url para conectarse es [grupoX@bdd1.ing.puc.cl](mailto:grupoX@bdd1.ing.puc.cl)
- La clave inicial es el [mail-sin-@uc.cl](mailto:mail-sin-@uc.cl) del primer integrante del grupo, pero al logearse pide automaticamente cambiar la clave.

En cuanto a la segunda pregunta, tienes que usar la terminal de postgresql para usar las sentencias DDL en PL/SQL.

**Comment by tom4stapia** [comment]
Para entrar a la terminal utiliza el comando: psql

**Comment by tom4stapia** [comment]
Ingresaste con la clave nueva y puerto 22?
