### ISSUE TITLE
Duda de Regla de Negocio (6.2)

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#181]
Hola!! Tengo una duda en el segundo punto de la sexta regla de negocio si me pudieran ayudar lo agradecería mucho. El segundo punto dice "un curso planificado se identifica por su sigla, sección y plan (cada plan pertenece a solo una sede)”, no pudo haber habido un error y haberse cambiado plan por período ("un curso planificado se identifica por su sigla, sección y período"), ya que puede ser que se dé la sección 1 de cálculo I en San Joaquín en dos períodos distintos por lo que tendrán diferentes horarios, y probablemente el profesor sea otro: así esos tres atributos no serían superllave.

Muchas gracias de antemano por la ayuda.

**Comment by ypne** [comment]
Hola
Hay que leerlo en tu contexto, el punto 6 comienza diciendo "se refiere a la oferta de cursos para un período determinado."
