### ISSUE TITLE
Duda materia Dependencia funcional con elementos nulos

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#182]
Vimos en clase que el atributo Y es dependiente del atributo X si y solo si:

Si la proyección del atributo X de la database T1 es igual a la proyección del atributo X de la database T2 entonces la proyección del atributo Y de la database T1 es igual a la proyección del atributo Y de la database T2. 

Mi problema es cuando la proyección del atributo X tiene valores nulos (atributo X puede tenerlos). En esos casos cómo se puede determinar dependencia funcional? Si se tiene X->Y pero solamente cuando X es no nulo, entonces no puede haber dependencia funcional, ya que cuando hay valores nulos no podemos comparar pi_{X}(T1) = pi_{X}(T2) ya que ese resultado sería UNKNOWN.

Cómo se puede analizar normalización en tales casos?

**Comment by ypne** [comment]
La dependencia funcional es sobre los atributos, no sobre los valores

**Comment by elneitans** [comment]
Exacto, para que exista esta dependencia debería funcionar para cualquier set de datos. Quiero comprobar que funciona cuando tengo datos nulos de acuerdo a la definición dada. Pido por favor ayuda en esto.

**Comment by ypne** [comment]
lo que mencionas es que la llave sea nula
