### ISSUE TITLE
Duda Conexión Server 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#183]
Hola; creo que nos pudimos conectar al server pero no estoy segura (adjunto fotos) del mismo modo no sabemos que datos usar; porque el excel que fue subido es solo de ejemplo o no? Si la base de datos se obtiene del server entonces cual es el nombre de esta? 
![image](https://github.com/user-attachments/assets/e96759d8-d317-4f97-9257-3d524d92c836)
![image](https://github.com/user-attachments/assets/8512b942-aee5-4f69-935a-df866e86f61e)

**Comment by ypne** [comment]
HolaJoseja, estás conectada en forma local en tu máquina

**Comment by ypne** [comment]
https://cursos.canvas.uc.cl/courses/75213/files/11156839?module_item_id=2299374

**Comment by josefa00** [comment]
Si lo vi pero sigo sin entender cual es la base de datos con la que tenemos que trabajar

**Comment by josefa00** [comment]
Al mismo tiempo no entiendo que base de datos hay que usar; el excel subido en Canvas?

**Comment by ypne** [comment]
1.- La base tiene el mismo nombre del grupo .... grupox
2.- Los datos que deben usar son los del excel, pueden exportar cada tab a un csv

**Comment by josefa00** [comment]
perfecto gracias; entonces cual es la idea de conectarse al server desde el principio?

**Comment by ypne** [comment]
si, deben trabajar en el server entregado. Si quieres puedes hacerlo todo local pero despues debes copiar Y PROBAR todo al server (códigos, datos, bases, etc.) ya que se pobará ahí. Además puede que local pudieras tener otras librerías diferentes al server. Déjate al menos un par de dias para copiar y probar en el server.
Además te ahorras tener que instalar el ambiente en la maquina local (PHP, APACHE, POSTGRES)

**Comment by josefa00** [comment]
perfecto gracias; y como conecto al server de manera no local para ir probando todo ahi?

**Comment by coniverav** [comment]
Misma pregunta, no entiendo. Seguimos el tutorial del readme y creamos un usuario, pero en los computadores de mis compañeros el usuario no existe (el de postgres).
