### ISSUE TITLE
Plataforma Trabajo conjunto

### ISSUE THREAD

**Issue by Cdelalastra** [IIC2413/Syllabus-2024-2#184]
Hola!, Para trabajar en conjunto con los mis compañeros, estamos usando la extensión de VS Code live share. He tenido muchos problemas para conectarme. Me sale reiteradamente este error, y yo y la host si estamos conectadas a internet.
![Captura de pantalla 2024-10-04 131126](https://github.com/user-attachments/assets/bf12150d-cbf0-4523-a2de-c57bc86bb03c)
¿Que puedo hacer al respecto?
¡Muchas gracias!

**Comment by ypne** [comment]
esta consulta no está en el ámbito del curso, deben buscar soporte en vs code
