### ISSUE TITLE
Pauta E1

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#186]
Hola! En la pauta E1 se usa casi siempre como llave el persona.id sin embargo en el enunciado nunca se hablo de este y para nosotras un id que identifica de manera única a una persona siempre ha sido el rut. Para proceder con la E2 no sabemos que hacer si seguir al pie de la letra la pauta de la E1 e inventar un id.persona o si trabajamos con el rut

**Comment by josefa00** [comment]
Si; nosotros usamos el numero de estudiantes sin embargo en personas la llave seria el rut y no la existencia de un id.personas. Como el enunciado se dice asumimos que todas las personas tienen rut y por esto mismo no se justificaría la creación de un id personas sin embargo como en la pauta de la E1 sale no sabemos porque guiarnos. Feliz si nos podría explicar porque en este caso se crea un id.personas

**Comment by ypne** [comment]
es opción de ustedes ambas posibilidades son correctas en el ámbito del proyecto
