### ISSUE TITLE
Duda prerrequisitos

### ISSUE THREAD

**Issue by Natitorresg** [IIC2413/Syllabus-2024-2#187]
Hola 
En el excel que nos entregan, en prerrequisitos en los atributos de prerrequisitos aparecen muchos conjuntos de números como "4440", eso se refiere a que los prerrequisitos de ese curso son todos los cursos cuyas siglas tienen esos números? o algo así? o son errores que hay que modificar, porque por lo que entendí los prerrequisitos son  o ciclos o siglas pero no creo que puedan ser siglas incompletas.

En la hoja "malla" aparecen esos números como los cursos de un ciclo, pero no entiendo si debemos dejar el numero así en la tabla de prerrequisitos, o, por ejemplo, dejar una lista de las siglas de curso con esos números como atributo.

**Comment by ypne** [comment]
respuesta en discussion
