### ISSUE TITLE
Pregunta uso de Pandas y Tailwind CSS

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#188]
Tengo algunas preguntas relacionadas con el proyecto:
¿Es posible utilizar pandas para limpiar los datos y luego subirlos a la base de datos? En caso de que se pueda, ¿se deja el script de Python en la entrga?

Respecto a la página web desarrollada en PHP, ¿puedo utilizar Tailwind CSS para no invertir demasiado tiempo en CSS?

Saludos cordiales

**Comment by ypne** [comment]
1.- Pandas, no
2.- no es necesario usar css

**Comment by nicolaslindl** [comment]
Y se puede usar la libreria Phpspreadsheet? Para leer las distintas hojas de los archivos

**Comment by ypne** [comment]
Tampoco es necesario, guarda cada tab como CSV
