### ISSUE TITLE
Distinción Profesor/Administrativo

### ISSUE THREAD

**Issue by javirossi** [IIC2413/Syllabus-2024-2#19]
Hola, para distinguir entre un profesor y administrativo: ¿Me debo fijar en la Jerarquía o Cargo? Por ejemplo,  el dato 7 señala que la jerarquía es "Profesor Asistente" y el cargo que es "Director (a) Formación Cont. y Postgra". Por otro lado, ¿está bien asumir que toda persona (en el archivo 2) que no es profesor es administrativo?

**Comment by waldoosg** [comment]
Un profesor puede ser a su vez un administrativo, como en el ejemplo que mencionas

**Comment by cataruze** [comment]
Hola, yo sigo con la duda de como diferenciar un profesor y un administrativo, si la persona tiene un dato aceptable en jerarquía lo clasifico cómo profesor? Y si tiene en cargo, lo clasifico cómo administrativo?

**Comment by ypne** [comment]
Una persona puede ser estudiante, profesor y administrativo al mismo tiempo(o cualquier combinación). Por ejemplo, un director(administrativo) puede ser un estudiante de postgrado y profesor de pregrado.

**Comment by cataruze** [comment]
Si, eso lo entendí, lo que no me quedó claro es cómo decir por ejemplo que si es administrativo. Es decir si en el atributo cargo tiene algo al tiro puedo decir que es administrativo?, aparte de poder ser profesor o estudiante. Y en el caso de los profesores, se ve en jerarquía? Si es así asistente, asociada, instructor… también cuentan como profesores?

**Comment by Matias449** [comment]
Misma duda, por ejemplo aquellos que no declaran jerarquía ni cargo quedan sin clasificación (ni profesor ni admin)?, y por ejemplo encontré una persona que dice asociado regular y académico, califica como profesor, admin ninguno? al igual que que pasa con asistente, instructor y asociados docentes, es suficiente para calificarlos como profesores?. En resumidas cuentas hay algun parámetro estándar o debemos intuir nosotros y luego explicar en informe que criterios ocupamos?

**Comment by waldoosg** [comment]
Si posee los datos necesar para pertenecer a la matriz de estudiante, profesor o administrativo, se añade respectivamente

**Comment by cataruze** [comment]
> Si posee los datos necesar para pertenecer a la matriz de estudiante, profesor o administrativo, se añade respectivamente

En este caso, si en persona, no tenia nombre pero lo reemplaze con X, igualmente se pone en la matriz personas o no lo debo incluir?

**Comment by waldoosg** [comment]
Agrégalo igualmente
