### ISSUE TITLE
Duda con cargador y limpieza de datos

### ISSUE THREAD

**Issue by amadasaez** [IIC2413/Syllabus-2024-2#191]
Hola, tengo unas dudas con el cargador de datos y la limpieza de datos.
1. No entiendo cómo debe ser el cargador de datos. Debe ser igual de la E0? Porque con el video que se subió de la Ayudantía 5 no entendería para qué debe conectarse con postgresql. Si tengo los datos en el mismo computador.
2. Para la limpieza de datos no entiendo el orden las acciones. Debo primero limpiar la base y luego hacer las tablas? O da lo mismo. Además no sé si puedo hacer una tabla con errores y otra sin como por cada hoja de los datos. También no sé si se puede hacer una copia de los datos que tengo y luego trabajar sobre eso para encontrar los errores. 
3. Al crear la tabla de SQL, esta donde se crea? donde se guarda? que no sé como puedo trabajarla o ver lo que tiene dentro después de crearla.
Muchas gracias

**Comment by ypne** [comment]
respuesta en discussions
