### ISSUE TITLE
Lectura de datos desde el Excel

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#192]
Buscando en internet me salio que debo instalar la librería PhpSpreadsheet, con el comando "composer require phpoffice/phpspreadsheet", esta librería se puede usar? Ya que o sino por lo que tengo entendido no se podría leer el archivo excel

**Comment by ypne** [comment]
No es necesario

**Comment by Ilancf** [comment]
Entonces cómo hago para leer los datos del excel?
Actualmente lo que hice fue de cada hoja del excel hacer a mano un csv con esos datos, pero como usted dijo de no tocar el excel no se si es valido, ya que ustedes van a tener posiblemente otros datos. Esto que hago actualmente esta permitido?

**Comment by ypne** [comment]
<img width="929" alt="Screenshot 2024-10-07 at 3 04 04 PM" src="https://github.com/user-attachments/assets/102450de-5b87-479b-a29c-05c783145ede">

**Comment by MathiasPrett** [comment]
> <img alt="Screenshot 2024-10-07 at 3 04 04 PM" width="929" src="https://private-user-images.githubusercontent.com/140910038/374280709-102450de-5b87-479b-a29c-05c783145ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjc4NDAsIm5iZiI6MTcyODMyNzU0MCwicGF0aCI6Ii8xNDA5MTAwMzgvMzc0MjgwNzA5LTEwMjQ1MGRlLTViODctNDc5Yi1hMjljLTA1Yzc4MzE0NWVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxODU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2JkMTI0MDY4ZTJjZDc0ZWU5Nzk1NTk0N2U2NzU3MjQ0ZDdkYTMxYTNlYjExN2UxMmY4ODg2YjEwZmVlNDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XpOpxxZleJEcyz7nPI9rmFcGoWWSKP1JQmIju8qxbXs">

![Captura de pantalla de 2024-10-07 16-02-28](https://github.com/user-attachments/assets/ce217dfa-591c-4f7c-8297-ccda52e5458d)
_(No aparece escrita esa nota en el enunciado)_

Hola Profesor, creo que estamos trabajando con enunciados distintos y el que se encuentra subido al Syllabus está desactualizado. Saludos.

**Comment by augustayanez** [comment]
podemos separar el excel manualmente en varios archivos csv o se tiene que hacer programando?

**Comment by ypne** [comment]
Mathias, no veo la diferencia en la imagen... me pueden indicar dónde está?

**Comment by ypne** [comment]
> podemos separar el excel manualmente en varios archivos csv o se tiene que hacer programando?

A mano, save as CSV uno por tab

**Comment by MathiasPrett** [comment]
> Mathias, no veo la diferencia en la imagen... me pueden indicar dónde está?

Si. Usted indica en la respuesta anterior:


> <img alt="Screenshot 2024-10-07 at 3 04 04 PM" width="929" src="https://private-user-images.githubusercontent.com/140910038/374280709-102450de-5b87-479b-a29c-05c783145ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzIzNzAsIm5iZiI6MTcyODMzMjA3MCwicGF0aCI6Ii8xNDA5MTAwMzgvMzc0MjgwNzA5LTEwMjQ1MGRlLTViODctNDc5Yi1hMjljLTA1Yzc4MzE0NWVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QyMDE0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjhkNTc5ODk5OTQ3NzZkNzU0MjRmZWViYjEwNmVkOTNkZWE0ZmJkY2MyMzg1ZDAzMWRhODZkMmIzNjE4NjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GojMuM4nSsipXFZ2agLCm_UX4OdlgVH_rjHqF_QTj9c">

Lo que parece ser una captura sacada del enunciado de esta entrega. Busqué esa nota en el enunciado disponible en el Syllabus del proyecto, y no logro encontrarla. Mi respuesta, la captura de pantalla, quiere decir que busqué de manera textual esa frase y no se encuentran coincidencias.

Lo que me lleva a pensar que el enunciado que usted tiene, y del cual se indica que se puede separar el excel en CSV's, es distinto al que nosotros tenemos subido en el Syllabus.

**Comment by MathiasPrett** [comment]
![imagen](https://github.com/user-attachments/assets/b2b78385-d6d2-4ca8-b0a3-4b7bf32d39ef)

En el enunciado que tenemos (y que acabo de volver a descargar del Syllabus), solo nos sale esto, no la nota que indica.

**Comment by ypne** [comment]
OK gracias. Lo están regularizando. En todo caso en discussions hay un listado del tratamiento de datos donde aparece lo de los CSV
