### ISSUE TITLE
Diferentes prerequisitos

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#193]
Me queda la duda de cual prerequisitos considerar entre el que se encuentra en "Asignatura" y "prerequisito", ya que en la siguiente imagen se ve que en uno hay 1 prerequisito y en el otro no tiene, entonces quisiera entender mejor este tema de los prerequisitos
![Screenshot 2024-10-07 155654](https://github.com/user-attachments/assets/f5e9ce25-8dd8-4964-8240-a91dce407a2d)
![Screenshot 2024-10-07 155730](https://github.com/user-attachments/assets/25428fa5-3031-4e20-a15c-fba641b1f710)

**Comment by ypne** [comment]
buena observación , voy a hacer el cambio en el archivo. los prerequisitos entan en el tab prerequisitos.
gracias

**Comment by ignanuyens** [comment]
Hola! una pregunta, se cambiaron los archivos con las tablas? para volver a descargarlas.
Deberían coincidir los prerrequisitos de la tabla asignaturas y prerequisitos?

Muchas gracias
