### ISSUE TITLE
relación carrera

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#194]
viendo el esquema relacional que se subió como pauta de la entrega 1, en la relación carrera existen los atributos nombre, plan de estudio y numero de alumno. En donde se escoge como primery key plan de estudio, pero creo que debería ser número de alumno, ya que de no ser así no la identificaría de forma única, porque en un plan de una carrera hay varios alumnos y por lo tanto creo que no podría ser plan de estudio la llave primeria. esta afirmación es correcta y la llave primaria deberia ser número de alumno?

**Comment by ypne** [comment]
No se mareen con eso. El esquema relacional que ustedes deben hacer  debe estar en 3FN (o BCNF) y  para eso deben determinar las dependencias funcionales.
Debe haber una tabla plan con la definición exclusiva de la plan(cod plan, nombre plan, nombre carrera), otra estudiante(num alumno, nombres, etc.) una relación alumno plan (id alumno, id plan, carrera) todo dependiente de las dependencias que determinen.

**Comment by ypne** [comment]
que es lo que dice tu esquema?

**Comment by Ilancf** [comment]
Carrera(llave primaria(estudiante.numero de estudiante), nombre, llave foranea(plan de estudio.código))

**Comment by ypne** [comment]
ok, por lo que veo tu tabla carrera es la relación estudiante carrera  (estoy suponiendo que nombre es el nombre de la persona). Una observación Carrera no es una entidad, sino que un atributo de Plan de estudio ya los estudiantes estudian un plan, no una carrera. Te recomiendo lo siguiente
Tabla Estudiante-plan
        número de alumno PK FK (alumno.número de alumno)
        codigo de plan PK FK(plan. código)
El nombre del estudiante está en la tabla persona

**Comment by ypne** [comment]
la carrera solo depende del plan no del alumno
tabla plan 
cod plan PK
nombre
etc.....
