### ISSUE TITLE
Carácter de curso

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#195]
en el enunciado se menciona de la existencia de un carcácter el que puede ser según el enunciado: "MIN M ́ınimo, ”TALLER” Optativo de ampliaci ́on, ”ELECTIVO” Optativo de profundizaci ́on, CTI/CSI Curso transversal/sello institucional. Los de tipo ”TALLER” deben rendirse en el primer ciclo, Los ”CTI” o ”CSI” son uno por ciclo y los ”ELECTIVOS” son de segundo ciclo". Pero en el excel no logro encontrar este carácter en las asignaturas ni en ninguna hoja del excel, este atributo lo obviamos nómas o de donde lo obtenemos?

**Comment by ypne** [comment]
es parte del nombre "Taller:"
tambien pueden usar la hoja malla donde todos los cursos especificados con número son mínimos. El resto aparecen con nombres genéricos como CSI, Taller, electivo

**Comment by ignanuyens** [comment]
Hola! me sucedió lo mismo, pero sigo sin entender mucho la tabla de malla. Entendí que si un curso es de caracter TALLER, su nombre iniciará así. Pero no logro ver el resto: "MIN M ́ınimo,  Optativo de ampliaci ́on, ”ELECTIVO” Optativo de profundizaci ́on, CTI/CSI Curso transversal/sello institucional. Los de tipo ”TALLER” deben rendirse en el primer ciclo, Los ”CTI” o ”CSI” son uno por ciclo y los ”ELECTIVOS” son de segundo ciclo". 

Le agradecería si me explica con mayor detalle cómo puedo analizar el carácter de un curso, a partir de la tabla malla, tomando en cuenta que la tabla malla es más para visualizar y no para el manejo computacional de los datos. Me cuenta ver cómo a través de un código puedo ver el carácter de todos los cursos a partir de la tabla malla. 

Muchísimas gracias de antemano

**Comment by ypne** [comment]
En la malla aparecen 3 tipos de curso
1.- Los que se identifican con un número es minimo 
2.- electivo corresponte a los que dicen electivo en el nombre
3.-taller corresponde a los que dicen taller en el nombre
4.- CTI o CSI son los que dicen CSI o CTI en el nombre

todo curso se compone de dos partes XXX y NNNN donde XXX es el plan y NNNN un número. La malla está explícita para los planes HP2 y HW2.
O sea si en la malla aparece 3456 el curso puede ser HP23456 o HW23456 y ambos son equivalentes.

**Comment by ignanuyens** [comment]
No entendí el punto 1.- Los que se identifican con un número es minimo, me puedes dar ejemplos de asignaturas que sean mínimas y en qué columna viste eso por favor? 

Por otro lado, encontré asignaturas de carácter TALLER, ELECTIVO, CTI, pero si busco CSI no se encuentra ninguna referencia en las tablas, no sé si se debe a un error o algo por el estilo.

muchas gracias nuevamente

**Comment by ypne** [comment]
1.- están en la malla
2.- Si no encuentran CSI está bien, solo no hay datos, igual con los otros
3.- Si no hay datos no les afecta

**Comment by ignanuyens** [comment]
No encuentro nada en la malla que me hable de las asignaturas de carácter Optativo de ampliación, Optativo de profundización. Por otro lado, los cursos mínimos sigo sin entender cuáles son, ya que todos los cursos se identifican con un número, así que todos serían mínimos. Tampoco entiendo aún a qué ciclo pertenecen los cursos de carácter Optativo de ampliación, Optativo de profundización. 
Gracias

**Comment by Nicolvnd** [comment]
No soy de la administración del curso, pero según entendí yo los que son TALLER son Optativo de ampliación y los que son ELECTIVO son Optativo de profundización, pero me sumo a la pregunta sobre los mínimos, ya que hasta según entiendo yo, la malla del excel es la malla solo de un plan, entonces como podría saber cuales son los mínimos de los otros planes? podría asumir que todos los que no son de tipo TALLER, ELECTIVO o CTI/CSI son mínimos? 
Gracias.
