### ISSUE TITLE
Bonus E2

### ISSUE THREAD

**Issue by denisekinzel** [IIC2413/Syllabus-2024-2#196]
Hola! Con mis compañeras de grupo tenemos descargado un enunciado con un bonus antes del punto 6, en la página 3. Pero ahora, en github y en Canvas, el enunciado no tiene ese párrafo. Eso significa que ya no existe bonus? Y hay algo más que haya cambiado entre los enunciados que debamos tener en cuenta?
Gracias!!

**Comment by ypne** [comment]
<img width="680" alt="image" src="https://github.com/user-attachments/assets/316f7e7d-6e1d-4a4a-9465-2cb15d0c522e">

**Comment by augustayanez** [comment]
hola! los estudiantes que suspendieron estudios también los tenemos que considerar como retirados o "desertores"?
