### ISSUE TITLE
Run en archivos planeación y docentes planificados 

### ISSUE THREAD

**Issue by rosarioguerreror** [IIC2413/Syllabus-2024-2#198]
Hola! Me quedan dudas respecto a cuál RUT considerar como correcto en los diferentes archivos. Hemos encontrado una diferencia entre los RUTs del archivo de planeación y el de docentes planificados, y no se especifica cuál debería ser el que se tome como referencia para unificar los datos.

<img width="1189" alt="Screenshot 2024-10-09 at 11 32 55" src="https://github.com/user-attachments/assets/0713b5ca-fcde-4dee-bbc5-bc2430fd2ba3">

Gracias!

**Comment by ypne** [comment]
Hola si no tienen información extra deben seguir la misma regla indicada antes.

**Comment by oliviallanosj** [comment]
cual regla

**Comment by ypne** [comment]
la que está en el enunciado
