### ISSUE TITLE
Creación de atributos tipo "ID" a distintas entidades

### ISSUE THREAD

**Issue by agustinvaldesz** [IIC2413/Syllabus-2024-2#199]
Esta permitido crear atributos de tipo ID a entidades que no necesariamente se explique por enunciado que lo tienen, por ejemplo avance académico o a listas de cursos ofrecidos? Esto con el fin de hacer un mejor esquema relacional, y poder alcanzar la forma BCNF.

**Comment by ypne** [comment]
si
