### ISSUE TITLE
Atributos a utilizar en el Esquema

### ISSUE THREAD

**Issue by oliviallanosj** [IIC2413/Syllabus-2024-2#200]
Hola! Tengo una duda sobre los atributos de cada entidad, ya que en los archivos hay datos que no necesariamente debiéramos ocuparlos y que no fueron mencionados en el enunciado. Por ejemplo, en el archivo Planeación hay un atributo que es el lugar (sala) y el edificio, pero para la entidad de oferta académica solo es necesario la sala. En ese caso solo ocupamos algunos de los atributos que nos entregan en el archivo excel o es necesario utilizar todos?

Además, hay datos que no se encuentran en los archivos del excel, por ejemplo Plan de estudios posee atributos como cantidad_OFG, cantidad_OPR y no hay nada en relación a ellos en los archivos entregados. En ese caso eliminamos los atributos que no tienen contenido?

**Comment by ypne** [comment]
1.- Deben cargar todos los atributos
2.- Carguen los atributos e indique que no tienen los datos
