### ISSUE TITLE
Limpieza de archivo

### ISSUE THREAD

**Issue by amadasaez** [IIC2413/Syllabus-2024-2#201]
Hola, una pregunta, ¿puedo limpiar los archivos al mismo tiempo que creo las tablas, por ejemplo con los espacios nulos?¿ O tengo que crear la tabla de errores con absolutamente todos los errores y luego ir como "sumándolos" a la tabla sin errores ?

**Comment by emivenezian** [comment]
misma pregunta

**Comment by ypne** [comment]
respondo en discussions

**Comment by emivenezian** [comment]
no me queda claro lo expuesto en discussions, es simplemente el enunciado. porda responde la pregunta

**Comment by ypne** [comment]
aún no publicaba la respuesta

**Comment by emivenezian** [comment]
oka, escribi en disscusions la duda
