### ISSUE TITLE
Conexión con servidor

### ISSUE THREAD

**Issue by vicenterodas** [IIC2413/Syllabus-2024-2#202]
Hola, no logro conectarme con el servidor.
Ya hice todos los pasos de conectarme a través de ssh, luego crear la contraseña y la conexión por Filezilla.
Pero al crear un archivo php para cargar los datos no logro conectarme.

Este es el código. Vale decir que también probé con 'grupo76@bdd1.ing.puc.cl' en host.
<img width="680" alt="Captura de pantalla 2024-10-09 a las 15 26 39" src="https://github.com/user-attachments/assets/92d6edcf-341e-4f73-bb49-80b714b955e4">

Y me arrojo este error.
<img width="970" alt="image" src="https://github.com/user-attachments/assets/42f594f9-67d9-4421-8b22-5cf96a6913e7">

No he logrado solucionarlo de ninguna manera, que debo hacer. Gracias.

**Comment by ypne** [comment]
asignado a Martin Andrighetti

**Comment by mkoporcic** [comment]
hola, tengo el mismo problema

**Comment by ypne** [comment]
revisaron la documentación en canvas?
https://cursos.canvas.uc.cl/courses/75213/files/11163470/download?download_frd=1

**Comment by kovaxis** [comment]
Hola!

El servidor solamente acepta conexiones a través de `localhost` (el servidor y tu código PHP corren en la misma máquina, y por ende para conectarse a la base de datos basta con conectarse a `localhost`). Tienes que cambiar el host a `localhost` así como muestra el código de ejemplo `index.php`:

```php
<?php

// Ejemplo que muestra como conectarse a la base de datos y ejecutar queries
// Recuerda que tienes que establecer una contraseña como indica el README
// Reemplaza `grupoX` y `contraseña` por el identificador de tu grupo y la
// contraseña que estableciste respectivamente.

echo "hola mundo!"

$db = pg_connect("host=localhost port=5432 dbname=grupoX user=grupoX password=contraseña");
$result = pg_query($db, "SELECT * FROM book");
$rows = pg_fetch_all($result);
echo json_encode($rows);

?>
```

**Comment by CatalinaBO** [comment]
el puerto para nuestra entrega sería 5432 o 22?
