### ISSUE TITLE
Cambiar formato fecha inicio vigencia

### ISSUE THREAD

**Issue by JaimeMatas** [IIC2413/Syllabus-2024-2#203]
Buenas tardes,
Como grupo tenemos la siguiente pregunta: si tenemos un atributo de una tabla que es un date, como por ejemplo inicio_vigencia en plan_de_estudios, podemos cambiar el formato, en cargador.php, es decir no directo del csv, del dato correspondiente a inicio_vigencia, para que así coincida con el formato que requiere date. Esto ya que sino no se lograría poblar poblar la tabla con ninguna tupla, dado que el formato no sería compatible con el de date y nos saldría un error. ¿Podemos hacer esto, o debemos enviar todas las tuplas al archivo con los errores y luego cambiarles el formato?

**Comment by ypne** [comment]
si, pueden hacerlo
