### ISSUE TITLE
Conexión del cargador al servidor

### ISSUE THREAD

**Issue by diegofuentesy** [IIC2413/Syllabus-2024-2#205]
Hola, tengo una duda a como se debe correr el cargador. No entiendo si es que este se va a correr desde dentro de nuestro servidor? o este va a ser un archivo que al correrlo desde cualquier carpeta local debe ser capaz de conectarse al servidor y limpiar y cargar los datos.

**Comment by ypne** [comment]
se va a correr desde la cuenta de su grupo en el server del curso
