### ISSUE TITLE
Duda "Calificaciones" archivo notas

### ISSUE THREAD

**Issue by antoriffoc** [IIC2413/Syllabus-2024-2#207]
Hola!
Quería consultar qué hago con las calificaciones "DP", "EI", "ES", "HO", "RE", "SC" y "SD" que no tienen nota, ya que en el enunciado estas no son especificadas como calificaciones válidas.
Las que sí tenían nota las cambié por su correspondiente según el enunciado. 

Muchas gracias.

**Comment by ypne** [comment]
Muy bien!!!! yo no las había visto, probablemente son calificaciones antiguas y descontinuadas, pero válidas. Lo mejor es  agregarla a la tabla de calificaciones para no perder el dato de que fue un curso realizado y con eso debiera pasar la restricción de integridad.
