### ISSUE TITLE
Duda valores en tabla de prerrequisitos 

### ISSUE THREAD

**Issue by escontre** [IIC2413/Syllabus-2024-2#209]
Hola, no entiendo como interpretar los numeros que aparecen en la columna de prerrequisitos en la tabla "prerrequisitos".
Por ejemplo para "ENCANTAMIENTOS I" se tiene como prerrequisito "4440".

**Comment by FelipeFuentesG** [comment]
Hola, me sumo a la pregunta

**Comment by VAMarques** [comment]
Hola, creo que he descrifrado el significado:

Por ejemplo, esta es una muestra del curso HP24440

HP2 | HP24440 | INTRODUCCION AL LOS   ENCANTAMIENTOS
-- | -- | --

Entonces nota como HP2 es el codigo de plan, luego, en la sigla, hay otro HP2, y el resto es 4440, entonces el 4440 es el numero de curso, con el cual, quiza, puedan haber equivalencias.

**Comment by escontre** [comment]
Ahhh capto. Muchas gracias :)
