### ISSUE TITLE
Profesores/Administrativos duplicados

### ISSUE THREAD

**Issue by k0rval4n** [IIC2413/Syllabus-2024-2#21]
¡Hola! Tanto en la matriz de personas como de estudiantes se exige que las entradas sean únicas, pero en la de profesores no se indica. ¿Entonces, debemos permitir que exista más de una entrada por profesor, o es un error? Muchas gracias!
![image](https://github.com/user-attachments/assets/2e37b729-1f74-4556-8a4d-140ece1b55ab)

**Comment by TomasKetterer** [comment]
Hola, no deberían haber profesores duplicados en las tablas, por lo que no sería necesario manejar ese caso en profesores. Se especificó en los otros casos porque si tienen duplicados

**Comment by k0rval4n** [comment]
> Hola, no deberían haber profesores duplicados en las tablas, por lo que no sería necesario manejar ese caso en profesores. Se especificó en los otros casos porque si tienen duplicados

Super, muchas gracias! 👍
