### ISSUE TITLE
Duda sobre las tablas a cargar en la base de datos

### ISSUE THREAD

**Issue by Catalina-Vasquez** [IIC2413/Syllabus-2024-2#210]
Hola, me surgió una duda de la lógica que debemos seguir para cargar las tablas. 
¿Se deben corregir y limpiar los archivos entregados y cargarlos tal como se encuentran organizados en tablas en la base de datos, para luego a partir de esas tablas crear otras tablas que representen las entidades de nuestro modelo? o en lugar de eso se deben crear directamente las tablas asociadas a las entidades reorganizando antes los atributos de los archivos csv.

**Comment by ypne** [comment]
Hola
Existen las dos posibilidades
1.- cargar los datos directo a las tablas del modelo o
2.- Cargar los datos tal como vienen en los csv y luego, a partir de estas tablas cargar los datos en las tablas del modelo. 
El tema es que en el caso 2 la conversión debe ser automatizada, no manual.
