### ISSUE TITLE
Duda dominio de los atributos

### ISSUE THREAD

**Issue by antoniamarin** [IIC2413/Syllabus-2024-2#211]
Hola, tenía una consulta sobre el dominio de los atributos para el esquema relacional. En clases hemos visto int, serial, char, varchar, date etc. Pero en un ejemplo de esquema que subieron utilizaron sólo int y string. Mi duda es, entonces, está bien si usamos string para las fechas en vez de date, int en vez de serial, y string para los char y varchar? O debemos usar date, serial y varchar?

**Comment by ypne** [comment]
Deben usar los tipos de datos correctos para las restricciones del enunciado, en la documentación entregada en canvas están todos los tipos de datos soportados. https://www.postgresql.org/docs/14/datatype.html
