### ISSUE TITLE
Duda relación académico-curso: DATOS

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#213]
Buenas, en la data entregada se dan dos tablas relevantes para mi pregunta: Notas, donde se entrega el curso-período de un estudiante y su nota, y la planeación, que indica el profesor (y horario, lugar,etc) dado un curso-período-sección. Sin embargo esto es incompleto respecto lo que dicen las Reglas de Negocio donde (punto 5.1): "Cada curso realizado o en ejecución por parte de un estudiante tiene, además de la nota, calificación, nivel, etc., el período en que fue realizado y la **sección** en la que los hizo". Es esta una carencia que creo que existe: que la sección que tomó cada estudiante no se coloca explícitamente ni se puede inferir. 

Esto me afecta al realizar la segunda consulta, en la que se pide ingresar cualquier período y retornar los nombres de los cursos que se dieron, con su profesor y el porcentaje de aprobación que tuvo. No solamente con lo anterior, sino que también no sé cómo se puede saber qué profesor dictó qué curso-sección otro período que no sea 2024-02, ya que la tabla que relaciona académicos con cursos ofrecidos, Planeación, solo abarca el 2024-02. Además se nota que distintas secciones de un mismo curso en un mismo período pueden tener distintos profesores, por lo que no se puede asignar el mismo profesor a todas las secciones.

No sé si llevo muchos días sin dormir o realmente hay un problema en los datos para realizar tal consulta. Pido ayuda si es que hay algo que no esté viendo.

Muchas gracias de antemano

**Comment by Paulaverastegui** [comment]
Hola! concuerdo con mi compañero, es imposible saber que profesor dictó que curso en que periodo. Se da solo la planeacion del 2024-2 por lo que es imposible saber que curso dicto que profesor en semestres anteriores. No tiene mucho sentido entregar los porcentajes de aprobacion por profesor ya que no se sabe que nota corresponde a que profesor, ni tampoco que profesor dicto que curso en que periodo. Esto no solo afecta la consulta 2 si no también la consulta 3.

**Comment by tereriosg** [comment]
Tengo la misma duda. No es posible relacionar un profesor con un curso dictado con anterioridad con los datos especificados. Podemos realizar las consultas sin considerar profesores? Para poder realizarlas.

**Comment by ypne** [comment]
Para la consulta asuman que en cada curso-periodo se dictó solo una sección

**Comment by tereriosg** [comment]
Entonces elegimos arbitrariamente un profesor que dicte esa asignatura? O simplemente no incluimos profesor

**Comment by Paulaverastegui** [comment]
No tendría ademas mucho sentido la consulta 3, "Entregue para un curso(código) ingresado como parámetro ,el promedio del porcentaje de aprobación histórico agrupado por profesor" porque sería el porcentaje de aprobacion de un curso nomas, porque si asumimos que solo hay una seccion sería solo un profesor tambien.

**Comment by ypne** [comment]
tienen cerca de 20 años de datos, debe haber más de un profesor por curso

**Comment by Paulaverastegui** [comment]
entiendo que hay mas de un profesor por curso pero yo no tengo como saber que calificación corresponde a que profesor, por lo que no tengo como agrupar el porcentaje de aprobación por profesor. Sería más bien el porcentaje de aprobación del curso, pero cuando tengo una calificación no tengo como saber que profesor le dictó ese curso al estudiante, por lo tanto no puedo agrupar los porcentajes de aprobación.

**Comment by Utmite** [comment]
A
