### ISSUE TITLE
Tiempo límite para poblar tablas

### ISSUE THREAD

**Issue by JaimeMatas** [IIC2413/Syllabus-2024-2#214]
Buena tardes,
Tengo la siguiente pregunta: en poblar la tabla historial_academico nuestro archivo se demoró cerca de 10 minutos, esto debido a la extensión del archivo Notas.csv que tiene alrededor de 600.000 líneas.
Me gustaría saber si, al corregir nuestra tarea, ustedes cargarán y poblarán todas las tablas desde cero o si utilizarán nuestra base de datos ya cargada para revisar todo. 
La tabla se pobló de manera correcta, por lo que el tiempo de duración, para nosotros, ya no es un problema, sin embargo, no estoy seguro si esto representará un inconveniente para ustedes. 
Agradezco de antemano su respuesta a esta duda.
Muchas gracias.

**Comment by LUCAS13-ING** [comment]
Tengo la misma duda

**Comment by ypne** [comment]
no hay inconveniente
