### ISSUE TITLE
Uso de Excel para pre-limpiar los datos

### ISSUE THREAD

**Issue by SSParzival** [IIC2413/Syllabus-2024-2#215]
Hola buenas, en base a lo mencionado en ayudantía, tengo la duda sobre si se puede usar Excel para pre-limpiar los datos.

**Comment by Utmite** [comment]
Tengo la misma duda, por lo dicho en la ayudantía

**Comment by ypne** [comment]
<img width="783" alt="image" src="https://github.com/user-attachments/assets/bf434539-7ce4-480d-bbcd-333991e312a9">
