### ISSUE TITLE
¿Como asignar estamento a una persona? 

### ISSUE THREAD

**Issue by Durmye** [IIC2413/Syllabus-2024-2#216]
En el enunciado se explica que el estamento puede tomar los siguientes valores: 
1. Alumno vigente
2. Alumno no vigente
3. Exalumno
4. Administrativo
5. Academico

En base a esto, surge la duda: 

Dado el caso en el que una persona es "concurrentemente" cualquier combinación en base a los valores anteriores. El atributo estamento, ¿Que valor debería tomar? 

Ejemplos: 
- Sea una persona estudiante y academico al mismo tiempo, su atributo estamento debería ser: 
    - Estudiante vigente
    - Academico 
   ¿O una combinación de ambas?

- Sea una persona academico y administrativo al mismo tiempo, su atributo estamento debería ser: 
    - Academico
    - Administrativo
    ¿O una combinación de ambos?

¡Gracias!

**Comment by ypne** [comment]
Depende del modelo que hayan hecho. Una persona puede ser varios estudiantes y cada estudiante puede ser en forma exclusiva vigente, no vigente o exalumno.

de igual forma los administrativos van en la tabla administrativo y/o académico si es que lo modelalor así

**Comment by Durmye** [comment]
Claro, existe la posibilidad de que una persona tenga muchos "estamentos" de manera concurrente. En este caso, ¿Cuál es el que "prevalece"? ¿O es necesario mostrar todos ellos? 

Asumiendo que una **Persona** tiene que asumir un valor en el atributo **estamento**
