### ISSUE TITLE
Duda Revision de todos los datos de las tablas dadas

### ISSUE THREAD

**Issue by rinsoni** [IIC2413/Syllabus-2024-2#217]
Holaa, segun el diagrama y esquema que hemos desarrollado, para poblar las tablas no necesitamos todos los datos de los archivos .csv que nos pasaron. Esta bien eso? Es necesario usar todos los datos y revisar cada atributo si es que algunos no lo ocuparemos? O hay algun error en nuestro esquema?

**Comment by ypne** [comment]
Se deben cargar todos los atributos y todas las tuplas
