### ISSUE TITLE
Logro: MENCION EN PLANIFICACION SOCIAL

### ISSUE THREAD

**Issue by SebastianArroyoSanchez** [IIC2413/Syllabus-2024-2#220]
Estoy tratando de estandarizar la columna "Logro" de la tabla Estudiantes con la información que se nos dio. No logro encontrar nada sobre "MENCION EN PLANIFICACION SOCIAL" en la carrera Hechicería, no sé si asociarla a un inicio de curso, un titulo, una licenciatura o un semestre. 

¿Me podrían ayudar con esto? Muchas gracias de antemano!

**Comment by Mateodlcc** [comment]
Intenta explorar con que se relaciona lo que mencionas revisando los datos, esto puede ser simplemente por inspección visual de los datos con los que se relaciona. En caso de no encontrar nada en particular, elige una de las alternativas que propones y justifica el porqué seleccionaste esta. Sólo con lo que mencionas parece calzar con una licenciatura o titulo, pero insisto, intenta encontrar la categoría con la que tenga mayor relacion según los mismos datos y justifica en el informe lo realizado.
