### ISSUE TITLE
Duda Hoja Docentes Planificados

### ISSUE THREAD

**Issue by AracelyPaillal** [IIC2413/Syllabus-2024-2#221]
Holaa!
Tengo una duda, hay un par de docentes en que su CONTRATO es "GRATIS" y otro que es "DOUBLE TIME". Ambos tienen RUN, por lo que no fueron eliminados. Entonces, ¿qué debo poner en esas columna? si se supone que CONTRATO sólo puede ser "FULL TIME", "PART TIME" u "HONORARIO".
Además, existe una persona que tiene la SEDE igual a "TODAS". Es posible que una persona esté en todas las sedes? Qué hago con eso?

**Comment by Mateodlcc** [comment]
Para los docentes que tienen un CONTRTAO que no se corresponde con los mencionados, puedes re asignarle el valor como uno de los "válidos". En el caso de SEDE,  puedes aplicar la misma lógica.

Cualquiera sea la solución escogida, explica el porqué se tomó esa decisión y que cambios implica en los códigos relacionados.

**Comment by AracelyPaillal** [comment]
Muchas gracias!
