### ISSUE TITLE
Conexion db

### ISSUE THREAD

**Issue by begrassi** [IIC2413/Syllabus-2024-2#224]
Hola, cuando intento conectarme a la db como se explica en el index me aparece el siguiente error:
PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "grupo77"
FATAL:  password authentication failed for user "grupo77" in /home/bgrassi/BDD/E2/cargador_datos.php on line 6
A pesar de estar usando la clave que cree y que si me funciona para FileZila, incluso intente renovar la clave pero el error continua

**Comment by agustinvaldesz** [comment]
Tengo un error muy parecido

**Comment by vruizz22** [comment]
## Crear contraseña de Postgres
Su base de datos viene sin contraseña, por lo que no podrán conectarse desde PHP. Para esto,
deben crear una contraseña. Tras conectarse por SSH, deben ejecutar el siguiente comando:
```bash
psql
```
Luego, ejecutar la siguiente query SQL:
```SQL
ALTER USER grupoX WITH PASSWORD 'clave_bacan';
```
Ahi la clave se recomienda que sea la misma que la que usaron en filezilla.

**Comment by begrassi** [comment]
Ya habia hecho ese paso, lo volvi a hacer para asegurarme, me conecte por ssh a traves de la terminal de ubuntu y ejecute psql y la query pero sigo teniendo el mismo error.

**Comment by Mateodlcc** [comment]
Revisa que el código con el que te estas conectando esté correcto, es decir, que te estés conectando al host y puerto correcto.

<?php
  require('data.php'); 
  try {
    # Se crea la instancia de PDO
    $db_77 = new PDO("pgsql:dbname=$databaseName_gp77;host=localhost;port=PUERTO;user=$user_gp77;password=$password_gp77");
  } catch (Exception $e) {
    echo "No se pudo conectar a la base de datos: $e";
  }
?>

Esto es, teniendo un archivo data.php que contenga tus variables.

[Este código es solamente un ejemplo]

**Comment by begrassi** [comment]
![image](https://github.com/user-attachments/assets/5e95d5f4-c456-4875-acbb-965471fae1f9)
Y cuando me conecto a traves de la consola si puedo, por lo que la clave no está incorrecta.

**Comment by Mateodlcc** [comment]
De casualidad su contraseña tiene algún carácter especial?
En caso de ser así es posible que haya un problema al guardarlo como variable.

**Comment by Mateodlcc** [comment]
Estás trabajando dentro del servidor o con todos los archivos en tu computador?

**Comment by begrassi** [comment]
Estaba trabajando solo desde mi computador, ahora estoy intentando conectarme al servidor via ssh pero pareciera que está caido, luego de un tiempo de espera me sale un error de timed out

**Comment by Mateodlcc** [comment]
En tu computador tienes una base de datos con ese nombre y para ese usuario creada en psotgres?
De no ser así entonces ahi está el problema, actualmente no te estas conectando directamente al servidor (ya que no estás trabajando ahi).

El segundo error, se debe a que hay demasiadas personas intentando acceder al servidor en simultáneo por lo que este no alcanza a responder. En otras palabras se cayó.

**Comment by Mateodlcc** [comment]
En tu computador (a nivel local) tienes una base de datos de postrges asociada a tu usuario (grupo77), con tu nombre de bdd y con esa contraseña? De no ser así es normal que ocurra ese error, ya que nunca vas a poder conectarse a una bdd que no existe. Si trabajas dentro del servidor estas variables estarían correctas pero si queires trabajar de forma remota o tienes que tener la BDD en tu pc o, la otra alternativa, es que te conectes remotamente al servidor, para ello el host sería la ip del servidor.
