### ISSUE TITLE
Duda ex alumno 

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#225]
Hola., al ver las tablas no se puede calificar un alumno como exalumno dado que este se diferencia por poseer título, pero esta información no se encuentra en los excels. Que hacemos en este caso?

**Comment by cataruze** [comment]
Muchas graciassss, entonces además de considerar que tengan grado y título, tengo que considerar los casos que sale alumno egresado en causal de bloqueo ?

**Comment by noamsito** [comment]
Sí, pero siempre tengan en cuenta las reglas de negocio y lo que se menciona en las notas del enunciado.
