### ISSUE TITLE
Poblar tablas 

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#226]
Hola, tenía la duda de si podía primero poblar las tablas literal igual al Excel y desp con esto crear mis propias tablas. La pregunta va más como en si puedo tener tanta cantidad de tablas aunque algunas no sean del modelo o estas deberán ser eliminadas desp de crear las nuevas tablas con respecto a las obtenidas del Excel?

muchas gracias de antemano.

**Comment by VicenteSanMartin** [comment]
Hola! Te recomiendo revisar la issue #210. Respecto a la segunda pregunta, pueden usar tablas temporales que sean eliminadas después de crear las nuevas tablas de su modelo.
