### ISSUE TITLE
SERVER caído

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#227]
Hola, quería avisar que el Server se encuentra caído.

**Comment by k0rval4n** [comment]
![image](https://github.com/user-attachments/assets/31bda85c-aa27-4de4-a95c-345a452d38ee)

**Comment by josefa00** [comment]
Trabaje todo desde el servidor remoto y no lo tengo local. Que puedo hacer; mientras el servidor siga caído no tengo como seguir avanzando

**Comment by LucasPalaciosU** [comment]
Yo también estoy trabajando remoto! No tengo cómo avanzar, por favor consideren extender el plazo que estuvo caído el servidor

**Comment by josefa00** [comment]
hola se volvió a caer

**Comment by pedrojohnson1** [comment]
Hola, por favor considerar la caída del servidor para los que estamos trabajando desde ahí. No tenemos como avanzar.

**Comment by isidorasanchezl** [comment]
Hola, se volvió a caer, por favor consideren la caída del servidor, con mi grupo también estamos trabajando remoto y no podemos seguir

**Comment by cataruze** [comment]
Nos pasa lo mismo

**Comment by Dcarva22** [comment]
Por favor considerar, nos juntamos y no hemos podido avanzar

**Comment by Rvillena75** [comment]
Hola, nosotros tampoco hemos podido avanzar y nos falta harto de la entrega, por favor considerar.

**Comment by ArthurFJ** [comment]
Nosotros igual estamos con problemas, no podemos conectar

**Comment by sbarriag** [comment]
Hola, sigue caido :(

**Comment by AkalcD** [comment]
No me puedo conectar igual :(

**Comment by Bonjour1X** [comment]
:c

**Comment by connandiaz** [comment]
Holaa se volvió a caer. Existe la chance de dar un día extra por los inconvenientes? :(

**Comment by AlanGoldsmith25** [comment]
Hola! No se si soy yo o se volvio a caer :(

**Comment by abraxvs** [comment]
Hola, se volvió a caer

**Comment by sbarriag** [comment]
Se cayo de nuevo :(

**Comment by javirossi** [comment]
sigue caído :c

**Comment by CristobalGonzalezSepulveda** [comment]
todavía está el server caído.

**Comment by mtbustamantec** [comment]
no hemos podido trabajar casi nada desde ayer!
