### ISSUE TITLE
Duda consulta 6

### ISSUE THREAD

**Issue by Natitorresg** [IIC2413/Syllabus-2024-2#229]
Hola, no entiendo muy bien el enunciado de la consulta 6:
![enunciado_consulta_6](https://github.com/user-attachments/assets/a8e9c6f8-12b6-4a70-873e-1c5a42d6940b)
Sobre esto, como los cursos vigentes no tienen nota todavía, la idea es que nosotros inventemos notas y actualicemos la base de datos con eso? no logro entender bien lo que plantea el enunciado.  Tampoco entiendo la parte "El archivo debe
contener al menos una instancia de nota-calificación de la tabla y un estudiante que no esté en
la lista". A que lista se refiere?

**Comment by antonietaflorees** [comment]
misma dudaaa :((

**Comment by arodriguez-l** [comment]
Redacción dudosa

**Comment by mauriciosalass** [comment]
tengoo la mismaa dudaaa
