### ISSUE TITLE
Duda matrices

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#23]
Hola, no entiendo muy bien a que se refieren con matrices, al comienzo pensé en que son archivos con la infromación pedida, luego pensé que simplemente es una lista en donde cada elemento es una fila de infromación de los archivos, pero ahora me confundí y pensé que quizás en PHP hay una forma más facil de hacer un estilo data frame a la cual ustedes llaman matriz. Muchas gracias por su tiempo

**Comment by waldoosg** [comment]
Con matrices nos referimos a que se pide que puedan mostrar los datos en formato tabla, no es que en php exista una estructura que sea una matriz. Lo importante es que puedas imprimirlos por consola como una tabla

**Comment by ypne** [comment]
Los datos se deben almacenar en una estructura que soporte una matriz, si no las consultas serán más difíciles de hacer.
