### ISSUE TITLE
Informe Etapa2

### ISSUE THREAD

**Issue by Tichi1010** [IIC2413/Syllabus-2024-2#230]
Hola, quería preguntar si van a habilitar un buzón en canvas para subir el informe, en el enunciado dice que hay que subir el informe a canvas. O tenemos que subirlo al server?

**Comment by VicenteSanMartin** [comment]
Hola! Tal como sale en el buzón de Canvas: 

> Solo es necesario que entregue un integrante del grupo.
Fecha de entrega: miercoles 16 de octubre a las 23:59 por Canvas.
Formato de la entrega: a.- Informe UN ARCHIVO PDF por Canvas. b.- Datos cargados en la Base de datos del server c.- Programas Cargador de datos y Bananer en la cuenta grupal del server.
