### ISSUE TITLE
Error Ingreso Server E3

### ISSUE THREAD

**Issue by abraxvs** [IIC2413/Syllabus-2024-2#231]
### ¿Cambiaron las credenciales de acceso al servidor?
Hola, quería saber si han cambiado la dirección del servidor, las contraseñas, o si aún no se habilita. Con nuestro grupo hemos intentado ingresar pero no nos permite el acceso. 
Estamos usando el comando: ssh grupoX@bdd1.ing.puc.cl
Probamos con la contraseña que utilizamos en la entrega pasada y también con el correo del primer compañero del grupo.
Necesitamos ingresar al server para trabajar.
Saludos.

**Comment by Bonjour1X** [comment]
x2

**Comment by kovaxis** [comment]
Hola, está arreglado esto. Porfavor revisar el README del servidor de la Entrega 3. En particular, ahora el comando es:

```sh
ssh grupoXe3@bdd1.ing.puc.cl
```

**Comment by abraxvs** [comment]
Genial!, Gracias
