### ISSUE TITLE
Pauta E2

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#233]
Hola! Van a subir la pauta de la E2 debido a que la necesitamos para poder trabajar en la E3. Muchas gracias

**Comment by Paulaverastegui** [comment]
Hola me sumo a los comentarios de mi compañera. Además aprovecho de preguntar por las notas de esta misma, creo que es fundamental tenerlas para poder avanzar en la entrega 3 ( si no me equivoco ya deberían estar publicadas las notas).

**Comment by domingaelton** [comment]
Si porfavor! Es muy necesaria para poder avanzar en esta entrega

**Comment by ypne** [comment]
La pauta de la E2 no se necesita para la e3 ya que la relación está en el modelo ER y eso es particular a cada grupo.
