### ISSUE TITLE
Error descarga de archivos

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#234]
Estimado profesor, 

Le quería pedir ayuda debido a que tenemos problemas al descargar el archivo notas adivinacion.csv: al intentar descargarlo por Canvas, éste nos permite descargar dos archivos: el primero pesa casi 8 MB y tiene solamente las primeras 38 líneas con datos: las otras están vacías. La segunda (que Canvas dice es el archivo "original") pesa casi 40MB pero tiene caracteres aleatorios, o basura. No sé si es un error nuestro. Cuando intentamos descargar a través de GitHub, se descarga la primera opción.

Muchas gracias de antemano.

**Comment by abraxvs** [comment]
Me pasa lo mismo :((((

**Comment by ypne** [comment]
prueben con Github
