### ISSUE TITLE
Uso de librerías en server

### ISSUE THREAD

**Issue by LudwigUC** [IIC2413/Syllabus-2024-2#236]
Para conectar el server encontré una librería que ayuda a la ejecución de esta función llamada "phpseclib". 

Mi duda es. Al momento de ejecutar el script en el servidor, ¿cómo podemos incluir librerías externas en el servidor mismo para que se ejecute todo correctamente?

**Comment by Mateodlcc** [comment]
Por algunas experiencias previas, solo se permitirá el uso de las librerías que ya se encuentran presentes en el servidor, en otras palabras, no se pueden incluír librerías externas al servidor.

**Comment by LudwigUC** [comment]
¿Cómo podemos saber que librerías están presentes en el servidor?

**Comment by LudwigUC** [comment]
Creo que se ve con "dpkg -l"
