### ISSUE TITLE
E3 sobre la eliminación de tablas y tuplas

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2413/Syllabus-2024-2#238]
Estimados:

Con respecto al punto 2 del enunciado, me gustaría saber si para borrar las tablas y tuplas de nuestra base de datos, tenemos que realizar algún procedimiento específico o podemos realizarlo directamente con PSQL desde el servidor.

También nos gustaría saber si para efectos de evaluación de esta parte, basta con dejar alguna captura de pantalla de cómo borramos estas tablas y tuplas en el informe o hay que hacer algo adicional.

Muchas gracias de antemano.

**Comment by Mateodlcc** [comment]
Hola, como indica el enunciado el procedimiento para eliminar las tablas y tuplas de sus bases de datos en el servidor se puede hacer con PSQL desde sus cuentas en el servidor o utilizando ERD Tools.

Para presentar lo anterior en el informe, basta con que indiquen el procedimiento realizado en el servior, el uso de imágenes facilitará la comprobación de lo que indiquen por lo que es altamente recomendado.
