### ISSUE TITLE
E3 sobre el archivo notas adivinacion.csv

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2413/Syllabus-2024-2#239]
Estimados:

Con respecto a la issue [234](https://github.com/IIC2413/Syllabus-2024-2/issues/234#issue-2624422535) con mi grupo descargamos el archivo tanto por Github como por Canvas, pero aun así solo podemos visualizar 37 filas siendo que el archivo pesa aproximadamente 8MB, les solicitamos si por favor pudieran subir el archivo correcto para poder trabajar de manera adecuada.

Muchas gracias de antemano.

**Comment by Mateodlcc** [comment]
Comentaré lo anterior para que se revise el tema

**Comment by Mateodlcc** [comment]
La respuesta fue que solo se trata de los datos de una sección por lo cual solo son 27 filas efectivas, el resto de filas pueden ser eliminadas.

**Comment by ypne** [comment]
el archivo tiene 37 filas
