### ISSUE TITLE
Limpieza

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#24]
Hola, en la parte de limpieza de datos
1.  hay que fijarse primero en que cumplan con los requisitos de cada sección?, por ejemplo en: codigo Plan: string, codigo del plan de estudios, no nulo. Tendría que ver que sea un dato no nulo y string o tendría que verificar algo más
2. El punteo de las reglas de negocios también se tienen que verificar? Por ejemplo:
 • El segundo archivo contiene la informacion de los profesores y administrativos vigentes.
• Los profesores y administrativos se identifican por RUN

muchas gracias de antemano.

**Comment by lucolhabe** [comment]
Hola, en el primer punto solo se verifica que cumpla con los requisitos del enunciado, con que sea un string en ese caso ya cumple. Para las reglas son como funciona el programa, por lo que no se deben verificar ya que vienen en el formato o con las restricciones indicadas.

**Comment by cataruze** [comment]
gracias, para asegurarme entonces para limpiar los datos solamente me fijo en el tipo de dato y nulidad? Y también puedo asumir que el rut será único por persona? Y la tarea será evaluada con los archivos dados o con otros?

**Comment by lucolhabe** [comment]
Efectivamente la limpieza es para que se logre que esten en el formato correcto, asi que si, y te recomiendo ver las 3 notas abajo de las reglas de negocio que pueden ayudar a entender el objetivo de la limpieza. Puedes asumir RUN unico por persona y los archivos son los dados.

**Comment by josefa00** [comment]
Hola! Puedo asumir que si me dicen que un dato es de cierto tipo (por ejemplo el mail es un str) siempre será de ese tipo o debo revisar eso y cambiarlo si es necesario?
