### ISSUE TITLE
IMPOSIBILIDAD DE DELETEAR TIPOS. 

### ISSUE THREAD

**Issue by SSParzival** [IIC2413/Syllabus-2024-2#241]
![image](https://github.com/user-attachments/assets/4e9b16ac-2927-4e4f-94f3-3ba5c26f068c)

**Comment by Utmite** [comment]
mi grupo tiene el mismo problema .-.

**Comment by VAMarques** [comment]
Por favor, yo y mi grupo, tenemos el mismo problema.

**Comment by SSParzival** [comment]
Concuerdo, mi grupo tiene el mismo problema.

**Comment by SSParzival** [comment]
Creo que necesitamos 1 día más por este error.

**Comment by ypne** [comment]
cual es la pregunta?

**Comment by Utmite** [comment]
En mi grupo creamos tipos, para así mantener la integridad, el problema es que al hacer la copia del server para hacer la entrega 3, no nos dieron permisos para editar los tipos que creamos en la entrega 2, sin embargo si nos dieron permisos para editar las tablas de la entrega 2.
Por eso nos gustaría si nos pueden dar los permisos para editar los tipos que creamos antes

**Comment by ypne** [comment]
Listo, prueben

**Comment by Utmite** [comment]
Confirmo funciona 👍
