### ISSUE TITLE
Duda puntos 2 y 3 del enunciado

### ISSUE THREAD

**Issue by ignanuyens** [IIC2413/Syllabus-2024-2#242]
Rengo una duda de enunciado de la entrega 3, respecto a los primeros 3 puntos.
![image](https://github.com/user-attachments/assets/e8e334a5-6c5c-4fca-9611-17b44535566a)

En el punto 2, con "borrar del esquema", no sé si hacen referencia a ¿borrar las tablas de "profesores" y "jerarquías" y no tener que volver a crearlas? o ¿se refieren a borrar las tuplas de esas tablas, como para la tabla Notas y Planeación. 

En el punto 3, tengo problemas con la conexión con la base de datos, y con el archivo README Servidor BDD.pdf. En un inciso de ese archivo aparece lo siguiente:
![image](https://github.com/user-attachments/assets/92f01afd-1825-44b5-a677-99f1ed729003)

Yo ya logré cambiar la clase en ssh y en postgres, pero al momento de correr la línea para conectarme (psql --sbname=e3profesores), no me funciona. No sé si es porque se debe correr escrita de otra forma, ya que tampoco sé cómo aplicar el SELECT después, ya que se supone que yo había borrado todo lo de profesores y jerarquía.

Luego, volviendo al enunciado de la entrega, donde dice "Haciendo uso de esta conexión modifique, a partir de la tabla de profesores, los valores de los atributos correspondientes en la tabla Personas. Esto se debe realizar una sola vez, por lo que debe implementar alguna forma de verificar que los datos ya fueron actualizados". Me confunde que a partir de la tabla de profesores (que ya había borrado), cambie a las personas. Sobre realizarlo una única vez, también me genera dudad de lo que sucedería si lo realizo por error más de una vez, o cómo comprobar si lo realicé.

Perdón lo largo, pero quise ser lo más clara con mi duda. Muchísimas gracias de antemano por la ayuda y disposición.

**Comment by ypne** [comment]
P: En el punto 2, con "borrar del esquema", no sé si hacen referencia a ¿borrar las tablas de "profesores" y "jerarquías" y no tener que volver a crearlas? o ¿se refieren a borrar las tuplas de esas tablas, como para la tabla Notas y Planeación.
R: Se indica borrar del esquema, no borrar las tuplas

P:"Haciendo uso de esta conexión modifique, a partir de la tabla de profesores, los valores de los atributos correspondientes en la tabla Personas. Esto se debe realizar una sola vez, por lo que debe implementar alguna forma de verificar que los datos ya fueron actualizados"....sucedería si lo realizo por error más de una vez, o cómo comprobar si lo realicé.
R: Eso es exactamente lo que se está pidiendo que implementen

**Comment by nicolaslindl** [comment]
Me sumo a las dudas sobre el punto 3: 
Donde dice "Esto se debe realizar una sola vez, por lo que debe implementar alguna forma de verificar que los datos ya fueron actualizados.", supongo que se refiere a que solo se debe insertar una vez cada registro, no que la inserción debe realizarse solo 1 vez. Es decir, que podría usar INSERT INTO ... ON CONFLICT ... , para que cada vez que se ejecute, compruebe si el registro ya esta, y si no esta, lo inserta.

**Comment by ypne** [comment]
si el registro fue actualizado, no rebe hacerse nuevamente, sinó con cada corrida se revisaría toda la tabla profesores

**Comment by anticarasosman** [comment]
Yo tambien me sumo a las dudas del punto 3, no comprendo bien como debemos conectarnos a la base de datos, ni tampoco muy bien las instrucciones para la primera conexion ¿Es posible pedir por una explicacion a mas detalle?
