### ISSUE TITLE
Tabla "Notas"

### ISSUE THREAD

**Issue by domingaelton** [IIC2413/Syllabus-2024-2#243]
En el punto 2 del enunciado sale "borre de la tabla Notas Todas las tuplas correspondientes a los cursos 2024-2". En nuestro diagrama de la entrega pasada (que lo hicimos basado en la pauta que nos entregaron de la entrega 1) no tenemos ningna tabla que se llame notas, sino que estas estan la tabla de hostorial academico. Lo mismo con tabla planeacion que en realidad la informacion esta en la tabla de oferta academica ¿Las borramos de esa tabla?

**Comment by ypne** [comment]
entonces la tabla notas se llama historial académico
