### ISSUE TITLE
Archivo nuevo Planeación 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#244]
Hola; como se debe cargar el nuevo archivo planeación se asume que este no tiene ningún error?

**Comment by ypne** [comment]
eso te lo dará el dbms cuando lo cargues

**Comment by nicolasvialy** [comment]
Hola! Sigo sin entender esto, no debemos pasar el nuevo archivo planeación por lo filtros realizados en la entrega anterior?
