### ISSUE TITLE
Eliminar tabla de planeación

### ISSUE THREAD

**Issue by Paulaverastegui** [IIC2413/Syllabus-2024-2#245]
Hola! me surgió una duda del punto 1 de la entrega. Sale que se debe eliminar la tabla de planeación, pero en el caso de mi grupo lo que hicimos al crear esa tabla fue agregar a los docentes que no estaban registrados y que si estaban en este archivo para que queden datos válidos. Mi pregunta es si solo debo borrar las tuplas de la tabla planeación (o cualquiera equivalente) o todos los datos de ese archivo que fueron guardados en otras tablas también? 

En el caso de mi grupo nosotros habíamos dividido la tabla de planeación en varias tablas para respetar el BCNF. Por ejemplo tenemos una tabla de departamentos, con sus códigos, mi pregunta es si debo borrar todos los datos creados a partir del archivo anterior de planeación o solo los de la tabla equivalente a planeación.

**Comment by ypne** [comment]
no es necesario. la tabla planeación anterior le faltaban datos para esta entrega, pueden tomar los nuevos datos y hacer un update a las suyas

**Comment by Paulaverastegui** [comment]
Perfecto gracias.
