### ISSUE TITLE
tabla temporal acta

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#247]
tengo dudas sobre la creación de la tabla acta
1) cuando trato de hacer "CREATE TEMP TABLE IF NOT EXISTS ...." me detecta todo excepto TEMP que lo lee como un string tambien probe utilizando TEMPORARY y tampoco me lo lee correctamente
2) Tengo duda sobre lo que se pide en el acta y el csv de "notas adivinación I", ya que no calzan entre si. En acta se pide "número de alumno, curso, periodo, nombre del estudiante, nombre del profesor, la única nota final", y en el csv de "notas adivinación I" contiene "número de alumno, run, asignatura, sección, periodo, oportunidad 1, oportunidad 2". Entonces mis dudas son:
- para crear la tabla acta hay que hacerlo utilizando las otras tablas como son la tabla profesores, estudiantes, y o personas, ya que se neceseitaría sacar de ahí los nombres de los alumnos y los profesores
- En "notas adivinación I" el run que contiene es del alumno o del profesor, porque si el run no es del profesor no habría manera de obtener la info para consiguir el nombre del profesor.
- Seguros que el acta no tiene el mismo formato que el csv "notas adivinación I", ya que esto tendría mas sentido para la creación de la tabla

Se que son varias preguntas y por favor agradecería que las respuestas esten divididas de la misma forma que estan las preguntas

Gracias de antemano!

**Comment by ypne** [comment]
1.- https://www.postgresql.org/docs/current/sql-createtable.html
2.- para crear la tabla acta hay que hacerlo utilizando las otras tablas como son la tabla profesores R: si
En "notas adivinación I" el run que contiene es del alumno o del profesor, r: sigla, sección, periodom -> profesor
Seguros que el acta no tiene el mismo formato que el csv "notas adivinación I", ya que esto tendría mas sentido para la creación de la tabla -> seguro

**Comment by Ilancf** [comment]
La tabla temporal acta debe tener solo las notas que provienen del nuevo archivo "notas adivinación I" o le debemos entregar todas las notas pasadas tambien?

**Comment by vicntealonso** [comment]
misma duda
