### ISSUE TITLE
Nombre del profesor en acta.

### ISSUE THREAD

**Issue by nicolasvialy** [IIC2413/Syllabus-2024-2#248]
Hola!
Entiendo que para crear la TEMP TABLE de acta se debe buscar el nombre de profesor ubicándolo con Sigla, sección, periodo que tenemos en el nuevo archivo csv. Mi pregunta es si esa busqueda debemos hacerla mediante un codigo que sea dinamico o podemos hacer una consulta directo en psql y simplemente poner "manualmente" el nombre que hayamos encontrado del profesor en el acta?

**Comment by ypne** [comment]
debe ser una consulta
