### ISSUE TITLE
Valores Nulos

### ISSUE THREAD

**Issue by njllanos** [IIC2413/Syllabus-2024-2#25]
Hola, tengo una duda acerca de los valores nulos y que hacer con ellos.

En el enunciado se dice que "Si encuentra un valor nulo y la especificación indica no nulo, reemplácelo por una marca de valor
inválido (por ejemplo en calificación, ”” por ”x” en el programa PHP)"
Pero también se instruye que "Realice la detección de los datos que no cumplan con los formatos correctos, indicados más adelante y
si es posible los corrija, de lo contrario lo **descarte**."

Por ello me da dudas de que hacer en ciertos casos en que existen valores nulos. Por elemplo, si esque en los archivos hay un registro de estudiante con los datos:
;;;;;;;;;;;.@llimail.kom;.@lamejor.cl;;;;2;;;;;;
Debo descartarlo o rellenar los valores que deberian ser no nulos?

**Comment by TomasKetterer** [comment]
Hola! En este caso, vas a notar que puedes arreglar los valores no nulos colocando "x", pero a la vez, vas a tener que descartar el registro de ese estudiante porque como se menciona en el enunciado, no se puede tener un estudiante sin RUN (y tienes que revisar todos los otros requisitos mínimos también). Trata de cumplir con todos los requisitos que te solicitan, intentando descartar la mayor cantidad de registros inválidos y arreglando aquellos que puedas arreglar. Posteriormente, reemplaza los valores no nulos con "x". Esto te debería facilitar un poco el trabajo.

**Comment by martihermosillag** [comment]
Hola, ¿podrías aclarar a qué te refieres con "descartar"? No entiendo por qué dices que se descarta el dato del estudiante si no tiene RUN, pero que también hay que revisar lo demás. Entonces, ¿descartar no significa eliminar el dato de nuestra tabla? ¿Por qué tendría que rellenar con "x" los valores no nulos si el dato ya fue descartado?

**Comment by TomasKetterer** [comment]
Quizás no me expliqué del todo bien. El enunciado dice lo siguiente:
![image](https://github.com/user-attachments/assets/b4804793-ef28-4cf2-9de0-c7a8ec4449e4)
Me refería a que pueden haber otros datos que si tengan RUN pero que no cumplan con alguna otra regla de negocio y por ende hay que revisar todas las posibles situaciones en donde un registro puede ser erróneo y se debe descartar, es decir, eliminar el registro de la tabla.

En cuanto a los de las "x", me refiero a que luego de descartar todos los datos se proceda a rellenar con "x" los registros no descartados. Espero haberte ayudado :)

**Comment by njllanos** [comment]
Hola, ¿A que haces referencia con requisitos mínimos? Lo pregunto dado que en apartado de reglas de negocio se incluye un listado de reglas, pero también el tipo de valor de cada elemento (si puede ser nulo o no).

**Comment by TomasKetterer** [comment]
Me refiero a eso mismo, las reglas de negocio

**Comment by njllanos** [comment]
Pero entonces si algo que sale en las reglas de negocio que debería ser no nulo, como por ejemplo "Nombres", ¿Debería descartarlo?

**Comment by cataruze** [comment]
Hola yo también tengo hartas dudas sobre esto. Que datos considero que si no están, hay que eliminar toda la línea? Por ejemplo, que si un usuario no tiene rut la línea de datos ya no se incluye, pero con que otros datos pasa esto, por ejemplo ocurre también con el nombre? El plan de estudios?

**Comment by faresdababneh** [comment]
Hola, yo sigo con la duda, ¿Cuales son los requisitos mínimos que si no se encuentran (O son inválidos) debieramos descartar la línea entera de información? Aparte del RUN que me quedó claro. Muchas gracias
