### ISSUE TITLE
Duda E3: Profesor y Jerarquías

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2413/Syllabus-2024-2#250]
Hola, tengo una duda sobre el enunciado: ¿A qué tabla corresponde "Jerarquía" en el esquema? Guiándome por el diagrama, ¿sería eliminar el atributo "Jerarquía" de las entidades "Profesor" y "Académico", o es una entidad en 3NF/BCNF que representa la jerarquía académica?

Saludos y gracias de antemano.

![Screenshot 2024-11-09 at 4 24 18 PM](https://github.com/user-attachments/assets/96b8b07b-fe7e-475d-99a2-2719bc453248)

**Comment by vicenterodas** [comment]
Misma duda, gracias.

**Comment by Mateodlcc** [comment]
Depende de su modelo, por lo que muestras, vendría a ser por lo menos el atributo jerarquia y todas sus dependencias

**Comment by ypne** [comment]
La base de datos nueva de profesores no es de su grupo por lo que no pueden modificarla. Según veo en su modelo jerarquía es solo un atributo, como no muestran el esquema no se si ese atributo se refiere al código (P.Ej. JC1) o al texto. Si es código deberían agregar al modelo la tabla jerarquía con los atributos código y texto solamente
