### ISSUE TITLE
E3: Nota de presentación. 

### ISSUE THREAD

**Issue by Durmye** [IIC2413/Syllabus-2024-2#251]
En las "reglas de negocio" punto dos se especifica: 

- "Si un estudiante tiene nota de presentación <= 3.0 solo tiene una oportunidad". 

Sin embargo, en el archivo `notas adivinación l.csv` se encuentran las columnas: 

| Número de alumno | RUN | ASIGNATURA | SECCION | PERIODO | OPORTUNIDAD DIC | OPORTUNIDAD MAR |

Entiendo que `OPORTUNIDAD DIC` corresponde a la nota obtenida en la primera oportunidad del examen y `OPORTUNIDAD MAR` corresponde la segunda. Entonces, ¿Dónde (o Como) consigo nota de presentación?

**Comment by ypne** [comment]
no la tienes

**Comment by ignanuyens** [comment]
Me sumo a la pregunta de mi compañero. Podrían por favor explicar con mayor claridad cómo puedo verificar que se cumplan las reglas de negocio, si no tengo la nota de presentación? 
Muchas gracias

**Comment by ypne** [comment]
es parte deñ problema

**Comment by coniverav** [comment]
no veo cómo podría obtener eso sin una explicación de qué sería la nota de presentación, agradecería que lo explique:)

**Comment by ypne** [comment]
la nota de presentación no importa ya que en la tabla se presentan las notas finales
