### ISSUE TITLE
Punto 4 vista

### ISSUE THREAD

**Issue by SSParzival** [IIC2413/Syllabus-2024-2#252]
Cuando se refiere a esto: Despliegue una Vista (1pt) con el acta de notas (en una ventana). ¿Se refiere a desplegar la vista en consola, o en página web?

**Comment by Utmite** [comment]
Misma duda

**Comment by Benjamin-Ch** [comment]
Me sumo a la pregunta.

**Comment by Mateodlcc** [comment]
https://github.com/IIC2413/Syllabus-2024-2/issues/272, perdón por la demora
