### ISSUE TITLE
Elementos E2 en E3

### ISSUE THREAD

**Issue by sofiagutierrezleiva** [IIC2413/Syllabus-2024-2#253]
Hola! Quisiera saber si en esta entrega deben mantenerse las consultas, registros de usuario, etc. de la entrega anterior en la interfaz gráfica (y lo pregunto en particular por aquellas consultas que requerían datos de profesores... ) o debemos crearla "desde 0"?

**Comment by ypne** [comment]
usen todo lo de la e2

**Comment by nsilval** [comment]
Dices que hay que usar todo lo de la e2, pero lo que tengamos incorrecto volvera a ser evaluado, hay un puntaje asignado a las cosas de la entrega pasada o el puntaje que se muestra en el enunciado por cada parte es el puntaje total?
