### ISSUE TITLE
Ejecutar SELECT para revisar datos de los profesores

### ISSUE THREAD

**Issue by anticarasosman** [IIC2413/Syllabus-2024-2#254]
Disculpa, logre conectarme a la base de datos, ejecute psql --dbname=e3profesores para revisar los datos de la tabla de profesores y luego ejecute SELECT * FROM profesores, lo cual me mostro una tabla de multiples profesores, pero luego de volve a intentar ejecutar el comando, me sale un mensaje diciendo que la relacion "profesores" no existe, revisando la relaciones actuales me sale lo siguiente:
![image](https://github.com/user-attachments/assets/2c726db8-ca7c-4bc1-b743-67dbc6bc83ea)
¿Deberia estar la relacion de profesores en esta tabla?

**Comment by elneitans** [comment]
creo que ese es tu esquema, no la e3profesores.

**Comment by Mateodlcc** [comment]
> creo que ese es tu esquema, no la e3profesores.

Como bien indicó tu compañero, estás viendo tu propio esquema, si quisieses ver el esquema de e3profesores debes cambiar a esa bdd haciendo \c e3profesores y luego puedes ejecutar el comando \dt.
