### ISSUE TITLE
Material I2

### ISSUE THREAD

**Issue by vicntealonso** [IIC2413/Syllabus-2024-2#255]
Estimados:

Espero se encuentren bien. Quisiera consultar si se publicará material complementario para el estudio de la I2, como evaluaciones de años anteriores y la solución del taller n.º 9. Agradezco de antemano su apoyo.

Saludos cordiales.

**Comment by ignanuyens** [comment]
Hola! me sumo a preguntar hasta qué numero de clase entra en la prueba.

Muchas gracias.

**Comment by ypne** [comment]
hasta la materia de 1 clase antes del la prueba

**Comment by VicenteSanMartin** [comment]
Hola! Después de la clase de este miércoles se va a mandar un anuncio confirmando los contenidos que entran en la prueba, pero debería ser desde la clase 8 hasta la 13. 

Respecto al material de estudio, todas las evaluaciones de años anteriores se encuentran en sus respectivos repositorios de Github, disponibles en la sección "Complementos" de canvas, donde hay harto material complementario. La solución del taller 9  será subida durante la semana.

**Comment by ypne** [comment]
hasta la materia de 1 clase antes del la prueba
