### ISSUE TITLE
Eliminación de notas

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#256]
Por lo que entiendo uno debe eliminar de la tabla notas solo las notas del 2024-02 correcto o se le deebn eliminar todas las notas?
Luego cuando uno ya tiene el acta, el trigger debe insertar en una tabla de notas nueva en donde solo se le van a insertar las notas de 2024-02 o debe insertarse en la tabla de notas con todas las notas de los semestres pasados?

**Comment by ypne** [comment]
<img width="891" alt="image" src="https://github.com/user-attachments/assets/e15e1919-1b04-42b4-af4c-1e5cd8aebe16">
