### ISSUE TITLE
Eliminacion de tabla profesor

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#257]
Cuando uno elimina la tabla profesor, ¿cómo se debe manejar el caso de los datos de la tabla de programación académica por ejemplo? Esta tiene como referencia el RUT del profesor en donde si se borra en cascada, se borraría la oferta academia que estaba relacionado a ese RUT, ¿o bien, borramos todos los datos de todas las tablas y volvemos a subir los datos? En estos, por ejemplo, los datos que no se van a subir, no afecten los que se siguen subiendo (como por ejemplo seria que al volver a subir los datos a la tabla programación académica no se haga un foreign key reverenciando al rut de los profesores).

**Comment by ypne** [comment]
La nueva tabla de profesores está en la otra base de datos, actúen segun su modelo

**Comment by ypne** [comment]
actuien en consecuencia con su modelo
