### ISSUE TITLE
tabla profesores

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#258]
Se pide que se borre la tabla profesores actualmente subida y luego haciendo uso de una conexión con el servidor e3profesores se modifique a partir de la tabla de profesores subida en el servidor e3profesores la tabla personas. Sin embargo hay otros atributos que están en la tabla de profesores subida en el servidor e3profesores que no van en la tabla personas y que al menos nosotros como grupo lo teníamos en en la tabla profesores, como serían los datos correspondientes al grado académico, contrato, jornada, dedicación ya que estos datos no son de todas las personas y son simplemente de profesores. 
Entonces ¿tenemos que igual crear una nueva tabla de profesores, subiendo los datos correspondientes a los profesores a través de esta conexión o solo los datos perteneciente a la tabla persona? Como se menciona, hay datos de la tabla de profesores a los que nos vamos a conectar, que si es que se ponen los que se piden en nuestro esquema de nuestra tabla de personas se van a perder simplemente. 
Además, ¿si dejamos solo la tabla personas en nuestro servidor, entonces borramos la tabla profesores del esquema? En ese caso perdemos esos datos exclusivos de los profesores como son grado académico, contrato, jornada, dedicación, etc.

**Comment by ypne** [comment]
no deben crear juna nueva tyabla de profesores, debe subir a la tabla personas los nuevos datos de la tabla de profesores
