### ISSUE TITLE
Eliminar atributos referidos a profesores y jerarquias

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#259]
En el punto 2 se menciona “borre del esquema las tablas de Profesores y Jerarquías, además de todos los atributos que se refieren a ellas en cualquier tabla, excepto los indispensables para funcionar”, pero tenemos duda de qué pasa por ejemplo con el RUT de los profesores que están en la programación académica, en donde se pide este que es una llave foránea y por lo mismo es en teoría indispensable para funcionar, entonces obviamente si se borra del esquema la tabla profesores entonces se pierde toda la información relacionada. También nos gustaría entender mejor a qué se refiere con eliminarla del esquema, y cuando se menciona de borrar todos los atributos que se refiere a ella en cualquier tabla si también se refiere a borrar tablas que no sean indispensables para el esquema, como podría ser borrar la tabla administrativos, ciclos, jerarquías, etc.

**Comment by ypne** [comment]
es parte del problema
