### ISSUE TITLE
Formato de datos: Bloqueo

### ISSUE THREAD

**Issue by jcdo** [IIC2413/Syllabus-2024-2#26]
Según el enunciado de la tarea, es necesario verificar y ajustar el formato de los datos. Actualmente, todos los datos se encuentran en formato "string", por lo que entiendo que deben convertirse al tipo de dato correspondiente.

Tengo una duda específica con respecto al dato "Bloqueo". Este valor debería ser un booleano, pero en el archivo aparece como el string "N". ¿A qué valor booleano debería asociarse este string? Además, ¿debo realizar la conversión y tratar el dato como un booleano, o mantenerlo en su formato original como "N"?

**Comment by TomasKetterer** [comment]
El valor de bloqueo puede ser S/N. No es necesario que hagas la conversión a True o False, ya que con el string basta (de todos modos es un booleano ya que es como 0 o 1). Mantenlo en su formato original. S representa a Sí y N representa a No.
