### ISSUE TITLE
Punto 4 Inciso 4 - Duda SELECT TABLAS...

### ISSUE THREAD

**Issue by Benjamin-Ch** [IIC2413/Syllabus-2024-2#260]
Hola
En el enunciado
"Construya una interfaz donde se puedan ingresar los textos de A,T,C y ejecute la consulta SELECT A FROM T WHERE C donde A es un conjunto de atributos de las tablas T..."

1. Se da a entender que el usuario pueda seleccionar múltiples tablas en la query, ¿es esto asi, tiene algún limite? o es solamente una?

2. Dado el caso, para realizar la consulta es necesario hacer "JOINS" o simplemente concadenar las tablas?

3. En el caso de JOIN, por ejemplo:
SELECT A^n FROM T1 JOIN T2 ON T1.columna = T2.columna...
¿Debo verificar que las columnas en cada tabla coincidan para realizar el JOIN? Y si no fuera el caso, proyectar un mensaje de error?

Gracias.

**Comment by SSParzival** [comment]
Mi grupo tiene la misma interrogante.

**Comment by Utmite** [comment]
En mi grupo tenemos la misma duda ahora, pues el sistema que estamos haciendo es de una tabla

**Comment by ypne** [comment]
1.- no
2.- es parte del problema
3.- esa consulta está mal estrtucturada
