### ISSUE TITLE
Notas

### ISSUE THREAD

**Issue by Ilancf** [IIC2413/Syllabus-2024-2#261]
Con mi grupo tenemos duda de las convocatorias, ya que según las reglas del juego se puede tener 2 convocatorias, pero en las notas que venian desde la entrega pasada hay convocatorias distintas a las que se mencionan en las reglas, un ejemplo es el de la siguiente imagen:
<img width="548" alt="Screenshot 2024-11-10 at 22 29 20" src="https://github.com/user-attachments/assets/b4c74511-9764-48dc-af80-963ea5e5d2f6">
Según las reglas solo puede tener 1 o 2 oportunidades, entonces no sabemos como manejarlo, para la entrega pasada decidimos dejar todas las convocatorias para no perder información. Pero ahora por lo que entendemos en acta debemos dejar los datos sin la convocatoria y solo la nota final (perdiendo información) cierto?
Y luego en la tabla de notas tambien debemos borrar las notas que no corresponde y dejar solo la finales de la convocatoria correspondiente y eliminar la el atributo convocatoria cierto?

Es por esto que si estamos entendiendo bien le pedimos que nos aclara todas las posibles combinaciones de convocatorias correctas posibles para dejar solo las notas finales (entendiendo que se espera que borremos las notas de las convocatorias que no son las finales, perdiendo la informacion de las convocatorias pasadas).

**Comment by ypne** [comment]
es parte del problema

**Comment by Ilancf** [comment]
Esque en el punto 2 de las reglas de negocio, solo se habla de 2 oportunidades y de las siguientes oportunidades: ”JUL” - ”AGO”, ”DIC” - ”MAR”. Pero al uno ver los datos de la entrega pasada para dejar solo las notas. finales ve muchas mas convocatorias. Entonces, creo que falta aclarar que hacer con esas otras convocatorias para dejar solo la nota final y poder dejar todas las notas en el mismo formato, porque o sino lo que pensamos hacer es asumir que las unicas convocatorias validas son ”JUL” - ”AGO”, ”DIC” - ”MAR” y todas las otras eliminarlas por la falta de información, pero no creemos que sea lo correcto (ya que siempre comentan de no eliminar los datos).

**Comment by ypne** [comment]
elarchivo de datos que estan mostrando no es el de la etaba 3
