### ISSUE TITLE
Contraseña para conectar a la base de datos "profesores"

### ISSUE THREAD

**Issue by anticarasosman** [IIC2413/Syllabus-2024-2#263]
Hola disculpa, estoy intentando conectarme a la base de datos para actualizar la tabla de personas con los contenidos de la tabla "profesores", actualmente estoy haciendo el siguiente connect:
![image](https://github.com/user-attachments/assets/102088af-ae07-4f9d-a8b0-547b7c5c6f23)
Estoy 100% seguro que la contraseña es la que creamos al conectarnos por primera ves a la base de datos pero incluso cambiando el usuario a "grupo49e3" o "grupo49e3@bdd1.ing.puc.cl" siempre me sale el siguiente error:
![image](https://github.com/user-attachments/assets/caa74e28-8fc9-4c07-aa9a-b55937ab6a8a)

**Comment by anticarasosman** [comment]
Disculpa, ya lo soluciones, si alguien esta teniendo el mismo problema, en el README del servidor BDD, justo al final sale lo que uno debe poner en el pg_connect.

**Comment by Mateodlcc** [comment]
El user debiese ser grupo49e3 sin el @bdd1. Si aún cambiando el user no les funciona está raro. Dónde está probando hacer la conexión, dentro del server? 
Les funciona la conexión a su propia bdd?

**Comment by anticarasosman** [comment]
> El user debiese ser grupo49e3 sin el @BDD1. Si aún cambiando el user no les funciona está raro. Dónde está probando hacer la conexión, dentro del server? Les funciona la conexión a su propia bdd?

El usuario lo probamos con y sin el @BDD1, también intentamos agregar ".puc.uc.cl" con el mismo resultado. Estamos probando hacer la conexión al server desde un archivo php que esta ubicado en nuestra carpeta de la app Bananer.

**Comment by Mateodlcc** [comment]
Ese archivo está en su computador o dentro del servidor? 
Y repito la pregunta anterior, pudieron conectarse a su propia BDD? intenten con dbname=grupo49e3.

**Comment by anticarasosman** [comment]
Perdón, se me fue responder lo ultimo, el archivo esta en mi computador y si, si somo capaces de conectarnos a nuestra propia BDD.

**Comment by Mateodlcc** [comment]
Ya, el problema debería estar en el hecho de que tu computador no tiene la bdd e3profesores, intenta correr ese mismo archivo desde el servidor. Cuando digo conexión a su propia BDD me refiero a intentar de la misma manera que lo haces ahora. O sea, en el mismo archivo, en lugar de utilizar dbname=e3profesores intenta con dbname=grupo49e3. Lo anterior, si estás trabajando en tu computador y no en el servidor, debería entregar el mismo error a menos que tengas una bdd con ese nombre de forma local.

**Comment by anticarasosman** [comment]
Efectivamente entrega el mismo error cuando cambio el dbname a "grupo49e3"¿como puedo trabajar desde el servidor?

**Comment by Mateodlcc** [comment]
Intenta subiendo los archivos al servidor y revisando si se realiza correctamente la conexión

**Comment by anticarasosman** [comment]
> Intenta subiendo los archivos al servidor y revisando si se realiza correctamente la conexión

Perdona pero ¿como hago eso? Te refieres a subir los archvios por filezilla?

**Comment by Mateodlcc** [comment]
Una opción válida es subirlos a través de FileZilla
