### ISSUE TITLE
Inciso 3

### ISSUE THREAD

**Issue by vicenterodas** [IIC2413/Syllabus-2024-2#264]
Hola, tengo una duda en el punto 3.
El enunciado  menciona **Haciendo uso de esta conexion modifique, a partir de la tabla de profesores, los valores de los atributos correspondientes en la tabla Personas.**

Pero mis columnas en ambas tablas son diferentes (solo se repite RUN y nombre) entonces no entiendo qué debo actualizar.
O se se refiere a que debo agregar las columnas de la tabla profesores a la tabla personas, y para los profesores colocar esos datos. O que debo insertar nuevos profesores en la tabla personas que antes no tenía. 

Gracias

**Comment by pedrojohnson1** [comment]
Me sumo a la pregunta!

**Comment by martintuset** [comment]
Aca estamos igual

**Comment by Mateodlcc** [comment]
Podrías indicar que contienen cada una de las tablas que estás comparando por favor?
(La nueva tabla de profesores y tu tabla de personas).
