### ISSUE TITLE
Tabla profesores

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#265]
En la tabla profesores de la base de datos de mi grupo, se pide que sea borrada, por lo tanto después está simplemente no existirá?, esto me causa confusión ya que si mantenemos lo de la entrega 2 necesitamos información de los profesores.

también en la tabla de jerarquía está no la teníamos para la entrega 2, que hacemos en ese caso? Nada o tenemos q crearla y borrarla

**Comment by Mateodlcc** [comment]
Más arriba en el enunciado dice:
"En esta ocasión, a diferencia de la etapa anterior, hay conexión a una base de datos externa donde residen los datos de los profesores. Por lo que su grupo deberá eliminar la tablas de Profesores y Jerarquías de su base de datos, modificar el modelo si corresponde y hacer uso de una conexión a esa base para las transacciones que se indican."

Por tanto, lo que deben hacer es eliminar las 2 tablas si es que existen en la BDD de la E2 y establecer una conexión a las nuevas BDD externas que les son proporcionadas.
