### ISSUE TITLE
Inserción de Notas en la Tabla: Consideraciones para el Trigger

### ISSUE THREAD

**Issue by vicntealonso** [IIC2413/Syllabus-2024-2#266]
Cuando se tiene el acta, ¿el trigger debe insertar las notas en una nueva tabla exclusiva para las notas del semestre 2024-02, o debería insertarlas en la tabla de notas existente, que contiene todas las notas de los semestres anteriores?

**Comment by Mateodlcc** [comment]
Debería insertarlas en la tabla de notas existente
