### ISSUE TITLE
Duda Stored Procedure 

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#267]
Estimados,

No entiendo qué es lo que tiene que realizar el Stored Procedure del punto 4.2, porque parece que la frase se interrumpió antes de concluir. La frase en cuestión es:
"Construya un Stored Procedure (1pt) que al final de la carga de las notas del curso a la tabla termporal ”acta”. Despliegue una Vista (1pt) con el acta de notas (en una ventana)..." El Stored Procedure debe desplegar la vista, o crearla, o realizar alguna otra cosa? Porque el punto 4.1 habla acerca de comprobar que los datos cumplan con las restricciones de negocio, entonces eso ya debería estar listo, y no sé qué debe hacer este stored procedure...

Muchas gracias de antemano.

**Comment by Mateodlcc** [comment]
El Stored procedure Carga las notas de la tabla temporal "acta" a la tabla de notas general. Luego, para la siguiente parte, el trigger debe además, calcular la calificación.

**Comment by rosarioguerreror** [comment]
Si nosotros para la entrega pasada dejamos la tabla de notas general como historial academico, que incluye la columna convocatoria, como podriamos agregar las tuplas nuevas si en la tabla acta no esta la convocatoria?

**Comment by Mateodlcc** [comment]
Es un problema que deben resolver como grupo, podrían o crear la tabla de notas reestructurando su esquema, o manejar estos casos de alguna manera particular. De todas maneras recuerden mencionarlo en el informe.

**Comment by josefa00** [comment]
Hola me queda la duda ya que si hago primero el  Stored procedure y un alumno tiene una nota para la convocatoria de diciembre y otra para la de marzo entonces estaría agregando a una misma personas dos veces a la tabla del historial académico lo que esta mal. ¿Entonces no debería primero hacer el trigger para decidir que calficacion dejar? Ademas si el acta tiene asociado dos calificaciones, ¿No debería crear otra tabla para insertarla en Historial Académico para que cumpla el formato de esta tabla?

**Comment by Mateodlcc** [comment]
Lo importante es cumplir con lo solicitado, si te parece mejor hacer el trigger y luego finalizar la stored procedure (insertar el acta en la tabla oficial) es válido siempre y cuando justifiques el porque. La misma idea aplica para la segunda pregunta.

**Comment by FelipeFuentesG** [comment]
Hola! Me confundió un poco cuando dijiste que el Stored Procedure debe cargar las notas de la tabla Acta a la tabla de Notas general, ya que el enunciado no dice eso. El enunciado dice que el Stored Procedure debe crear un vista de la tabla temporal acta con los atributos válidos, entonces no entiendo en qué parte se deben cargar las notas del acta a la tabla de notas ¿Lo debe hacer el mismo trigger solicitado?

**Comment by ypne** [comment]
Objetivos del punto 4
1.- crear una transacción begin tensaccion - commit  que cree el DDL desde PHP una TEMP TABLE y cargue los datos. El efecto de esto es que si hay un error la tranzacción completa se deshace (Undo/redo)
2.- el stored proceduree debe crear al final de la transaccion anterior una VIEW (no tabla) con los atributos alumno, curso, periodo, nombre del estudiante, nombre del profesor, la nota final  (no cada convocatoria) y la despliegue en una ventana de bananer
3.-contruya un trigger que al insertar las notas desde el csv (punto 1 ) calcule la calificacion a partir de las totas (las calificaciones calculadas se insertan en la tabla NOTAS)

si les es más facil pueden asumir que que el punto 3 se hace en conjunto con el 1, pero no es necesario.
espero que les quede claro de esta forma

**Comment by josefa00** [comment]
No entiendo si son dos stored procedures porque al principio de este issue sale que "El Stored procedure Carga las notas de la tabla temporal "acta" a la tabla de notas general" pero después se dice que "stored proceduree debe crear al final de la transaccion anterior una VIEW" entonces no entiendo cual de estas dos funciones cumple o si son dos stored procedures separados?
