### ISSUE TITLE
E3 dada E2

### ISSUE THREAD

**Issue by vicntealonso** [IIC2413/Syllabus-2024-2#268]
Se menciona que debemos utilizar todo lo de la entrega 2, pero si tenemos algún error, ¿será evaluado nuevamente?. Mi consulta surge por la necesidad de organizar la separación del trabajo, no para disminuir la carga de la entrega. ¿Existe un puntaje específico para los elementos de la entrega anterior, o el puntaje indicado en el enunciado para cada parte es el puntaje total?

**Comment by ypne** [comment]
al final de la E2 deben tener al menor los datos cargados correctamento, si hay algun error   que no influya en la e3 no se evalúa nuevamentge

**Comment by josefa00** [comment]
Hola nuestro cargador es muy largo por lo tanto en comentarios de la E2 se nos puso "No funciona correctamente el cargador" no se porque no funciona entonces dado que esta es la E3 se penalizara por esto?
