### ISSUE TITLE
Trigger

### ISSUE THREAD

**Issue by vicentekrebs** [IIC2413/Syllabus-2024-2#269]
Hola! Una duda. Al calcular las calificaciones de las notas mediante el trigger, no se puede obtener para insertar en la tabla de Notas cuando las calificaciones son EX, A, R, dado que el acta lo único que proporciona en cuanto a eso es la nota final o los casos donde esta es NP o P. Qué se hace entonces?

**Comment by Mateodlcc** [comment]
Este es uno de los desafíos del proyecto. Busquen una solución que les simplifique la tarea (pero que les permita llevarla a cabo) y recuerden argumentar aquella propuesta en el informe.
