### ISSUE TITLE
Duda PPS

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#27]
Hola, buenas tardes:

En relación con el archivo 1, las filas 4 y 39 sugieren que la misma persona tomó dos secciones del mismo curso en el mismo semestre, obteniendo un promedio de 3.5 en una sección y 4 en la otra. ¿Al calcular el PPS, se consideran ambas secciones o se elimina alguna de las dos?

Muchas gracias.

**Comment by Mateodlcc** [comment]
Lo normal sería considerar ambas notas, pero si lo que te hace mas sentido es eliminar una, tienes la libertad de hacerlo siempre y cuando justifiques tu decisión en el informe.
