### ISSUE TITLE
Acta de notas: "curso"

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#270]
Hola! en el acta de notas dice que se deben poner "número de alumno, curso, periodo, nombre del estudiante, nombre del profesor y la nota final", con curso se refiere a poner la sigla o el nombre del curso? y, sería el mismo para todas las tuplas (todas serían de Adivinación I)?

Gracias de antemano:)

**Comment by Mateodlcc** [comment]
Para evitar redundancia (BCNF), agrega únicamente uno de los dos, con el cual puedas identificar el curso. La idea es que sea escalabale para otros cursos pero si, dado que la información es de Adivinación I, todo diría lo mismo.
