### ISSUE TITLE
Regla de negocio

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#271]
El enunciado, al final de la parte de reglas de negocio, aparece: "Si un estudiante tiene nota de presentación a examen ¡= a 3.0; no tiene primera oportunidad y solo segunda", lo que no entiendo muy bien qué quiere decir con lo de ¡= 3.0 (me imagino que es un error de tipeo), agradecería si me lo explican con otras palabras. Además, no entiendo cómo podría obtener la nota de presentación si solo tengo las notas de las convocatorias.

**Comment by ypne** [comment]
<=

**Comment by coniverav** [comment]
cómo podría obtener la nota de presentación si solo tengo las notas de las convocatorias?

**Comment by pedrojohnson1** [comment]
Me sumo a la pregunta. No entiendo a que se refiere en el enunciado acerca de la nota de presentación, ya que nunca se especifica nada de esta y asumen que es un dato conocido. Feliz si se podría aclarar por favor.

**Comment by SSParzival** [comment]
No concuerdo, debería ser <> a 3.0.

**Comment by LudwigUC** [comment]
> Me sumo a la pregunta. No entiendo a que se refiere en el enunciado acerca de la nota de presentación, ya que nunca se especifica nada de esta y asumen que es un dato conocido. Feliz si se podría aclarar por favor.

Me sumo a la cadena. ¿Podrían responder esto por favor?

**Comment by ypne** [comment]
Estimados
La redacción de la regla está en términos de un reglamento de calificación, por lo que los datos del dataset se apegan a dicha norma. La tarea del ingeniero que está haciendo el sistema es interpretar la norma, escrita probablemente por un especialista en normas y no datos, y compatibilizarlo con lo que se encuentra en los datos. En este entendido les explico _in extenso_ la siguiente interpretación:

Primero una pregunta específica
1:"¿Cómo podemos saber cuales tienen una oportunidad y cuales 2?"
R: En el registro de la tabla Notas y las notas del curso se especifica la fecha de convocatoria, algunos cursos tendrán solo un registro, por ejemplo "DIC" y otros dos "DIC" y "MAR" eso indica si dicho curso tiene una o dos convocatorias. 

Ahora sobre nota de presentacion y otros temas:
2: Sobre las notas del curso:
La regla dice que las notas permitidas en la lista del curso son  desde 1.0 a 7.0 +P+NP+nulo o vacío
<img width="523" alt="image" src="https://github.com/user-attachments/assets/77648f10-0bd9-446c-9f9d-d5e6bc8a6e94">

3: Sobre la convocatoria
a) Si un curso tiene 1 convocatoria, (ver punto 1 anterior) solo aparecerá un registro de convocatoria en las tablas de Notas y en la lista notas del curso, por lo que la regla nota de presentación>=3.0 no se aplica (solo es válida para los cursos con 2 convocatorias).
<img width="755" alt="image" src="https://github.com/user-attachments/assets/3e8e12cc-7012-45f6-ac58-cb6c46ec7077">
Dicho sea de paso, todos los alumnos tienen valor en la primera convocatoria, por lo que nota de presentacion>=3.0 para todos

4.- Respecto a la aprobación (para el acta de notas)
Si el caso es que el estudiante:
a)  aprueba (nota>=4,0) en la primera convocatoria, no tiene una segunda" porque ya aprobó el curso. Por ejemplo, en el siguiente registro:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/d910ac17-4867-4510-b09b-524db52fe424">
y su nota final del acta será la nota de esa aprobatoria de la primera convocatoria.

b) reprueba en la primera convocatoria y la segunda es vacía, significa que se quedó con su nota reprobatoria y no rindió la segunda. Por ejemplo en el registro 
<img width="714" alt="image" src="https://github.com/user-attachments/assets/9c2e6660-e171-45ee-a94b-67f37d172724">
Y su nota final sería la de la primera convocatoria (nota NP es válida solo para la primera convocatoria (punto 2)

c) reprobó la primera convocatoria y aprobó la segunda, quiere decir que SI tenía nota de presentacion >=3.0 y la nota final del acta será la de la segunda convocatoria. 
<img width="717" alt="image" src="https://github.com/user-attachments/assets/d628fb3b-0152-412b-bc3d-f00574a7b2ea">

d) reprobó ambas convocatorias, reprobó el curso con la nota final de la segunda convocatoria

e) tiene nota NP en la primera y nota en la segunda significa que no se presentó en la primera y la nota final será la segunda

5.- Casos especiales:
Existen  casos especiales más allá del tema de la nota de presentación
a) notas P y NP, por punto 2, son notas válldas en el contexto de la lista de notas del curso, para efectos de la tabla Notas y (por la tabla de las Calificaciones) la calificación sería P o NP  respectivamente y nota vacía.

b) La nota NP solo aplica en la primera convocatoria, por lo que si el estudiante tuviera un NP en la _segunda_ convocatoria no sería una nota válida, lo que no es el caso de la lista entregada.  

c) Si tiene nota aprobatoria en la primera y también en la segunda convocatoria es un registro erróneo
<img width="734" alt="image" src="https://github.com/user-attachments/assets/fb037e1a-6eb5-438e-b483-64347a9a8b92">

Como pueden ver, conocer la nota de presentación no es necesaria para implementar.
Espero que sea de ayuda.
Saludos
