### ISSUE TITLE
Punto 4 Vista

### ISSUE THREAD

**Issue by SSParzival** [IIC2413/Syllabus-2024-2#272]
Cuando se refiere a esto: Despliegue una Vista (1pt) con el acta de notas (en una ventana). ¿Se refiere a desplegar la vista en consola, o en página web?

**Comment by Utmite** [comment]
Misma duda

**Comment by Mateodlcc** [comment]
Se refiere a desplegarlo en la página web

**Comment by josefa00** [comment]
Se desplegaría con algún boton en especial o solo cuando se haga una consulta relacionada a las notas?

**Comment by Mateodlcc** [comment]
Queda a su criterio el cómo llegar a cumplir con lo solicitado
