### ISSUE TITLE
Duda aplicación Bananer e inicio de sesión

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2413/Syllabus-2024-2#273]
Hola! En la entrega anterior la aplicación web Bananer contenía un inicio de sesión, en donde se debían registrar usuarios que fueran profesores o administrativos. Mi duda es que, ahora que hay que borrar la tabla de docentes de nuestra base de datos, ¿cómo funciona el inicio de sesión? A partir de esto, ¿Hay que usar la aplicación bananer de la entrega anterior? ¿o sólo debemos desarrollar las funciones y la interfaz gráfica mencionadas en el enunciado de la entrega 3?

**Comment by Mateodlcc** [comment]
Deberían ser capaces de implementar las mismas funcionalidades con las tablas provistas de la bdd e3profesores.
Ustedes tienen la libertad de basar su entrega actual en la anterior implementando las nuevas funcionalidades y modificando las anteriores.

**Comment by ignanuyens** [comment]
Una pregunta con lo anterior. Nosotros no estamos considerando ahora que debemos iniciar sesión ya que el enunciado no lo pide, lo mismo que las consultas. Supongo que también tenemos esa libertad de ahora no iniciar sesión.

**Comment by FelipeFuentesG** [comment]
Entiendo, muchas gracias. Eso sí, tengo otra duda respecto a esto. ¿Podemos tener en una tabla en nuestra bdd los docentes que son usuarios de bananer? Para así solamente tener que conectarnos a la base de profesores cuando se registre un usuario y no tener que hacerlo para iniciar sesión una vez esté registrado. Mi duda también es porque se nos pide no tener información de los docentes en nuestras tablas.

**Comment by Mateodlcc** [comment]
Si bien lo que planteas es mas sencillo, lo que se pretende evaluar es justamente que sean capaces de manejar las conexiones a diferentes BDD, por lo tanto no sería pertinente tener una tabla de docentes en su propia bdd.

**Comment by FelipeFuentesG** [comment]
Claro claro, entiendo. ¿Entonces lo más correcto es tener que conectarnos a la bdd de docentes cada vez que se inicia sesión? De todas formas, ¿en ese caso pierde sentido tener que registrar a nuevos usuarios no?

**Comment by Mateodlcc** [comment]
La respuesta a la primera parte es si, y a la segunda depende de como se realicé dicho registro.

**Comment by ignanuyens** [comment]
Pero el registro de los usuarios no se puede hacer con una tabla?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Mateodlcc ***@***.***>
Enviado: Wednesday, November 13, 2024 12:14:25 PM
Para: IIC2413/Syllabus-2024-2 ***@***.***>
Cc: Ignacia Nuyens Gotelli ***@***.***>; Comment ***@***.***>
Asunto: Re: [IIC2413/Syllabus-2024-2] Duda aplicación Bananer e inicio de sesión (Issue #273)


La respuesta a la primera parte es si, y a la segunda depende de como se realicé dicho registro.

**Comment by ignanuyens** [comment]
Pero el registro de usuarios no se puede hacer en una tabla??

**Comment by FelipeFuentesG** [comment]
Me suma a esa duda, porque usar una tabla para guardar los usuarios registrados es bastante útil, si no, no se podría distinguir si un usuario está registrado o no (aunque sea un docente válido)

**Comment by Mateodlcc** [comment]
Si, siempre y cuando cumplan con las restricciones de la entrega, por ejemplo, mantener el modelo y esquema en BCNF/3NF.

**Comment by Mateodlcc** [comment]
Tendrías que guardar la información (claves) en alguna otra tabla, la cual, si no es equivalente a la tabla de usuarios, probablemente genere problemas de BCNF/3NF.

**Comment by ignanuyens** [comment]
Claro pero ahí tendría una tabla de usuarios, la cual la idea es no tenerla (según entendí con las respuestas anteriores). Por eso no sabría cómo hacerlo sin crear ninguna tabla de usuarios, saber cuál es la clave.
Muchas gracias

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Mateodlcc ***@***.***>
Enviado: Thursday, November 14, 2024 8:35:34 AM
Para: IIC2413/Syllabus-2024-2 ***@***.***>
Cc: Ignacia Nuyens Gotelli ***@***.***>; Comment ***@***.***>
Asunto: Re: [IIC2413/Syllabus-2024-2] Duda aplicación Bananer e inicio de sesión (Issue #273)


Tendrías que guardar la información (claves) en alguna otra tabla, la cual, si no es equivalente a la tabla de usuarios, probablemente genere problemas de BCNF/3NF.

**Comment by ignanuyens** [comment]
Entiendo, entonces el problema está en que yo no puedo pasar la tabla de profesores a mi base de datos, pero si puedo después de que inició sesión, guardar su Mail en una tabla de usuarios con su clave?? Pero conectándome a la base de datos de profesores
Gracias por la ayuda

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Mateodlcc ***@***.***>
Enviado: Thursday, November 14, 2024 10:26:49 AM
Para: IIC2413/Syllabus-2024-2 ***@***.***>
Cc: Ignacia Nuyens Gotelli ***@***.***>; Comment ***@***.***>
Asunto: Re: [IIC2413/Syllabus-2024-2] Duda aplicación Bananer e inicio de sesión (Issue #273)


No hay problema con tener una tabla de usuarios, es lo ideal
