### ISSUE TITLE
Duda enunciado P2 'Borrar excepto indispensable'

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#274]
Hola! Tengo una duda con el enunciado: 'Borre del esquema las tablas de Profesores y Jerarquías, además de todos los atributos que se refieren a ellas en cualquier tabla, excepto los indispensables para funcionar (por ejemplo, personas).'

Entiendo que se deben eliminar las tablas 'Profesores' y 'Jerarquías', además se deben eliminar todos los atributos de otras tablas que hagan referencia a estas tablas, sin embargo, dan como ejemplo 'personas' en donde esta, al ser una tabla y no un atributo, me genera confusión. ¿Es un error y se referían a algún atributo como nombre profesor? O hay algo que estoy entendiendo mal. Muchas gracias.

**Comment by Mateodlcc** [comment]
Lo que deben hacer es eliminar las tablas de profesores y jerarquías. Esto va a depender de como ustedes modelaron su esquema, por tanto se solicita que se elimine toda información relacionada a estas tablas. Cuando se habla de dejar la tabla de personas, se pretende que ustedes mantengan en su bdd todas las relaciones que establezcan los diferentes usuarios de la aplicación, sin embargo la información acerca de los profesores será provista por una bdd externa.
