### ISSUE TITLE
Duda E3

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#275]
Hola! En la E3 se evaluara que la E2 funcione bien también o no?

**Comment by Mateodlcc** [comment]
En la E2 se evaluará todo lo que se solicita en el enunciado. Naturalmente, se solicita el esquema relacional y modelo E/R actualizados, o aspectos en esa línea, de modo que, deben actualizar, y ojalá mejorar su entrega anterior para la actual, pero insisto, será evaluado lo solicitado para esta entrega. (Si la duda va orientada a la página web, se menciona la ampliación de esta, pero en principio no se deberían evaluar las consultas anteriores. De todas formas, es buena práctica arreglar los errores anteriores.)

**Comment by josefa00** [comment]
muchas gracias! se subirá una pauta del modelo E/R?

**Comment by Mateodlcc** [comment]
En principio no, ya que la idea es que vayan iterando sobre su propio esquema y resolviendo errores. No debería evaluarse el cargador por lo que recomiendo dejar los datos cargados al subir la entrega y que no hayan errores asociados a la falta de datos.

**Comment by josefa00** [comment]
pero según nuestra retroalimentación nuestros datos están mal cargados; entonces quizás si hayan errores asociados a la falta de datos. ¿Que hacemos?

**Comment by Mateodlcc** [comment]
Deberían lograr cargar al menos los datos suficientes como para que se les pueda evaluar su entrega 3
