### ISSUE TITLE
Duda esquema y bloqueo E3

### ISSUE THREAD

**Issue by AmarantaB** [IIC2413/Syllabus-2024-2#276]
Estimados, en la E2 se nos corrigió que nuestro esquema no cumplía la formal normal solicitada ya que causal de bloqueo puede depender de estado bloqueo y nosotros los colocamos juntos en una misma tabla con otro atributo como superllave. En un intento de solucionarlo para esta entrega, pensamos que podíamos solucionarlo creando una tabla aparte de causal y estado, no obstante notamos que para un mismo estado puede haber varias causales (como es el caso de estado S), luego estado no puede ser llave. En tal caso, pensamos que podríamos regularlo al revés, que en la tabla aparte las causales sean las llaves y estados los dependientes (ya que si la causal es sin bloqueo el estado es N y para cualquier otro valor es S). Quisiéramos saber si lo anterior es válido y solucionaría lo que nos corrigieron, ya que al ser una lógica al revés de lo que nos anotó el ayudante nos queda la duda de si está es correcto. Muchas gracias desde ya.

**Comment by ypne** [comment]
en la tabla bloqueo la PK es el motivo del bloqueo no el estado ya que S o N pueden tener muchos motivos
