### ISSUE TITLE
Actualizar Profesores y Agregar Nuevos

### ISSUE THREAD

**Issue by CatalinaBO** [IIC2413/Syllabus-2024-2#277]
Hola! Respecto al punto 3, nos piden que actualicemos los atributos de los profesores en la tabla persona a partir de la nueva base de datos. Al hacer esto, encontramos que en la nueva base de datos hay tuplas que no tienen ninguna coincidencia con los datos antiguos de profesores. Por ende, debemos actualizar los datos de los profesores que tienen algún dato que coincide y agregar los que no tienen coincidencia como nuevos profesores en la tabla persona? o simplemente no agregar a estos nuevos?

**Comment by Mateodlcc** [comment]
Es algo que ustedes deben determinar y justificar.

**Comment by Mateodlcc** [comment]
No logro entender la pregunta
