### ISSUE TITLE
Punto 4: Vista 

### ISSUE THREAD

**Issue by rosarioguerreror** [IIC2413/Syllabus-2024-2#278]
Hola!
No me quedó claro en el enunciado si la vista que debe desplegar el acta de notas en una ventana debe construirse directamente a partir de la tabla temporal acta, o si debemos hacerla de otra forma.

gracias!

**Comment by Mateodlcc** [comment]
Pueden hacerlo con la tabla temporal, o podrían también ir a buscar las notas añadidas en la tabla notas pero esto conlleva un desafío mayor y así como una menor eficiencia. Mi recomendación sería generar la vista con la tabla temporal a modo de visualizar los datos que se insertarán en la tabla notas (algo así como una confirmación visual que tendrá el profesor antes de ingresar las notas al sistema).

**Comment by rosarioguerreror** [comment]
Pero si la vista se hace en base a una tabla temporal, como podríamos hacer que se vea en la pagina web si la vista dejaría de existir cuando se cierre la conexión?

**Comment by elneitans** [comment]
tengo la misma pregunta ;(
