### ISSUE TITLE
Duda consulta A,T,C 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#279]
Hola queria preguntar si es que en las consultas el T será solo una tabla (no permitido hacer join) y la A solo un atributo. Del mismo modo, si es que son únicamente un atributo y una tabla ¿Podría usar un dropdown para asegurarme asi que sean a prueba de errores?

**Comment by Mateodlcc** [comment]
No se puede utilizar un dropdown, la idea es evaluar la capacidad que tienen para evitar inyecciones a su bdd y que se manejen con el concepto de consultas case sensitive/insensitive.
