### ISSUE TITLE
Duda punto 2

### ISSUE THREAD

**Issue by VANCOUVERMATU11** [IIC2413/Syllabus-2024-2#280]
Hola! Leí unas issues anteriores y aún así no me queda claro. Cuando en el punto 2 dice; "Borre del esquema las tablas de Profesores y Jerarquías", esto se refiere a: ¿Actualizar el esquema relacional y el diagrama E/R, borrar la tabla de la base de datos, o borrar los datos contenidos en estas tablas? ¿O solo alguna de esas cosas?

Y por lo que vi en una issue anterior, habría que ocupar las tablas de una base de datos externa. Esa base de datos externa no tiene necesariamente las mismas columnas que la nuestra, entonces deberíamos actualizar a lo que hace referencia algunas tablas nuestras? De esa forma, si es que por ejemplo para una tabla como OfertaAcadémica donde necesito el run del profesor, ¿Ahora mi tabla OfertaAcadémica debe hacer referencia a una tabla externa?

Agradezco su respuesta. Saludos

**Comment by Mateodlcc** [comment]
Respecto a la primera parte, se busca que eliminen las tablas de SU bdd ya que estas vendrán por parte de otra bdd (e3profesores), NO hay que borrarlas del esquema relacional ni del diagrama E/R.

Para responder la 2da parte, la respuesta es que si, deben actualizar su esquema, diagrama y, los valores que se relacionan a profesores y jerarquia en otras tablas deben eliminarlos para luego ser actualizadas con los nuevos valores (provenientes de las tabals externas).
