### ISSUE TITLE
Carga de datos al servidor

### ISSUE THREAD

**Issue by Simon-Cabrera** [IIC2413/Syllabus-2024-2#282]
Hola, tengo un problema al subir los datos de la entrega pasada al servidor. En mi computador la carga de datos se demora 30 segundos pero en servidor me saca y me sale el error de la imagen. Los datos que estoy cargando viene de un archivo .csv que esta sacado del sheet "Notas" del archivo Datos proyecto E2.xlsx. El archivo .csv pesa 86 MB porque tiene 603986 lineas. ¿Como puedo solucionar este error?
![Screenshot 2024-11-13 at 3 41 26 PM](https://github.com/user-attachments/assets/0ad4f50c-a5d7-4338-8972-da4c3a83ea21)

Saludos y gracias de antemano.

**Comment by ypne** [comment]
Los datos de la e2 ya están cargados
