### ISSUE TITLE
Duda tuplas tabla Planeación

### ISSUE THREAD

**Issue by njllanos** [IIC2413/Syllabus-2024-2#283]
Hola! Tengo una duda en cuanto a la parte del enunciado en donde se pide "borre todas las tuplas de la tabla planeación y vuelva a cargarla con los datos entregados".

Para la entrega pasada nuestro grupo no tenía una tabla "planeacion" como tal,  sino que de "Planeación.csv" obtuvimos distintas entidades (tablas) con información particionada de ese excel ("departamentos", "facultad" y "ofertas_academicas"). En ese caso para lo que pide el enunciado habría que borrar las tuplas de esas tres tablas (o solo algunas) o directamente habría que cambiar el modelo para tener una tabla que sea "planeacion".
De antemano muchas gracias

**Comment by Mateodlcc** [comment]
Queda a criterio de ustedes como resolver este caso, una opción válida es eliminar los valores asociados a planeación y actualizar dicha información con la nueva información proporcionada. Ahora, otra opción que podría ser más facil de corregir por lo que podrían ahorrarse problemas es lo último que comentan, creando la tabla planeación. Sea cual sea su decisión recuerden incluirlo en su informe.

**Comment by ypne** [comment]
Mateodlcc tiene razón, actúen en consecuencia con su modelo
