### ISSUE TITLE
¿Qué hace Stored Procedure?

### ISSUE THREAD

**Issue by LUCAS13-ING** [IIC2413/Syllabus-2024-2#284]
Cuando se habla de la creacion del Stored Procedure se dice que:

Construya un Stored Procedure (1pt) que al final de la carga de las notas del curso a la tabla termporal ”acta”. Despliegue una Vista (1pt) con el acta de notas (en una ventana). El acta de notas contiene el número de alumno, curso, periodo, nombre del estudiante, nombre del profesor, la única nota final que es el resultado de la combinación de ambas oportunidades (según las reglas de negocio). Debe validar que existan: el curso, alumno, profesor, que las notas están en el rango correcto, etc.)

Lo que no entiendiendo es si el Stored Procedure debe cargar los datos en la tabla temporal acta o si debe desplegar la vista en base a la tabla. Es un poco confusa la redacción de esta parte.

**Comment by elneitans** [comment]
https://github.com/IIC2413/Syllabus-2024-2/issues/267

**Comment by Mateodlcc** [comment]
Como dijo tu compañero, revisa la issue #267.
