### ISSUE TITLE
agregar profesores a personas

### ISSUE THREAD

**Issue by domingaelton** [IIC2413/Syllabus-2024-2#286]
Hola! Cuando tratamos de agregar los profesores de la tabla entregada a personas, no se puede porque en la tabla personas pusimos restriccion al run si es que tenia menos de 7 digitos. En la tabla de profesores que nos dieron hay varios que tienen un run menor. Podemos alterar el chequeo en la tabla personas? o descartamos a los profesores (que son varios)

**Comment by Mateodlcc** [comment]
Pueden tomar esas decisiones siempre y cuando lo expliquen en el informe para que quien corrija, esté al tanto de los problemas encontrados y soluciones propuestas.

**Comment by ypne** [comment]
Esa regla de que la mantisa del RUN (número antes del DV) no tiene sentido, el RUN es un número serial que al minuto va desde el 1 a más de 25 millones. Conozco gente que camina por la calle con RUN de 6 cifras. levanten esa restriccion
