### ISSUE TITLE
Planeación 

### ISSUE THREAD

**Issue by AgustinSaavedra1** [IIC2413/Syllabus-2024-2#287]
Hola! Aun no me queda claro que se debe hacer con el nuevo archivo de planeacion. Hay que reemplazar el anterior por el nuevo y volver a usar el cargador de datos de la entrega pasada? O de se deben actualizar los datos de otra forma?

**Comment by Mateodlcc** [comment]
Cualquiera que te parezca mas conveniente, pero piensa que debes poder ser capaz de evidenciar que lo hiciste para que los ayudantes puedan corregirte

**Comment by ypne** [comment]
El archivo de planeación anterior tenía violaciones a la IC, se generó este nuevo para que puedan avanzar sin problemas, deben cargarlo (lo que corresponde)
