### ISSUE TITLE
Duda de los nulos

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#29]
Hola,

¿Los datos que no deben ser nulos y que aparecen como nulos en el archivo deben ser reemplazados por "x", o deben ser simplemente ignorados? ¿O queda a mi criterio decidir qué datos ignorar? Por ejemplo, podría optar por no cargar aquellos que tengan el plan de estudios como nulo, pero reemplazar con "x" los datos cuyo último logro esté en nulo.

Muchas gracias y saludos.

**Comment by lucolhabe** [comment]
Hola, deben ser añadidos aplicando el reemplazo por la "x", es decir, no pueden ser ignorados.
