### ISSUE TITLE
Solicitud de extension de plazo entrega 3

### ISSUE THREAD

**Issue by coodysoto12** [IIC2413/Syllabus-2024-2#290]
Si bien comprendemos que los tiempos estimados para las entregas están dimensionados para el esfuerzo de 3 personas para 3 semanas, la entrega de feedback de la E2 llego a inicios de la ultima semana asociada a la entrega 3, lo que deja poco margen de correccion con respecto al proyecto, que no deja de ser base para esta entrega, si bien la proxima semana esta la I2,  la nota proyecto sigue siendo un requisito minimo de aprobacion del curso, por lo que no le resta importancia el tiempo necesario para una entrega apropiada que permita aprobar el curso. Por lo que me gustaria pedir la posibilidad de extender el plazo de la entrega 3.

**Comment by ypne** [comment]
Se extendió

**Comment by LudwigUC** [comment]
Dios, patria y Eduardo Bustos!
