### ISSUE TITLE
Duda conexión a base de datos profesores y bdd.

### ISSUE THREAD

**Issue by vicentekrebs** [IIC2413/Syllabus-2024-2#291]
Por alguna razón al correr este código en un archivo llamado probar_punto_3.php que se encuentra en Grupo43e3/Sites/E3/probar_punto_3.php no funciona la conexión a las bases de datos, pero no entiendo por qué si seguimos al pie de la letra lo que dice el READme del servidor entregado en Canvas. 

// Conexión a la base de datos de destino (personas)
$db = pg_connect("host=localhost port=5432 dbname=grupo43e3 user=grupo43e3 password=nuestra_contraseña");
if (!$db) {
    die("Error en la conexión a la base de datos de personas.\n");
} else {
    echo "Conexión a la base de datos de personas establecida.\n";
}

// Conexión a la base de datos de origen (profesores)
$db_profes = pg_connect("host=localhost port=5432 dbname=e3profesores user=grupo43e3 password=nuestra_contraseña");
if (!$db_profes) {
    die("Error en la conexión a la base de datos de profesores.\n");
} else {
    echo "Conexión a la base de datos de profesores establecida.\n";
}

**Comment by LudwigUC** [comment]
En host tienes que poner: "bdd1.ing.puc.cl"

**Comment by ypne** [comment]
hay 3 formas de hacer el proyecto
1.- solo local en el pc (no recomendada), para lo cual es necesario contar con la base de profesores en el mismo PC y conectarse a localhost (127.0.0.1) como se indicó en la ayudantía y está en el material de la misma
2.- trabajar en el server, que tiene ambas bases, la del grupo y la de profesores donde sigue siendo válido lo de la ayudantía conectarse a localhost (127.0.0.1) 
3.- mixta, donde la base local está en el pc y la de profesores en el server en cuyo caso la base de profesores está en bdd1.ing.puc.cl.
Recuerden que el proyecto se evalúa en el server por lo que todo lo que hagas local debe instalarse en el server y PROBARLO.
