### ISSUE TITLE
tabla temporal acta

### ISSUE THREAD

**Issue by Natitorresg** [IIC2413/Syllabus-2024-2#292]
Hola, la tabla acta puede tener mas atributos de los que aparecen mencionados en el enunciado?.
Tambien tengo una duda sobre que cosas debe hacer el stored procedure,y el trigger. Porque lo que entendimos en el enunciado confunde comparando con las issues. 

Lo que como grupo teniamos entendido al leer la issue267 es que la stored procedure es para cargar la tabla temporal acta en nuestra base de datos, y el trigger para calcular la calificacion. Es asi? porque en la issue 266 se entiende que el trigger deberia cargar nota en nuestra base de datos y eso no aparece en el enunciado. aparece esto  "Construya un Stored Procedure (1pt) que al final de la carga de las notas del curso a la tabla termporal acta". Y sobre trigger sale  "Construya un Trigger que al insertar las notas de la acta en la tabla notas calcule la calificación". 

En los dos parrafos del enunciado al decir "que al" se refiere a que eso sucede antes o a la par del trigger y el stored procedure? o se incluye  lo que deben realizar?.

**Comment by LudwigUC** [comment]
Revisa la issue #267

**Comment by ypne** [comment]
1.- si lo encuentran necesario si
2.- lo de los triggers y sp lo acabo agregar al  https://github.com/IIC2413/Syllabus-2024-2/issues/267
3.- depende del contexto:
en el sp dice:  que al final de la carga de las notas... eso es al final
en el trigger dice que al insertar las notas ... eso es mientras se inserta cada tupla, podrías hacelo al final pero eso son 2 full scan sobre la tabla

espero que les sea util
