### ISSUE TITLE
Llave primaria en entidad con FK

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#293]
Hola!
 Espero se encuentren bien. Esta es una pregunta de materia en general, me quedó la duda dando vueltas y quería ver si me lo podían aclarar aquí.
 Cuando una entidad **tiene una FK** y tiene además un **atributo que permite identificar cada una de las tuplas**, **¿cuál es la llave primaria de dicha entidad?**.
 Estaba pensando en el caso del proyecto por ejemplo, que podría tener la entidad Estudiante que tenga una FK que sea el RUN (de Persona) y además una identificación propia Número de Alumno. **En dicho ejemplo, ¿cuál sería la llave primaria adecuada?** ¿Por qué sería dicha llave una llave apropiada?

Gracias de antemano!

**Comment by ypne** [comment]
Esto es materia de clases de mediados de semestre y de la E2, puedes revisarlo ahí  o en el texto guía

**Comment by ssepul21** [comment]
@ypne Pucha, entiendo que la pregunta igual es media básica (sobre todo porque ya pasamos eso hace tiempo ksksks), pero no me quedó muy claro viendo la pauta de la E2.

Agradecería si pudiese contestar la pregunta directamente 😅🥲. De antemano, gracias ^^

**Comment by VicenteSanMartin** [comment]
Hola! Hay que distinguir entre tipos de llaves. Una llave primaria es un atributo (o conjunto de ellos) que permite identificar de manera única a una tupla. Por otro lado, una llave foránea (FK) es un atributo que hace referencia a un atributo de otra tabla, pudiendo repetirse entre tuplas de la tabla.

Por ejemplo, en el caso que describes, la entidad Estudiante tiene una identificación propia (llave primaria) número de alumno, el cual identifica de manera única a un estudiante pues este nunca se repite. Además, un Estudiante tiene un atributo RUN, el cual hace referencia al atributo RUN de la tabla Persona (por ende, Estudiante.RUN es llave foránea), pero el atributo RUN no es necesariamente único dentro de la entidad Estudiante, ya que dos estudiantes pueden estar asociados a una misma persona (alguien que estudia dos carreras, por ejemplo). Por esto, RUN no es una llave primaria apropiada para la tabla Estudiante, mientras que el número de alumno sí lo es.
