### ISSUE TITLE
Duda enunciado Inciso 3

### ISSUE THREAD

**Issue by VANCOUVERMATU11** [IIC2413/Syllabus-2024-2#294]
Hola! Esto ya se preguntó antes pero quedó inconculuso. En el inciso 3 se menciona: "Haciendo uso de esta conexión modifique,
a partir de la tabla de profesores, los valores de los atributos correspondientes en la tabla Personas." Para la tabla profesores que proveen ustedes solo coincide nombre y run. El resto de columnas son datos que no se nos dieron en entregas pasadas. Qué se supone que debemos hacer entonces? ¿Agregar columnas nuevas con estos datos y rellenarlos si es que coincide el run? ¿O solamente revisar por ejemplo si es que se cambió el nombre y actualizarlo?

Gracias

**Comment by LudwigUC** [comment]
No soy ayudante, pero por lo que entendí, es necesario hacer consultas al resto de tablas disponibles en la base de datos remota "grupoXXe3". De esta manera se va completando la información faltante para actualizar la tabla "Personas".

**Comment by ypne** [comment]
en la tabla profesores de la segunda base de datos hay atributos que según el modelo debieran estar en personas. para que sea consistente con su programa, estos datos debieran estar en personas. Como la tabla de profesores no es de su grupo no se puede tocar por lo qe la alternativa es la presentada, hacer un UPDATE de los atributos correspondientes a los profesores de la base remota en la tabla personas de su grupo.
