### ISSUE TITLE
Duda transaccion

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#295]
Hola, quería saber si para hacer la tabla acta en la transacción se podía crear otra tabla temporar además de esta, para facilitar el proceso?

**Comment by ypne** [comment]
no cumpliría con el enunciado
 
<img width="785" alt="image" src="https://github.com/user-attachments/assets/334d7350-54a4-4040-ac02-53c6e304115b">

**Comment by cataruze** [comment]
Yap gracias, me quedo otra duda de la transacción, para esta al crear la tabla temporal acta debo está solo cargarla con número alumno, curso, periodo, nombre estudiante, nombre profesor y nota, o con todas las columnas del archivo entregado y al hacer la vista solo mostrar los nombrados?
