### ISSUE TITLE
Cosas a instalar

### ISSUE THREAD

**Issue by enzoacvi** [IIC2413/Syllabus-2024-2#3]
Holaa,

He estado buscando si en algún lugar se específica **qué programas o lenguajes debemos instalar**, pero no he encontrado nada. Así que pregunto por aquí dónde puedo encontrar el listado o cuáles son, para comenzar con la instalación de lo necesario para realizar la P0 y las entregas posteriores.

Gracias de antemano😁

PD: no he encontrado cómo poner el label a la issue, no sé si será automático o lo ponen ustedes.

**Comment by TomasKetterer** [comment]
Hola! Ya se subió el manual de instalación de php para windows y mac. Además se requiere que instalen ubuntu y filezilla.

**Comment by enzoacvi** [comment]
Muchas gracias!
