### ISSUE TITLE
Archivo1 Sección numérica

### ISSUE THREAD

**Issue by k0rval4n** [IIC2413/Syllabus-2024-2#30]
¡Hola! Al manejar las entradas del archivo 1, se debe exigir que el atributo de la sección sea entero, o eventualmente podrían ser letras/textos? ¡Muchas gracias!

**Comment by tom4stapia** [comment]
Hola! Según el enunciado, el atributo de las secciones debe ser un entero para esta entrega.

<img width="481" alt="Captura de pantalla 2024-08-13 a la(s) 01 13 10" src="https://github.com/user-attachments/assets/bca7e649-69be-4934-9249-d6ff4815737a">

**Comment by k0rval4n** [comment]
> Hola! Según el enunciado, el atributo de las secciones debe ser un entero para esta entrega.
> 
> <img alt="Captura de pantalla 2024-08-13 a la(s) 01 13 10" width="481" src="https://private-user-images.githubusercontent.com/101529711/357283015-bca7e649-69be-4934-9249-d6ff4815737a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQwMjAsIm5iZiI6MTcyMzU5MzcyMCwicGF0aCI6Ii8xMDE1Mjk3MTEvMzU3MjgzMDE1LWJjYTdlNjQ5LTY5YmUtNDkzNC05MjQ5LWQ2ZmY0ODE1NzM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMDAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWUyNzk3MzUwZGNiMjRkNTlkMmI0MzVjMWQ2OGZkNTE5ODIyM2Q0NzI0MmU0N2U3NWVmNzcyZGQ3YTM5MDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.txP8-IE2fw47qAzM3MgR_bqyTVpb2glX89msimbctVY">

Gracias!
