### ISSUE TITLE
Uso de cursores

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#300]
Hola! 

 Espero se encuentren bien ^^. 
 Estaba leyendo el compilado de Resumen y Ejercicios que está publicado en Canvas, pero no me termina de quedar del todo claro **por qué es bueno utilizar cursores**. Al menos las aplicaciones que muestra en el apunte, me da la idea de que no hace tanta diferencia usar los cursores con respecto a simplemente crear las tablas o hacer las consultas.
 Agradecería si pueden aclararme por qué se usa o cuál es la importancia que tiene aplicarlo.

Saludos! ✌🏻

**Comment by sbarriag** [comment]
Hola, aprovecho de preguntar si cursores será evaluado en la interrogación, porque si bien está en el apunte, no fue visto a detalle en clases

**Comment by VicenteSanMartin** [comment]
Hola! Les comento que cursores **no** será evaluado en la interrogación 2, ya que no fue visto detalladamente.
