### ISSUE TITLE
Duda taller 9 índices

### ISSUE THREAD

**Issue by ignanuyens** [IIC2413/Syllabus-2024-2#302]
Hola, tengo una duda en la pregunta 1, parte III.

Nos piden un factor de carga 1, pero en la solución ponen la función hash como key mod 100, cuando en realidad existen 1000 tuplas.  No me hace sentido que sea así para un factor de carga 1. 

También quería preguntar si efectivamente no existe alguna diferencia al definir un índice clustered con uno unclustered, o bien un índice primario o uno secundario, en el código. 

Muchas gracias de antemano

**Comment by calvarezl-cl** [comment]
Hola

Con respecto a la primera pregunta, un factor de carga 1 significa que todas los buckets de un índice hash o hojas de un B+ tree ya tienen un registro asociado. Por lo tanto al elegir 100 u otro valor que sea menor o igual que 1000 van a estar todos los índices ocupados.

La diferencia entre índices clustered y unclustered es que en clustered en la página del índice (hoja b+ o bucket) están los datos de la tupla y en unclustered los punteros a la página donde están los datos de la tupla. Entonces en menos pasos se encuentra la tupla en índices clustered que unclustered.

Saludos,
CAL

**Comment by ignanuyens** [comment]
Sigo teniendo una duda respecto al factor de carga. Creo que la respuesta me confundió más el concepto. Si me dices que "un factor de carga 1 significa que todas los buckets de un índice hash o hojas de un B+ tree ya tienen un registro asociado", no me calza con la definición que tengo entendida que es factor de carga=numero de tuplas (valores almacenados)/número de buckets (tamaño tabla hash). Por lo tanto, para el ejercicio del taller, si queremos que el factor de carga sea 1, tendríamos que preguntarnos por cuánto tengo que dividir a 1000 tuplas, para que me quede aproximadamente 1 tupla por bucket, lo cual sería 1.000.  En otras palabras, el factor de carga es aproximadamente la cantidad de tuplas que tendré en cada bucket, por lo que si utilizamos mod 100 tendríamos 10 tuplas por bucket, pero el factor de carga sería 10, no 1.
Por eso creo que o la pauta está mal, o yo tengo un error de concepto que me gustaría que me explicara.

Respecto a mi segunda pregunta, entiendo la diferencia de definición y de concepto, mi pregunta era en la definición en código. Ambos se definen como CREATE INDEX nombre ON Tabla(atributo)?? o tengo que hacer una diferenciación si es clustered o unclustered?? Porque la pauta del taller no hace una diferenciación pero no me hace mucho sentido.

Agradezco que expliquen con más detalle por favor. Gracias

**Comment by ypne** [comment]
adicionalmente, según la estructura usada, una tabla de hash puede contener mas de una tupla (factor de bloqueo)

**Comment by ignanuyens** [comment]
Creo que entiendo la primera parte, gracias.

Respecto a la segunda, comprendo la definición y precisamente porque no pueden haber dos índices primario viene mi pregunta porque en taller no hacen una diferencia en la definición de código.
<img width="494" alt="image" src="https://github.com/user-attachments/assets/105e7711-1c16-4885-99d9-549687aaf6ab">

Cómo sabe el código que la segunda es un índice secundario? si es que no se le pone nada extra, a mi parecer los dos simulan ser primarios lo cual no se puede.
Gracias

**Comment by calvarezl-cl** [comment]
Cuando los índices no son primarios, son secundarios. Ambos índices son secundarios, por lo tanto unclustered.

**Comment by ignanuyens** [comment]
Pero en teoría el primer índice era primario porque era para una llave primaria, por lo tanto estaría incorrecto decir que ambos son secundarios. 
Me podría dar un ejemplo de definición entre un índice clustered y uno unclustered por favor? En el formato de código tipo CREATE INDEX....
gracias

**Comment by coniverav** [comment]
quedé con la misma duda

**Comment by calvarezl-cl** [comment]
La sintaxis para crear un índice clustered es la siguiente:

CREATE CLUSTERED INDEX myIndex ON dbo.myTable(myColumn)

Saludos,
CAL
