### ISSUE TITLE
Duda respuestas guías semestres pasados (cátedra)

### ISSUE THREAD

**Issue by ignanuyens** [IIC2413/Syllabus-2024-2#303]
Buen día

Tengo dudas de las respuestas de los ejercicios de los siguientes archivos
[Control 2.pdf](https://github.com/user-attachments/files/17803208/Control.2.pdf)
[Guía 7 - Índices y Algoritmos.pdf](https://github.com/user-attachments/files/17803210/Guia.7.-.Indices.y.Algoritmos.pdf)

Son buenos ejercicios, sin embargo no puedo comprobar mis respuestas y tengo dudas al momento de comparar con otros compañeros. Es fundamental para el estudio contar con las herramientas necesarias para poder aprender, como las pautas de los ejercicios. Les agradecería si por lo menos pueden explicar las respuestas de los ejercicios de costo de I/O con los índices.
Muchas gracias de antemano

**Comment by ssepul21** [comment]
Apoyo la solicitud 🥲

**Comment by nico-larenas** [comment]
Hola,
No tenemos acceso a las pautas de semestres pasados, pero si tienes dudas con algún ejercicio en específico, feliz de responderlas.

**Comment by ignanuyens** [comment]
Agradecería que me explicaran cómo se realizan los 5 primeros ejercicios de la guía de índices y algoritmos, junto con la tercera consulta de la pregunta 1 del control 2.
Muchas gracias

**Comment by coniverav** [comment]
Apoyo la solicitud x2, no entiendo tampoco

**Comment by nico-larenas** [comment]
La respuesta de la 1 del control 2, es:

Se puede hacer un Nested Loop Join con costo: Costo (R) + Tuplas (R) * Costo (S)

**Comment by nico-larenas** [comment]
La Respuesta a la tercera consulta de la pregunta 1 del control 2 es:

Al ser precio > 2000 AND precio < 3000
Aquí usamos el B+ Tree, siendo el costo

h + 1 + x

h = Altura del arbol
1 = página donde están los punteros
x = tuplas que cumplen la condición (< 80)

**Comment by nico-larenas** [comment]
hola, 
te adjunto la pauta oficial del control 2, para que puedas comparar tus respuestas antes de la prueba
[Pauta Control 2.pdf](https://github.com/user-attachments/files/17833359/Pauta.Control.2.pdf)

Puedo revisar tu lógica en un rato, 
Ánimo con el estudio

**Comment by ignanuyens** [comment]
Ya entendí, muchas gracias
