### ISSUE TITLE
Sintaxis Stored Procedure

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#304]
Hola!
 Espero se encuentren bien. Quería consulta por la sintaxis de la stored procedure ya que la guía de ejercicios ocupa una diferente a la que vimos en clase.
 La del apunte ocupa esta:
 ![image](https://github.com/user-attachments/assets/8c843777-9309-40e0-8bf9-678f78362ba7)

Mientras que en clase vimos esta otra
![image](https://github.com/user-attachments/assets/d548ba53-13c2-49f4-9e21-d1bb3bc36aab)

- **¿Con cuál de las dos nos quedamos?**
- **¿En la prueba se nos dará un torpedo o algo por el estilo que tenga la sintaxis de las diferentes sentencias sql?** Ya sea como definir transacciones, triggers o stored procedures.

Gracias de antemano! 😁

**Comment by VicenteSanMartin** [comment]
Hola! Ambas sintaxis son válidas, por lo que ambas serán aceptadas en el contexto de la prueba. En relación a la segunda pregunta, en la prueba se dará un apunte con la sintaxis de ciertas sentencias solo a modo de recordatorio.

**Comment by ssepul21** [comment]
Vale! Muchas gracias
