### ISSUE TITLE
ORM y MongoDB

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#305]
Hola, quería preguntar si es necesario saber de memoria la sintaxis para programar ORM con alguna librería en especial, y si es así cuál. Lo mismo respecto MongoDB, dado que en la clase hay solo una slide de comandos: es esto suficiente para la i2 o es necesario estudiar más? Si es lo segundo, me sería de mucha ayuda saber qué cosas para orientar mi estudio a ello.

Muchas gracias de antemano.

**Comment by VicenteSanMartin** [comment]
Hola! No es necesario saber la sintaxis exacta para ORM con ninguna librería. En relación a MongoDB, con lo visto en clases es suficiente.
