### ISSUE TITLE
Duda examen esquema relacional

### ISSUE THREAD

**Issue by rodrigooflores** [IIC2413/Syllabus-2024-2#307]
Buenas tardes, haciendo la interrogación 1 otra vez me surgieron un par de dudas.

En primer lugar noté que para el esquema relacional utilizan una notación similar a la sintaxis cuando creamos tablas en PostgreSQL, sin embargo en esta no se pueden identificar llaves parciales. Por ejemplo según el diagrama ER de la pauta fecha_recepcion es una llave parcial, pero en el esquema de la pauta aparece lo siguiente:
<img width="1036" alt="esquema_pauta" src="https://github.com/user-attachments/assets/947e37b6-8728-40c8-b65e-fc0eec9e5f29">
Para efectos del examen ¿podríamos combinar ambas sintaxis para indicar las llaves parciales en el esquema?, estaba pensando en hacer algo como esto:
<img width="955" alt="esquema_llave_parcial" src="https://github.com/user-attachments/assets/44b55747-8a3a-408e-a98f-ce4fd1dbf510">

Mi segunda duda es más teórica relacionada a esto también. ¿Afecta en algo considerar un atributo como llave parcial o no para un DBMS como PostgreSQL?

Saludos!

**Comment by VicenteSanMartin** [comment]
Hola! Respecto al tema de la notación de llaves parciales en el esquema, lo que recomiendo, si es que se quiere especificar que un atributo es una llave parcial, es agregar un comentario para aclarar que dicho atributo es una llave parcial.

Respecto a la segunda duda, desde un punto de vista teórico (de un DBMS como PostgreSQL), no afecta el funcionamiento si un atributo no se marca de manera explícita como llave parcial, porque esta idea es del diseño lógico y conceptual (diagrama ER). Para un DBMS, lo importante es que la llave primaria final de la relación débil (compuesta por la llave parcial y la llave primaria de la relación fuerte) esté correctamente definida en el esquema.

**Comment by rodrigooflores** [comment]
Comprendo, muchas gracias!
