### ISSUE TITLE
Columnas no mencionadas en archivo2

### ISSUE THREAD

**Issue by Consolo0** [IIC2413/Syllabus-2024-2#31]
Hola, en el archivo 2 hay tres columnas (Paterno,Materno,Nombres), pero estas no se mencionan en el enunciado. Aun así cuando creamos la matriz Persona y estemos en el archivo 2, agregamos apellido paterno, materno y nombres o se ignoran ya que no fueron mencionados en el enunciado.

**Comment by waldoosg** [comment]
Hola, no se mencionan en el enunciado pero de igual forma se utilizan en la matriz persona. También mantén las columnas al momento de crear el archivo con los datos limpios.
