### ISSUE TITLE
Personas sin cargo ni jerarquia

### ISSUE THREAD

**Issue by Consolo0** [IIC2413/Syllabus-2024-2#32]
Hola,en el archivo 2 en la linea 76 y muchas otras, ocurre que hay personas sin jerarquía ni cargo. En este caso los consideramos como profesores? administrativos? o ambos

**Comment by noamsito** [comment]
Hola, simplemente debes considerarlo como nulo, dado que no incumple con la restricción planteada para esos atributos  (admite nulos).
