### ISSUE TITLE
Limpieza de datos de archivos: Necesidad de limpiarlos todos.

### ISSUE THREAD

**Issue by MathiasPrett** [IIC2413/Syllabus-2024-2#33]
Hola. Tengo una duda respecto a la entrega 0 del proyecto (p0). Se nos pide leer los archivos y entregar las matrices con los datos limpios en matrices. Pero eso implica limpiar TODOS los atributos de los archivos o basta limpiar y mostrar solo aquellos que finalmente se guardan en las matrices?

Pregunto esto porque en el enunciado son muy específicos con las reglas para cada dato que entregan los archivos, pero son solo algunos de estos datos los que se incluyen en las matrices.

gracias :)

**Comment by noamsito** [comment]
Se debe hacer una limpieza de todos los datos, ya que debes de analizar cuales son los errores que presentan y además indicar cual fue la solución utilizada ante estos.

**Comment by MathiasPrett** [comment]
Entiendo. Muchas gracias 🤝
