### ISSUE TITLE
Corectitid del dígito verificador

### ISSUE THREAD

**Issue by Tichi1010** [IIC2413/Syllabus-2024-2#34]
Hola buenas!
Mi duda es, en el archivo 1 cuando revisamos el dígito verificador det rut, podemos asumir que es el correcto? o tenemos que hacer los cálculos con el rut para cerciorarnos que sea el correcto?

**Comment by lucolhabe** [comment]
Hola, no necesariamente sera el DV "correcto" del rut, pero para efectos de la entrega asume que es el indicado ya que no se busca que sea validado o se realicen cálculos.

**Comment by njllanos** [comment]
Hola respecto a esto, ¿Hay que verificar que sea de un digito (o una letra en caso de la k)? En caso de que eso no se cumpla (sea de largo mayor a 1) que se debería hacer?

**Comment by lucolhabe** [comment]
Si habria que verificarlo ya que el DV es solo un caracter, en caso no de cumplir debes elegir como lo solucionas o que hacer respecto al dato, considerando que no puede ser de largo mayor a 1, lo cual deberas dejarlo escrito en el informe.

**Comment by njllanos** [comment]
En caso de que no cumpla, es una solución valida descartar el registro dado que no cumple con las reglas de negocio (que el DV sea de un dígito)? O necesariamente debo alterar su DV para poder contabilizar a esa persona

**Comment by lucolhabe** [comment]
Puedes elegir rechazarlo o cambiarlo por algun caracter que indique que es desconocido. Debes especificar en el informe que decision tomaste.
