### ISSUE TITLE
Duda código externo

### ISSUE THREAD

**Issue by elneitans** [IIC2413/Syllabus-2024-2#37]
Hola a todos. No me quedó claro de las clases si es posible utilizar código externo en la tarea, como por ejemplo de StackOverflow, como en el caso de Programación Avanzada. Si es afirmativo, quería preguntar cómo citarlo.

Muchas gracias de antemano.

**Comment by TomasKetterer** [comment]
Hola! Sí, se puede utilizar código externo, la idea es que aprendan cómo utilizar ese código y cómo funciona. Ideal que lo citen con una línea comentada con el link a la página con el código,
