### ISSUE TITLE
2 RUN con el mismo número de estudiante

### ISSUE THREAD

**Issue by jcdo** [IIC2413/Syllabus-2024-2#38]
Una de las reglas del negocio es:

> Los estudiantes se identifican por RUN o nu ́mero de estudiante. Un RUN puede tener m ́as de un nu ́mero de estudiante, cada vez que la persona entra a primer an ̃o en la universidad se le asigna un nuevo número.

Pero existe el caso que esto no se cumple y que hay 2 estudiantes (RUN) con un mismo número de estudiante, por lo que no me queda claro como hacer la limpieza. ¿Debo descartar todos los registros asociados al número de estudiante en conflicto?

**Comment by Mateodlcc** [comment]
Toma el supuesto que estimes conveniente y mencionalo en el informe. Personalmente recomendaría eliminar uno de los RUN y mantener el resto de la información. Pero si estimas conveniente eliminar toda la información asociada a ese número de estudiante, también puedes hacerlo, siempre y cuando justifiques tus razones.
