### ISSUE TITLE
Duda asistencia ayudantías

### ISSUE THREAD

**Issue by dgolzm** [IIC2413/Syllabus-2024-2#4]
Hola, escribo esta issue ya que en el programa del curso no se hace hincapié respecto a la asistencia a las ayudantías programadas para los días viernes, pero en los últimos módulos se está tomando en cuenta (al menos para la sección 1). Mi duda es, con qué fin es esto? Pregunto ya que en mi caso particular tengo un tope de horario a esa hora, y no soy el único estudiante con un conflicto similar. Es importante mantener el % de asistencia alto a este módulo? (obviando, por supuesto, la utilidad de asistir a ellos por la resolución de consultas).

**Comment by VicenteSanMartin** [comment]
Hola, la asistencia solo se está tomando para mantener un registro del nivel de participación de manera formativa. Esta no afecta de ninguna manera más allá de la utilidad misma de asistir a la ayudantía
