### ISSUE TITLE
Uso Linux 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#40]
Hola, en la entrega 0 estoy perdida con el uso de linux hay que descargar algo?

**Comment by TomasKetterer** [comment]
Hola, como se explicó en la ayudantía del viernes pasado, no es necesario que descarguen nada ya que ubuntu está instalado directamente en el servidor para que puedan utilizar linux

**Comment by josefa00** [comment]
perfecto; lo que no entiendo es como debe ser implementado en esta entrega

**Comment by TomasKetterer** [comment]
Lo principal es php en esta entrega, linux se utilizará para correr sus programas en el servidor. Traten de correr sus códigos cuando los suban al servidor para asegurar que funciona correctamente (esto se hace mediante los comandos enseñados en la ayudantía).
