### ISSUE TITLE
Duda limpieza de datos

### ISSUE THREAD

**Issue by antoer** [IIC2413/Syllabus-2024-2#41]
Hola, no entiendo a que se refiere con esto:
"Si encuentra un error de tipo codificación (Por ejemplo caracter tilde no soportada ”%’a” reemplácelo
por el correcto ”á” en el programa PHP."
Tengo que cambiar cada vocal que lleva tilde?

**Comment by josefa00** [comment]
Hola! No entendí muy bien; si mi archivo (sin modificar nada) se ven correctamente los tildes al imprimirlo entonces no tengo que hacer nada en este ámbito?

**Comment by coniverav** [comment]
Misma pregunta

**Comment by lucolhabe** [comment]
En ese caso no deberias, mientras se logre ver correctamente en la matriz se cumple con el objetivo.
