### ISSUE TITLE
Instalacion y dudas

### ISSUE THREAD

**Issue by emivenezian** [IIC2413/Syllabus-2024-2#42]
Hola, no me queda claro que hay que instalar. Lei las issues y algunas dicen que hay que instalar ubuntu y otra que no. Tambien intente conectarme al servidor pero me sale esto 
ssh mveneziar@pavlov.ing.puc.cl

The authenticity of host 'pavlov.ing.puc.cl (146.155.13.56)' can't be established.
ED25519 key fingerprint is SHA256:Uh29lZP3uvufjE3OG0CVR6MuMBLXxjidAdyhXgaXPmY.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

**Comment by TomasKetterer** [comment]
Si lo intentas nuevamente, no te dice que coloques una clave? En caso de que te funcione, recuerda que tu clave es tu número de alumno (al colocar la clave no se va a ver como ingresas los caracteres ya que estarán ocultos pero sí estarás escribiendo) y trata de cambiar la clave cuando logres entrar.
