### ISSUE TITLE
Tiempo de ejecución

### ISSUE THREAD

**Issue by k0rval4n** [IIC2413/Syllabus-2024-2#43]
¿Cuál sería el tiempo de ejecución máximo a la hora de cargar los datos? ¡Muchas gracias! 😄

**Comment by TomasKetterer** [comment]
Hola! El tiempo de ejecución debería ser bastante bajo, como máximo unos minutos, en caso de que ya esté corriendo en 10 minutos o algo así hay algo que se está haciendo mal.
