### ISSUE TITLE
Diurno y Vespertino al mismo tiempo 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#46]
<img width="365" alt="duda 1 p0" src="https://github.com/user-attachments/assets/13bdd261-3f2a-45c3-9f20-8efeda361dc1">
hola! que pasa cuando la jornada de un profesor es tanto diurno como vespertino. ¿Que debo poner en la matriz 3 de datos profesor en este caso? Adjunto foto 
Saludos y muchas gracias

**Comment by Mateodlcc** [comment]
Quedará a tu criterio, puedes dejarlo como "ambos" o solo uno de ellos, el que escojas.
