### ISSUE TITLE
Material de instalacion PHP en Linux

### ISSUE THREAD

**Issue by waknaudt** [IIC2413/Syllabus-2024-2#5]
Hola, solo se subio material de instalacion para Windows y MacOS. Como se instala en linux?

**Comment by TomasKetterer** [comment]
Hola! Como ayudantes abordamos Windows y MacOS porque son los sistemas operativos con los que contamos. No tenemos un tutorial de cómo instalar en linux, pero puedes seguir este tutorial de youtube [https://youtu.be/vUxr0yYiQbE?si=WrCyVXA-GXTjm_-1](url). En caso de que no funcione puedes tratar de buscar otro tutorial o hacernos más dudas por aquí mismo para tratar de ayudarles con la instalación en linux :)
