### ISSUE TITLE
Numero de estudiante

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#50]
Hola, si tengo el rut de un estudiante pero no tengo su numero de estudiante este dato debe ser eliminado?

**Comment by waldoosg** [comment]
Si, debe ser eliminado porque el dato de número de alumno es no nulo según el enunciado

**Comment by cataruze** [comment]
ya gracias, eso si sigo confundida con que datos (no nulos) tengo que eliminar si no tiene datos o reemplazarlo con un valor invalido?

**Comment by oliviallanosj** [comment]
pero en el caso que el dato fuera nulo (como el numero de alumno en el caso anterior), no se debería poner una "x", y en ese caso no se elimina?

**Comment by cataruze** [comment]
y por otro lado puedo asumir que el único tipo de personas dadas en los archivos son estudiantes, administrativos o profesores? es decir que no hay "civiles"

**Comment by waldoosg** [comment]
Toda la razón, cuando hay un dato donde falte un atributo y este es "no nulo", debe hacerse una marca para identificarse, como poner "x"

**Comment by oliviallanosj** [comment]
y en ese caso, el dato se considera como correcto y no se elimina? y al crear las matrices van a haber datos con "X"? eso es correcto?

**Comment by waldoosg** [comment]
Exacto, van a haber datos en las matrices con valores "x"

**Comment by cataruze** [comment]
entonces si no tengo el numero de estudiante igualmente lo debo agregar a la matriz estudiante?

**Comment by waldoosg** [comment]
> y por otro lado puedo asumir que el único tipo de personas dadas en los archivos son estudiantes, administrativos o profesores? es decir que no hay "civiles"

En principio, todos los datos deberían tener un rol como estudiante, administrativo o profesor, pero si ocurre el caso que existan personas con rol de  "civil", o sea, que no pertenezca a ninguno de los roles, solo se añade a la matriz de personas.

**Comment by waldoosg** [comment]
> entonces si no tengo el numero de estudiante igualmente lo debo agregar a la matriz estudiante?

Exacto, necesitas rellenar el dato con "x"

**Comment by cataruze** [comment]
y puedo asumir que todos los datos de numero de estudiante del archivo corresponden a un numero o vacio? es decir que no habrá una letra en este campo?

**Comment by waldoosg** [comment]
Te recomiendo no asumirlo y utilizar la función is_numeric de php.
https://www.php.net/manual/es/function.is-numeric.php

**Comment by cataruze** [comment]
ya gracias, y si llega a ocurrir eso simplemente elimino el dato o no?
