### ISSUE TITLE
Nivel 0 válido

### ISSUE THREAD

**Issue by k0rval4n** [IIC2413/Syllabus-2024-2#53]
¡Hola! En el enunciado se menciona que los niveles son Ingreso, 1, ..., 10, Licenciado. Sin embargo, en el archivo se encuentran instancias con nivel = 0. ¿Debemos considerarlo como un error y no considerar la instancia? (Me choca que un curso se imparta antes del primer semestre de la carrera). ¡Muchas gracias!

Adjunto captura del enunciado:
![image](https://github.com/user-attachments/assets/17587959-9b01-4b08-addf-1551b78d6d51)

**Comment by ypne** [comment]
Los niveles que indicas corresponden a los de los estudiantes.
En el caso de los cursos, el nivel corresponde al semestre al cual pernetece el curso en la malla. El valor 0 significa que el curso no tiene un semestre asignado.

**Comment by k0rval4n** [comment]
> Los niveles que indicas corresponden a los de los estudiantes. En el caso de los cursos, el nivel corresponde al semestre al cual pernetece el curso en la malla. El valor 0 significa que el curso no tiene un semestre asignado. El valor 0 es válido.

Super, muchas gracias profesor! 👍
