### ISSUE TITLE
Limpieza de datos

### ISSUE THREAD

**Issue by nicolasvialy** [IIC2413/Syllabus-2024-2#55]
Hola! No me queda claro con el enunciado si al limpiar los datos solo debemos fijarnos en cosas de formato (ej: que los números de estudiante sean un int no nulo) o también en el contenido de los datos (ej: que todos los mails institucionales tengan @lamejor.cl)?

**Comment by TomasKetterer** [comment]
Hola! Deben limpiar los datos de ambas formas, la idea es que se cumpla el formato de los datos y las reglas de negocio, por lo que el contenido de los datos también es importante.
