### ISSUE TITLE
Flujo de programa

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#56]
Hola!
 Espero se encuentren bien. 
 Quería consultar por el flujo del programa, ya que no me queda claro si siempre nos van a dar un RUT y después un curso o si, de acuerdo a lo que se nos entregue, debemos determinar cuál de las dos consultas se está haciendo. 

Saludos!

**Comment by ypne** [comment]
lo responderé en discussions
