### ISSUE TITLE
Memoria disponible

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#58]
Hola! Al crear todas las matrices el código me entrega el error: 'Fatal error: Allowed memory size of 134217728 bytes exhausted' ¿Cómo manejo esto? Ya que no podría entregar un código que tenga todas las matrices implementadas, quizás solo dejar la función que las crea y en base a esto se evalúe como fue mi desarrollo. 

Gracias!

**Comment by ypne** [comment]
De qué tamaño estás definiendo las matrices? Lo estás haciendo en el server? Los datos pesan 12MB

**Comment by cataruze** [comment]
Hola, me pasa lo mismo pero al definir la matriz persona, que se supone que no tiene elementos repetidos, porque me saldrá este error, uso listas para guardar los datos
