### ISSUE TITLE
Problema con instalación de FileZilla

### ISSUE THREAD

**Issue by Indo0103** [IIC2413/Syllabus-2024-2#6]
Me sale el siguiente error al intentar instalar FileZilla
![image](https://github.com/user-attachments/assets/fe9900f8-a025-4922-bd6b-fc930775668b)

**Comment by TomasKetterer** [comment]
Hola! Eso está pasando por un bloqueo por parte de tu antivirus. Lo que se puede hacer en ese caso es desactivarlo, hacer la instalación y volver a activarlo. Probablemente el antivirus que te está diciendo eso es windows defender y si no me equivoco, al desactivar el firewall de windows ya podrías hacer la instalación. Es muy importante que luego de instalar filezilla vuelvas a activar tu antivirus :)
