### ISSUE TITLE
Problema con un encabezado del Archivo2.csv RUN

### ISSUE THREAD

**Issue by anomvlito** [IIC2413/Syllabus-2024-2#60]
Tengo un problema con un encabezado del Archivo2.csv que no he editado, solo lo he leído tal como indican las instrucciones.
Estoy trabajando con los "diccionarios" de php, usando keys. 

Resulta ser que cuando extraigo los encabezados para usarlos como llaves de un array que yo cree, tengo un problema super especifico con el encabezado primer encabezado del archivo, luego de varios intentos y estudiar que estaba fallando me di cuenta que al aplicarle var_dump() al encabezado extraído del archivo, en consola me sale esto RUN string(6), al parecer tiene caracteres especiales o espacios ocultos, que he tratado de resolver el problema sin solucionarlo aún con código del estilo:

$encabezado = preg_replace('/[\x00-\x1F\x7F]/u', '', $encabezado);
 
 Lo único que pude hacer es cambiar a mano la llave en mi código PHP (sin modificar el archivo original), lo cual no considero que sea correcto, pareciera una solución parche. 
 
 Sospecho que es algo del formato de codificación de caracteres y tratado con mb_convert_encoding para transformar 'UTF-8' y ahi si que arruino el codigo jaja.
 
¿Qué recomiendan hacer en estos casos? Mi código funciona con el parche, pero no sé qué más documentación buscar al respecto.

**Comment by ypne** [comment]
Efectivamente, hay 3 caracteres HEX EF BB BF antes de RUN, que bueno que el programa lo encontró. Como es el encabezado, ese registro solo se descarta.
Si encuentras en los datos ese tipo de violacion a los tipos, la acción es copiar la tupla en un archivo de registros con error y luego tomar las acciones correspondientes:
-Si es posible corregir
-Descartar esa tupla y todas las que están relacionadas con ella.

Por ejemplo: Si hay un estudiante con datos inválidos y no se pueden corregir se debe descartar, pero junto con ello se deben descartar todos los cursos que tomó.
Saludos
