### ISSUE TITLE
FileZilla

### ISSUE THREAD

**Issue by faresdababneh** [IIC2413/Syllabus-2024-2#61]
Hola, ¿Subirán algún tutorial de FileZilla? Lo que pasa es que no entiendo como usarlo y trabajar en el server como se me preguntó en una issue que hice (Issue #58 ).

Muchas gracias.

**Comment by TomasKetterer** [comment]
Hola! En la ayudantía 2 se enseñó a usar filezilla y como trabajar en el servidor. En el pdf de esta ayudantía están algunos comandos importantes que se pueden utilizar, pero no se subirá un tutorial ya que se mostró todo en la ayudantía. En caso de ser necesario, trata de buscar algún tutorial en google o youtube

**Comment by ypne** [comment]
No es necesario usar filezilla, basta con un sftp
