### ISSUE TITLE
Duda Archivo 2

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#63]
Hola, buenas tardes.

El archivo 2 contiene columnas que no están mencionadas en el enunciado: PATERNO, MATERNO y NOMBRES. ¿Se trata de un error en el enunciado o en el archivo que nos proporcionaron?

Muchas gracias por su atención.

**Comment by noamsito** [comment]
Hola, en la issue #31 ya se respondió lo que preguntas. :)

**Comment by cataruze** [comment]
holaaa, en este caso esas columas deven cumplir los mismos requisitos que pedia estudiantes, por ejemplo con la nulidad?
