### ISSUE TITLE
Duda: Jornada: Diurno o Vespertino

### ISSUE THREAD

**Issue by Utmite** [IIC2413/Syllabus-2024-2#64]
Hola, buenas tardes:

Hay profesores en el archivo 2 que tienen la jornada diurna y vespertina al mismo tiempo, y opté por poner en la matriz de profesores en el campo de "Jornada" el valor "ambas". ¿Está bien?

Gracias por su atención.

**Comment by lucolhabe** [comment]
Hola, si pero recuerda indicarlo en el informe.
