### ISSUE TITLE
Grado académico - Matriz Profesor

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#65]
Hola, en el enunciado se menciona que en el Archivo 2, el grado académico correspondería a "Bachiller", "Licenciado" y "Doctor", sin embargo, en el documento .csv no se encuentra bachiller, pero en cambio sí existe MAGISTER, LICENCIATURA, DOCTOR Y DOCTORA . No sé si sea un error, pero quedo con la duda ya que en la matriz de profesor, se pide que se coloque el grado académico: "Bachiller", "Licenciado" o "Doctor" (o nulo), y no otras opciones. Qué debería colocar en la matriz?

**Comment by cataruze** [comment]
hola, yo tambien tengo dudas con esto, al limpiar los datos tomare como invalido si tengo por ejemplo "MAGISTER" o será error del enunciado que solo admite "Bachiller", "Licenciado" y "Doctor"?

**Comment by MartyMolina** [comment]
Decidan ustedes si prefieren utilizar "Bachiller", "Licenciado" y "Doctor", o "Magíster", "Licenciatura", "Doctor" y "Doctora". Asegúrense de mencionarlo claramente en el informe.
