### ISSUE TITLE
Revisión Entrega 0

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#66]
Hola! quisiera saber cómo es que se va a revisar la tarea, ya que me he dado cuenta que se entregan muchas libertades para su resolución (mientras todo se señale en el informe, claro). 
Con esto me refiero a que me ayudaría y aclararía harto entender qué es lo que me evaluarán y con qué criterio, ya que creo que no estoy entendiendo al 100% lo que esperan en la entrega como correcto. 
Por ejemplo, bastará con que solo que los outputs y las matrices tengan sentido con lo que coloqué en el informe? o que se obtengan unos datos en específico en las matrices pedidas? o si aparte de los outputs se revisará el código línea por línea? si acaso usarán otros archivos para filtrar y hacer las consultas? ...

Muchas gracias de antemano.

**Comment by ypne** [comment]
Hola, responderé en Issues
