### ISSUE TITLE
Secciones - Matriz Cursos

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#67]
El atributo "Secciones" se describe como "_int, número de secciones del curso_". Lo cual no me queda claro si debo poner en ese dato cada sección (repetir la fila en la matriz por cada número de sección que existe de cada curso) o poner el total de secciones en ese curso (solo una fila por curso, con su cantidad de secciones)?

**Comment by noamsito** [comment]
Hola, se refiere al número total de secciones que hay en el curso. Esto lo puedes interpretar en base al nombre de la matriz "Cursos: <ins>Stock</ins> de cursos....". :)

**Comment by SebastianArroyoSanchez** [comment]
Hola, filtrando los datos me di cuenta que existen varios ramos con igual nombre y distintas siglas y secciones, por ejemplo:

HF013456;"PSICOHISTORIA POLITICO";1;2

HF023456;"PSICOHISTORIA POLITICO";1;2
HF023456;"PSICOHISTORIA POLITICO";2;2

DV023456;"PSICOHISTORIA POLITICO";1;2
DV023456;"PSICOHISTORIA POLITICO";2;2

DS033456;"PSICOHISTORIA POLITICO";1;2
DS033456;"PSICOHISTORIA POLITICO";2;2


Es correcto mantener para esta matriz los siguientes:
HF013456;"PSICOHISTORIA POLITICO";1;2
HF023456;"PSICOHISTORIA POLITICO";2;2
DV023456;"PSICOHISTORIA POLITICO";2;2
DS033456;"PSICOHISTORIA POLITICO";2;2


En resumen mantengo la cantidad de secciones por sigla ¿Está correcto?

**Comment by MartyMolina** [comment]
Manten la cantidad de secciones por sigla. Lo que observaste es una situación que ocurre en la realidad, donde hay ramos que se llaman igual pero, en realidad, son distintos según su sigla.
