### ISSUE TITLE
Longitud archivo bananer

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#68]
Hola, cuantas líneas máximo puede tener el archivo bananer y se pueden tener más archivos aparte?

**Comment by noamsito** [comment]
Hola, no hay un límite específico en la cantidad de líneas que puede tener el archivo Bananer.php. Lo más importante es que el código cumpla con los requisitos del enunciado y sea lo suficientemente limpio y organizado para facilitar su desarrollo y corrección.

En cuanto a lo segundo, ¿Te refieres a archivos de ejecución o archivos asociados a las matrices? 

Si te refieres a lo primero puedes incluir más archivos, siempre que el archivo "bananer.php" se mantenga como el principal y el resto funcione como complementos para organizarse. Además de que expliques en el informe estos archivos extras (recuerda que tienes que especificar en el informe las instrucciones para ejecutar el programa). 

Sin embargo, si te refieres a lo segundo en la _Nota 1_ al final de la sección de las reglas de negocio se menciona lo siguiente: _"Si lo encuentra necesario, puede definir otras matrices, además de los indicados, más arriba y entregar el archivo con su contenido. En este caso, Ud. deberá dejarlo plasmado en el informe."_
