### ISSUE TITLE
mail personal

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#69]
hola, he estado viendo que los mails personales en el archivo 1 terminan en @llimail.kom, esto se debe cumplir para todos los mails personales para considerarlo un mail valido, o solo que sea un str?

Gracias de antemano

**Comment by noamsito** [comment]
Hola, en el enunciado no se menciona que los emails personales deban de cumplir con @llimail.kom, solamente que los emails institucionales contengan @lamejor.cl. Por lo tanto, con tal de que el mail personal no tenga @lamejor.cl, sino que un dominio (nombre@_dominio_) diferente debería bastar.

**Comment by ypne** [comment]
Es correcto lo que mencionas. El mail personal puede ser cualquiera con el formato nombre@dominio
