### ISSUE TITLE
Formato Informe

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#7]
Hola! Quisiera saber si existe algún formato que seguir o los requerimientos mínimos que deberíamos incluir en el informe? Siento que las explicaciones han sido muy ambiguas y no me queda muy claro qué sería un buen informe.

**Comment by noamsito** [comment]
En cuanto al formato del informe, no hay algo definido. Lo importante es que se desarrollen adecuadamente todos los puntos mínimos solicitados en el enunciado, asegurando una buena redacción y una extensión apropiada conforme a lo requerido.

Aquí te adjunto los contenidos que se piden (extraído del enunciado): 
1. Análisis de los datos (tipos) entregados en los archivos.
2. Tipos de errores de datos detectados por el programa y forma de solución utilizada. 
3. Nombre de los archivos de salida y explicación de su contenido.
4. Instrucciones para ejecutar el programa (muy importante).

**Comment by MathiasPrett** [comment]
Hola. Pueden por favor desarrollar un poco mas la idea del punto 1: 

"Análisis de los datos (tipos) entregados en los archivos."

Gracias.

**Comment by noamsito** [comment]
La idea es que realicen un análisis sobre los errores relacionados con los tipos de datos. Por ejemplo, si se espera que un dato sea de tipo 'string' pero en el archivo aparece un 'boolean', deben incluir este análisis en su informe.
