### ISSUE TITLE
RUN + DV

### ISSUE THREAD

**Issue by CatalinaBO** [IIC2413/Syllabus-2024-2#70]
Hola, limpiando los archivos de la tabla me di cuenta que hay un mismo RUN que tiene distinto DV. Con esto puedo asumir que son distintas personas? Esto en base a que los nombres completos son distintos y los planes de estudio también. Por último, al momento de realizar las consultas e imprimir las matrices, puedo solicitar por consola el rut completo (RUN + DV) o es estrictamente necesario que sea únicamente el RUN (como se solicita en las reglas de negocio)? Pregunto esto ya que si no se solicita el DV, los datos de las personas que tienen el mismo RUN se mezclarían. 
Muchas gracias

**Comment by ypne** [comment]
Hola, cuando se menciona RUN, estamos hablando del Atributo solamente, no incluye el DV. Si hay 2 personas con el mismo RUN es un error y no hay posibilidad (con los datos que tienen ahora) de corregirlo. Debieran eliminar los datos de uno de los dos repetidos y dejarlo documentado en el informe.
