### ISSUE TITLE
Verificación de largo y contenido de atributos

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#72]
Hola!
 Espero se encuentren súper. Quería consultar qué tan minucioso debo ser con la verificación de información de las tuplas.

1.  Por ejemplo, podría ser estricto exigiendo que el RUN tenga **exactamente** 8 dígitos, similar al número de alumno que tiene 4 dígitos. ¿Es necesario hacer la verificación a ese nivel o basta con que sean menos de 8 (o 4) dígitos en primera instancia?
2.  También, por ejemplo, **¿podría pasar que mi correo institucional sea el mismo que el personal?** No me queda claro si sirve para el personal sirve cualquier correo (incluido los @lamejor.cl) o si debe cumplir algo en concreto.
3. ¿Se puede asumir que variables como "Cohorte", "Fecha Logro" y "Última Carga" tienen el formato 20XX-0X? ¿Es necesario verificar casos similares como "Código de plan" o "Sigla del curso" que tienen patrones más o menos definidos?
4. ¿Es necesario modificar "Bloqueo" por true/false? Lo pensaba más que nada para cumplir con que sea un booleano.

Perdón por lo minucioso de las preguntas, pero quería tener claro estos casos borde 😔. Gracias de antemano! 😁

**Comment by MartyMolina** [comment]
1. Si es necesario, revisa las extensiones de los números de la manera correspondiente. 2. En cuanto al correo institucional, puede coincidir con el personal. 3. No es necesario verificarlo, pero podrías incluirlo como una observación en el informe. 4. Puedes cambiarlo a "true/false" si lo prefieres.
