### ISSUE TITLE
Valores invalidos o nulos

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#73]
Hola, cuando hay que poner un valor dado que no puede ser nulo, y si tengo que ese valor además tiene que ser un int puedo reemplazar por una X o necesariamente tengo que poner un int no válido?

**Comment by cataruze** [comment]
Y también si tengo un valor invalido ej 8 para una nota, pero puede ser nulo, lo tengo que reemplazar por una X o lo dejo vacío?

**Comment by lucolhabe** [comment]
Hola, para el primer caso podrias decidir cambiarlo por un int que represente un valor invalido, a tu preferencia, pero debe quedar claro en el informe para la corrección. En la segunda pregunta el mismo caso, tu decides como interpretas eso pero debe ir en el informe tu resolución.
