### ISSUE TITLE
[Solicitud] ¿Podemos utilizar la extensión mbstring?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2413/Syllabus-2024-2#74]
## Solicitud

¿Podemos utilizar la extensión `mbstring` de **PHP**? Es para manejar la codificación de los archivos de una forma consistente. Noté que esta no está habilitada por defecto en el paquete de instalación, por lo que en el servidor no está disponible. ¿Es posible que la habiliten para usarla? Al fin y al cabo de se trata de una funcionalidad del lenguaje.

**Comment by waldoosg** [comment]
No se pueden utilizar librerías externas
