### ISSUE TITLE
Profesor y administrativo

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#76]
Hola sigo con la duda de la distinción entre profesor y administrativo, ya que yo habia pensado que si habia informacion en jerarquia se referia a un profesor y si habia en cargo se referia a un administrativo, pero al revisar los datos, hay algunos que no poseen información en niuno de estos, en este caso en cual lo clasificaria dado que ambos admiten nulos, tambien hay datos en jerarquia que dicen "SIN JERARQUIZAR" eso como lo interpreto?
Por otro lado, en la matriz de profesor me piden jerarquia y cargo, lo cual me confunde con lo que tenia pensado como clasificación.

Gracias de antemano

**Comment by ypne** [comment]
Es profesor sin jerarquizar aún
Si además tiene cargo es administrativo, Si en la matriz de profesor tiene cargo lo ingresas también.

**Comment by cataruze** [comment]
No entendí muy bien, entonces siempre asumo que los datos del archivo 2 son profesores o solo si tiene información en jerarquía? Y si tiene cargo administrativo también es administrativo?

**Comment by cataruze** [comment]
También hay datos en jerarquía que son por ejemplo instructor esto también lo considero cómo profesor, o solo los datos que dicen profesor …?
