### ISSUE TITLE
Reglas de negocio y descartar datos

### ISSUE THREAD

**Issue by FelipeFuentesG** [IIC2413/Syllabus-2024-2#77]
Hola!,

De issues anteriores entendí que un RUN inválido implica descartar el dato completo. ¿Aplica lo mismo si se incumple alguna de las otras reglas de negocio? Por ejemplo, si la nota o nivel del curso no cumple lo indicado, ¿entonces el dato se descarta también? ¿o al igual que los otros atributos se marcan con una "x" si están incorrectos y no se pueden arreglar?

**Comment by tom4stapia** [comment]
Hola! En el caso de RUN repetidos, efectivamente se debe descartar uno. Sin embargo, para otros atributos que no cumplen con las reglas de negocio, no necesariamente implica descartar la fila completa, la idea es conservar la mayor cantidad de datos. Puedes marcar los incorrectos con un "-1" o "x", según corresponda, y mencionar en tu informe cada caso y cómo fue tratado.

**Comment by faresdababneh** [comment]
Pero yo de una issue anterior había entendido que habían ciertos requerimientos mínimos (El RUN es un ejemplo), siendo principalmente aquellos asociados con las reglas del negocio, por lo que consideré descartar aquellas filas que tuvieran problemas con 'Nivel' o 'Último logro', ya que nuevamente, en las reglas del negocio están especificamente mencionados que deben cumplir cierto formato. 

Por lo tanto, ¿Puedo descartar aquellas filas que no cumplan con el formato de 'Nivel' o 'Último logro'?. 

Muchas gracias

**Comment by tom4stapia** [comment]
Mientras detalles en tu informe cómo manejaste cada caso, no debería haber problema.
