### ISSUE TITLE
Valides datos str

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#79]
Hola, para los datos como nombre, además de ver si es str también tengo que verificar que tenga solo letras? 
por ejemplo en el archivo 2 en grado académico en una fila hay un cero, en este caso si está como str lo acepto o tomo como invalidó?

Gracias de antemano

**Comment by tom4stapia** [comment]
Hola! Queda a tu criterio si quieres verificar que solo tengan letras, en ambos casos te recomiendo hacerlo y mencionarlo en tu informe.
