### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#8]
Hola, en el enunciado de la tarea sale: "Cargar en su cuenta del equipo Linux los archivos entregados en el repositorio", a que se refiere con cuenta del equipo Linux? Este hay que instalarlo? y que más hay que instalar aparte de php y fillzilla?
Y la tarea se deve hacer desde Linux o puedo ocupar Windows?

Gracias de antemano.

**Comment by TomasKetterer** [comment]
Hola! Como se mencionó en la ayudantía de hoy, se puede usar windows para hacer la tarea. Cuando dice "Cargar en su cuenta del equipo linux" se refiere a cargar los archivos al servidor, que como mostramos el día de hoy, es subir los archivos a filezilla (o en su defecto a otro FTP).
