### ISSUE TITLE
Repeticiones e inconsistencias

### ISSUE THREAD

**Issue by njllanos** [IIC2413/Syllabus-2024-2#80]
Hola tengo una duda en cuanto a las limpiezas de los datos.

Primero en cuanto a repeticiones, **en los archivos proporcionados existen ciertas lineas repetidas, ¿en la limpieza esperada se espera que sean descartadas?** Lo pregunto dado que en el enunciado no se comenta acerca de esto en la parte de limpieza, sino que en la realización de las matrices. 

En cuanto a las inconsistencias, existen ciertos datos que no inclumplen ninguna regla establecida en el enunciado, aunque sin embargo parecen ser inconsistentes. Ejemplos de esto que he encontrado son; **estudiantes que hacen el mismo curso, en el mismo periodo, pero en secciones distintas o personas tienen 2 numeros de alumnos asociados que, no obstante, con ambos numeros de alumnos tienen exactamente los mismos cursos hechos y las mismas notas. En ambos casos no se incumple la repeticiones de datos, por lo que podrían ser incluidas en las matrices. Que se deberiera hacer en estos casos?** Y, en caso de hacer algo, ¿como se espera que se detecten?

**Comment by ypne** [comment]
Hola
1.- Las matrices deben contener solo filas que no se repitan
2.- si encuentran inconsistencias como el mismo estudiante en el mismo curso-periodo en 2 secciones diferentes con notas diferentes lo deben dejar establecido en el informe y eliminar ese dato.
3.- siempre hay que rescatar el máximo de los datos válidos, por lo que se puede corregir,  deben hacerlo, si se puede marcar el dato como inválido (por ejemplo teléfono con mas de 9 cifras ) se puede reemplazar por un valor que lo identifique como tal (000000000).
