### ISSUE TITLE
Problema matriz 2.Estudiante 

### ISSUE THREAD

**Issue by josefa00** [IIC2413/Syllabus-2024-2#81]
hola! en la matriz 2 se pide el numero de estudiante de la persona sin embargo un rut puede tener mas de un número de estudiante; que hago en este caso? tengo que poner todos los números asociados a ese estudiante?

**Comment by ypne** [comment]
si, uno por fila

**Comment by ssepul21** [comment]
Hola profe! 
 Respecto a ese mismo caso, a la hora de mostrar la salida, debemos mostrar solo la información de la carrera más reciente, en orden cronológico o queda a nuestro criterio??

**Comment by ypne** [comment]
Hola
En el caso de que un RUN tenga más de una carrera (número de estudiante) deben mostrar ambas, pero da lo mismo cuál muestran primero. Con tal que no mezclen datos todo bien. Saludos
