### ISSUE TITLE
Matriz prfesores y matriz administrativos

### ISSUE THREAD

**Issue by antoer** [IIC2413/Syllabus-2024-2#82]
Para crear la matriz de profesores y administrativos, como discrimino para saber donde poner a cada persona. En la matriz de porfesores pongo todos los datos del archivo 2?

**Comment by ypne** [comment]
si tiene cargo es administrativo, si tiene jerarquía (aunque sea "sin jerarquia") es profesor, si tiene ambos es ambos

**Comment by cataruze** [comment]
Y si no tiene ni uno, no lo consigo para ni una de esas matrices.? Solo en personas?

**Comment by jose-delasotta** [comment]
A qué te refieres con que sea "sin jerarquia"?

**Comment by ypne** [comment]
> A qué te refieres con que sea "sin jerarquia"?
> 
> 

Si en el valor del atributo es el indicado antes
