### ISSUE TITLE
Consulta de manejo de caracteres inválidos

### ISSUE THREAD

**Issue by ssepul21** [IIC2413/Syllabus-2024-2#83]
Hola!
 En la "Nota 3", primer inciso del final del enunciado se menciona el manejo de "**error de tipo codificación**". ¿Existe una manera efectiva de ver si puedo tener problemas con ello? Probando en mi terminal al menos no he tenido problema, pero no sé si es correcto o  no basarse solo en eso.
 Para el manejo de estos errores, quería saber si debemos utilizar **determinado _encoding_** para verificar que abarquemos de manera correcta este error ya que, por lo que tengo entendido, este error puede aparecer o no (y de forma diferente) dependiendo del _**encoding**_ y el **sistema operativo**.

 Entiendo que el servidor está en Linux, por lo que mi duda va más que nada al _encoding_ a considerar. 

Gracias de antemano! 😁

**Comment by ypne** [comment]
Más que el encoding lo importante es los caracteres válidos son los del idioma castellano, dígitos y @.  Las faltas de ortografía no cuentan como error.
