### ISSUE TITLE
¿Nota sin calificación?

### ISSUE THREAD

**Issue by maromero-21** [IIC2413/Syllabus-2024-2#84]
Hola! tengo una duda.
¿Hay algún escenario en donde tengamos el valor de la nota, pero sin la calificación? Estuve revisando y hay una cantidad de filas en donde se tiene nota, pero no hay calificación y quería saber cómo debiese actuar mi programa en este caso.

**Comment by ypne** [comment]
Hola
Pueden reportarlo como error y ocupar una marca que indique calificación inválida o
usar esta tabla para corregir
Ambas soluciones son válidas
Calificaci´on Descripci´on Nota Resultado
SO Sobresaliente 6.6 - 7.0 Aprobatorio
MB Muy Bueno 6.0 - 6.5 Aprobatorio
B Bueno 5.0 - 5.9 Aprobatorio
SU Suficiente 4.0 - 4.9 Aprobatorio
I Insuficiente 3.0 - 3.9 Reprobatorio
M Malo 2.0 - 2.9 Reprobatorio
MM Muy Malo 1.0 - 1.9 Reprobatorio
NP Nota Pendiente nulo Curso incompleto
EX Eximido nulo Aprobatorio
A Aprobado nulo Aprobatorio
R Reprobado nulo Reprobatorio
nulo nulo Curso Vigente

**Comment by maromero-21** [comment]
Gracias!

**Comment by maxweinreichs** [comment]
Tengo una duda relacionado a este mismo issue. Si queremos usar la tabla de conversión para corregir, entiendo que cuando tenemos una nota pero no una calificación podemos asignarle una con la tabla, pero cuando el valor de la nota es nulo la tabla también sugiere poner EX, A o R. Como sabemos cual ponerle si no sabemos el resultado que obtuvo el alumno en el curso?

**Comment by ypne** [comment]
No se puede porque estaría usando una calificación válida pero no se sabe si la nota nula es válida o no. 
Las notas nulas son válidas solo si la calificación es válida. O sea
If calificación es EX, A, R -> nota = nulo
Un caso especial es if periodo del curso es 2024-1 -> calificación = nulo and nota=nulo porque es un curso vigente que aún no termina.
