### ISSUE TITLE
Dudas varias Tarea Etapa 0

### ISSUE THREAD

**Issue by waknaudt** [IIC2413/Syllabus-2024-2#85]
Hola, estoy muy confundido y no se por donde empezar la tarea. Lei todo el enunciado pero no me queda claro. Por ejemplo donde dice "Fecha de entrega: domingo 25 agosto 23:59, informe por Canvas, código y datos en el server", a que server se refiere?  

Despues en otra parte dice "Cargar en su cuenta del equipo Linux los archivos entregados en el repositorio (ftp)" , a que equipo Linux se refiere? Donde se ejecuta el programa?

En otro lado dice "Realice la detección de los datos que no cumplan con los formatos correctos, indicados más adelante y
si es posible los corrija, de lo contrario lo descarte.", a que se refiere con formatos correctos? a los tipos?

Al final dice "El contenido del informe debe contemplar:
1. Análisis de los datos (tipos) entregados en los archivos", a que se refiere con analisis de los datos?

**Comment by ypne** [comment]
Hola, estoy muy confundido y no se por donde empezar la tarea. Lei todo el enunciado pero no me queda claro. Por ejemplo donde dice "Fecha de entrega: domingo 25 agosto 23:59, informe por Canvas, código y datos en el server", a que server se refiere?
R: el server del curso informado en la ayudantía

Despues en otra parte dice "Cargar en su cuenta del equipo Linux los archivos entregados en el repositorio (ftp)" , a que equipo Linux se refiere? Donde se ejecuta el programa?
R: 1.- el equipo linux es el server con ubuntu
2.- el programa se correrá en el server para la evaluacion


En otro lado dice "Realice la detección de los datos que no cumplan con los formatos correctos, indicados más adelante y
si es posible los corrija, de lo contrario lo descarte.", a que se refiere con formatos correctos? a los tipos?
R: a los indicados en el enunciado: int, string, boolean, valores, no nulo, acepta nulos, tuplas repetidas, tuplas inconsistentes, etc.

Al final dice "El contenido del informe debe contemplar:

Análisis de los datos (tipos) entregados en los archivos", a que se refiere con analisis de los datos?
R: qué tuplas no cumplieron con las condiciones y como se trataron dichos datos
