### ISSUE TITLE
profesor administrativo y otras dudas

### ISSUE THREAD

**Issue by emivenezian** [IIC2413/Syllabus-2024-2#88]
Pregunte esto hace unos dias y no han respondido
1. Un administrativo es aquel que tiene cargo?
2. Si no tiene cargo (vacio), asumo que es profesor?
3. Si una persona no tiene cargo (y en algunos casos tampoco jerarquia) no la considero administrativo verdad? Porque si la considerara, todas las personas del archivo 2 serian administrativos
4. En otra issue dijeron que si tiene cargo es administrativo, pero en la matriz de administrativo dice q el cargo admite nulos. De eso yo entiendo que pueden haber administrativos sin cargo. No me queda claro cual es la definicion de administrativo.
5. En otra issue dijeron que si tiene jerarquia es profesor, pero en la matriz de profesor dice q jerarquia admite nulos. De eso yo entiendo que pueden haber profesoires sin jerarquia. No me queda claro cual es la definicion de profesor.
6. Yo entendi que profesor es aquel que tiene al menos una jornada, ya sea o diurna o vespertina o ambas. Es el unico item de la matriz de profesor que no dice que admite nulos, por ende la entendi como condicion necesaria.

**Comment by noamsito** [comment]
Holaa, aquí te dejo las respuestas a tus preguntas:

1. Sí, por definición y como menciona el profesor en la issue #82 un administrativo es aquel que tiene cargo, sin embargo, si posee jerarquía y cargo, entonces corresponde a ambos roles. 
2. Podrías hacerlo dependiendo del caso, como se menciona antes si tiene jerarquía entonces sería un profesor, pero ten ojo que pueden haber algunos casos donde tal vez no tiene ningún dato descriptivo para ello, por lo tanto debes de tomar la decisión sobre qué matriz añadirlo o no.
3. No, porque pueden haber casos en los que no tenga jerarquía, pero pueden que tengan  horas asignadas, por lo tanto no podrías incluirlo como un administrativo, ya que en dicha matriz no se consideran dichos datos. 
4. Claro, pueden haber adminstrativos sin cargo, gracias a lo que mencionas. 
5. En efecto, si tiene jerarquía corresponde a un profesor. Sin embargo, un profesor también es aquel que tiene un grado académico u otros datos como se especifica en la matriz del enunciado. 
6. La restricción que mencionas está especificada en la parte de los archivos, lo mismo ocurre para algunos datos de la matriz persona.
