### ISSUE TITLE
Correos con tildes y Ñ

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#89]
Hola, quisiera saber si los correos con tildes deben considerarse como válidos o no? y los que contienen ñ Ñ?

**Comment by lucolhabe** [comment]
Hola, si se consideran validos en ambos casos, ten cuidado con que no existan errores de codificación.

**Comment by coniverav** [comment]
Y los tildes que están al revés? por ejemplo en ANAV**Ì**.ORÓSTICA@llimail.kom

**Comment by MartyMolina** [comment]
También
