### ISSUE TITLE
Archivo entregado por consola

### ISSUE THREAD

**Issue by carlosmartellus** [IIC2413/Syllabus-2024-2#9]
Hola, tenemos que recibir un archivo que se entrega por consola? Tipo
php Bananer.php Archivo_1.csv
cosa que nos entregue un nuevo archivo ya corregido?

**Comment by Mateodlcc** [comment]
No hace falta hacerlo así, puedes referenciar el archivo dentro del código.

Lo importante es que indiques en el informe lo que hiciste y como se debe correr tu código para que los ayudantes puedan hacerlo.
