### ISSUE TITLE
Duda jornadas archivo 2

### ISSUE THREAD

**Issue by maxcareyf** [IIC2413/Syllabus-2024-2#91]
Hola. Tengo una duda respecto al manejo de profesores/administrativos, específicamente relacionado con la tabla de profesores. Hay profesores/administrativos que son tanto diurnos como vespertinos, pero las instrucciones especifican que este atributo de la tupla puede ser solo diurno o vespertino. Para casos como este el dato se debe tratar como inconsistente, tener una fila para cada jornada o quedarse con solo una jornada al azar? Gracias.

**Comment by lucolhabe** [comment]
Hola, queda a tu criterio si dejarlo como "ambos" o poner solo uno de ellos, pero recuerda dejarlo claro en el informe.
