### ISSUE TITLE
Profesores sin jornada/Profesores sin cargo ni jerarquía

### ISSUE THREAD

**Issue by coniverav** [IIC2413/Syllabus-2024-2#93]
Hola, se consideran como buenos o malos los profesores que no tienen jornada ni diurna ni vespertina? y los profesores sin cargo ni jerarquía?

**Comment by noamsito** [comment]
No se consideran como errores. Como dice el enunciado esos datos admiten nulos. 
![Screenshot 2024-08-22 at 11 19 08 PM](https://github.com/user-attachments/assets/a3448af9-848f-4b7c-ab4f-d2e57bb10b26)
![Screenshot 2024-08-22 at 11 19 19 PM](https://github.com/user-attachments/assets/cdffd0ba-5d9a-476b-adf9-d1b805a211e6)
