### ISSUE TITLE
Numero de estudiantes

### ISSUE THREAD

**Issue by josevalenzuelam** [IIC2413/Syllabus-2024-2#95]
Como el numero de estudiantes no admite nulos, tampoco podríamos asignarle un valorn de estudiante por defecto porque sino distintas personas tendrian el mismo numero de alumnos, en ese caso podríamos simplemente eliminar esos datos?

**Comment by lucolhabe** [comment]
Hola, puedes tomar la opción que dices de darle un valor por defecto, y sabrías que cuando salga ese valor en la matriz significa que venia nulo en los datos. También puedes decidir eliminarlos. Recuerda especificar tu decisión en el informe.

**Comment by lucolhabe** [comment]
Hola, si se pueden eliminar por no ser validos, recuerda especificarlo en el informe.

**Comment by ypne** [comment]
En el archivo 1 hay 49019 tuplas que corresponden a 1387 estudiantes lo que da un promedio de 35 tuplas por cada uno. Antes de eliminar hay que ver si, en la eventualidad que hubiera un dato nulo buscar el resto de los 34 registros a ver si tambien son nulos.

**Comment by josevalenzuelam** [comment]
perfecto! gracias
