### ISSUE TITLE
Promedio del semestre (PPS)

### ISSUE THREAD

**Issue by sbarriag** [IIC2413/Syllabus-2024-2#97]
Hola, el enunciado dice para la consulta carga académica acomulada:  "indicando periodo del curso, sigla del curso, curso, nota y calificacion. Al final de cada periodo la nota promedio del semestre (PPS)" cuando dice al final de cada periodo, se refiere a imprimir como lineas intermedias con la nota del semestre o al final hacer como un resumen 
por ejemplo 
|2010-02|DV023490|PSICOHISTORIA DE LA SEGURIDAD SOCIAL|SU|4,7
|2010-02|DV024139|OPR: ARBITRAJE|SU|4,8
|2010-02|DV024868|OPR: LEY DE RESPONSABILIDAD ADOLESCENTE|SU|4,9
|2011-01|DV023486|PSICOHISTORIA FUTURA VI|NP|
|2011-01|DV023486|PSICOHISTORIA FUTURA VI|B|5,6
Promedio 2010-02: 4,8
Promedio 2011-01: 5,6
O deberia ser 
|2010-02|DV023490|PSICOHISTORIA DE LA SEGURIDAD SOCIAL|SU|4,7
|2010-02|DV024139|OPR: ARBITRAJE|SU|4,8
|2010-02|DV024868|OPR: LEY DE RESPONSABILIDAD ADOLESCENTE|SU|4,9
Promedio 2010-02: 4,8
|2011-01|DV023486|PSICOHISTORIA FUTURA VI|NP|
|2011-01|DV023486|PSICOHISTORIA FUTURA VI|B|5,6
Promedio 2011-01: 5,6

Pregunto porque los datos no vienen ordenados por periodo, entonces al recorrerlos no necesariamente puedo decir del dato 0 al 3 por ejemplo en este caso son 2010-02 entonces queria saber si esto queda a criterio de uno
Saludos y muchas gracias

**Comment by noamsito** [comment]
En base a lo que menciona el enunciado se debe realizar de la segunda manera que muestras: "Al final de cada periodo la nota promedio del semestre (PPS)." Sin embargo, te falta incluir al final del output el PPA: "y al final del reporte la nota promedio de todos los cursos (PPA)."
