### ISSUE TITLE
Matriz cursos y niveles

### ISSUE THREAD

**Issue by cataruze** [IIC2413/Syllabus-2024-2#98]
Hola, al hacer la matriz cursos encontré que habían cursos, con la misma sigla y nombre pero con distinto nivel, que hago en este caso  para poner en la matriz? Pondré el primer dato obtenido o el menor valor o mayor del nivel?
Dejo uno de los encontrados:
![Captura de pantalla 2024-08-20 220555](https://github.com/user-attachments/assets/3d18b315-d61d-42a8-af71-72c489e7fd38)

**Comment by noamsito** [comment]
Holaa, en ese caso debes de mantener ambos cursos, ya que como puedes ver son el mismo, pero diferentes secciones. La interpretación que se le puede dar, es que son cursos donde no necesariamente están coordinadors, por lo tanto, los contenidos pueden ser distintos. Esto mismo se comenta en la issue #67, para que también le eches un vistazo.
