### ISSUE TITLE
Dudas Algunos casos

### ISSUE THREAD

**Issue by sbarriag** [IIC2413/Syllabus-2024-2#99]
Hola solo para ver si estoy trabajando bien los datos:

**I) Si tengo un dato que es string y puede ser nulo (ej: Apellido materno, mail personal)**
Solo debo asegurarme que sea string? 

**II) Si tengo un dato que es int y no puede ser nulo y ademas tiene un formato (ej: RUN)**
Debo asegurarme de que no sea nulo (si lo es lo reemplazo por una "X" o algo parecido y se acaba la revisión) luego ver si es int (si no lo es lo descarto?) y por ultimo ver que cumpla el formato (si es mas largo, tengo que truncar el numero?, o si es mas corto que haria?)

Muchas gracias

**Comment by ypne** [comment]
I) Si tengo un dato que es string y puede ser nulo (ej: Apellido materno, mail personal)
Solo debo asegurarme que sea string?
R: no me queda clara la pregunta, te refieres a que no debes verificar el contenido? Si es así si deberías considerar que un string está conformado por letras, números y signos de puntuación

II) Si tengo un dato que es int y no puede ser nulo y ademas tiene un formato (ej: RUN)
Debo asegurarme de que no sea nulo (si lo es lo reemplazo por una "X" o algo parecido y se acaba la revisión) luego ver si es int (si no lo es lo descarto?) y por ultimo ver que cumpla el formato (si es mas largo, tengo que truncar el numero?, o si es mas corto que haria?)
R: nuevamente está compleja la redacción. Por lo que entiendo estás preguntando qué hacer si un RUN es nulo siendo que la regla dice que no lo es; bueno es este caso lo podrías tratar de corregir (en el caso de los estudiantes hay un promedio de 35 tuplas para la misma persona) o reemplazar por 0 (X no es string). No es la única validación que debes hacer ya que también existe la restricción que indica que las matrices no admiten tuplas repetidas.
